<?php

namespace WCC\Notifications\Storage;


use WCAA\Models\User\User;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\UserStorage;
use WCC\Notifications\Models\NotificationContact;

class NotificationsContactsStorage extends AbstractStorage
{
    protected $tableName = 'c_notifications_contacts';

    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    /**
     * @param NotificationContact $object
     * @return NotificationContact
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        $obj->enabled = $object->enabled == 1 ? true : false;
        if ($object->user_id) $obj->user = $this->userStorage->getById($object->user_id);
        return $obj;
    }

    /**
     * @param NotificationContact $object
     * @param $fillArr
     * @return NotificationContact
     */
    public function fillByArr($object, $fillArr = [])
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        $obj->enabled = $obj->enabled == 1 ? true : false;
        if ($object->user_id) $obj->user = $this->userStorage->getById($object->user_id);
        return $obj;
    }

    /**
     * @param NotificationContact $object
     * @return NotificationContact
     */
    public function add($object)
    {
        $object->setParams($this->prepareParams($object->getParams()));
        $object->user_id = $object->getUser()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param NotificationContact $object
     * @return NotificationContact
     */
    public function update($object)
    {
        $object->setParams($this->prepareParams($object->getParams()));
        $object->user_id = $object->getUser()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return NotificationContact
     */
    function getById($id)
    {
        $obj = $this->getObjectById(new NotificationContact(), $id);
        $obj->enabled = $obj->enabled == 1 ? true : false;
        $obj->user = $this->userStorage->getById($obj->user_id);
        return $obj;
    }

    function deleteByUser(User $user)
    {
        $psth = $this->pdo->prepare("DELETE FROM c_notifications_contacts WHERE user_id = ?");
        $psth->execute([$user->getId()]);
        return $psth->rowCount();
    }

    /**
     * @param User $user
     * @param $onlyEnabled
     * @return NotificationContact[]
     */
    function getByUser(User $user, $onlyEnabled = false)
    {
        $contacts = [];
        $query = "SELECT id FROM c_notifications_contacts WHERE user_id = ? ";
        if ($onlyEnabled) {
            $query .= " and enabled = 1 ";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$user->getId()]);
        foreach ($psth->fetchAll() as $f) {
            $contacts[] = $this->getById($f['id']);
        }
        return $contacts;
    }

    /**
     * @param $value
     * @param $type
     * @param $onlyEnabled
     * @return NotificationContact[]
     */
    function getByValue($value, $type = null, $onlyEnabled = false)
    {
        $contacts = [];
        $query = "SELECT id FROM c_notifications_contacts WHERE value = ? ";
        if ($type) {
            $query .= " and type = '$type' ";
        }
        if ($onlyEnabled) {
            $query .= " and enabled = 1";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$value]);
        foreach ($psth->fetchAll() as $f) {
            $contacts[] = $this->getById($f['id']);
        }
        return $contacts;
    }

    protected function prepareParams($params)
    {
        $parameters = [
            'severities' => null,
            'send_only_by_devices' => false,
            'ignore_notifications' => [],
        ];
        foreach ($parameters as $key => $_) {
            if (isset($params[$key])) {
                $parameters[$key] = $params[$key];
            }
        }
        return $params;
    }
}
