<?php

namespace WCC\Notifications\Storage;

use DI\Container;
use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCC\Notifications\Models\NotificationActionConfig;
use WCC\Notifications\Models\NotificationEventConfig;

class NotificationActionConfigStorage extends AbstractStorage
{

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    protected $tableName = 'c_notifications_actions_config';

    /**
     * @return NotificationActionConfig[]
     * @throws \Exception
     */
    function fetchAll()
    {
        $rules = [];
        foreach ($this->pdo->query("SELECT id FROM `{$this->tableName}` order by created_at, action_name ") as $id) {
            $rules[] = $this->fill(new NotificationActionConfig($id['id']));
        }
        return $rules;
    }

    /**
     * @param NotificationActionConfig $object
     * @return NotificationActionConfig
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object);
        $object->enabled = $object->enabled == 1 ? true : false;
        $object->send_on_status_failed = $object->send_on_status_failed == 1 ? true : false;
        $object->send_on_status_success = $object->send_on_status_success == 1 ? true : false;
        $object->ignored_devices = $this->getIgnoredDevicesByObject($object);
        return $object;
    }

    /**
     * @param NotificationActionConfig
     * @return NotificationActionConfig
     */
    function update($object)
    {
        $object->enabled = $object->enabled ? 1 : 0;
        $object->send_on_status_failed = $object->send_on_status_failed ? 1 : 0;
        $object->send_on_status_success = $object->send_on_status_success ? 1 : 0;
        $this->setDevicesByObject($object);
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param NotificationActionConfig[] $objects
     * @return NotificationActionConfig[]
     * @throws \Exception
     */
    function updateAll($objects)
    {
        //Request for fetching
        $newObjects = [];
        foreach ($objects as $obj) {
            if ($obj->getId()) {
                $newObjects[$obj->getId()] = $obj;
            }
        }
        $oldObjects = $this->fetchAll();
        $this->pdo->beginTransaction();
        //Remove old objects
        $psth = $this->pdo->prepare("DELETE FROM c_notifications_actions_config WHERE id = ?");
        foreach ($oldObjects as $obj) {
            if (!isset($newObjects[$obj->getId()])) {
                $psth->execute([$obj->getId()]);
            }
        }
        // Update/add objects
        foreach ($objects as $object) {
            if ($object->getId()) {
                $this->update($object);
            } else {
                $this->add($object);
            }
        }
        $this->pdo->commit();
        return $this->fetchAll();
    }

    /**
     * @param NotificationActionConfig $object
     * @return void
     */
    protected function setDevicesByObject(NotificationActionConfig $object)
    {
        $this->pdo
            ->prepare("DELETE FROM c_notifications_ignore_devices WHERE type = 'action' and notification_id = ?")
            ->execute([$object->getId()]);
        $psth = $this->pdo->prepare("INSERT IGNORE INTO 
                    c_notifications_ignore_devices (created_at, device_id, notification_id, type) 
                VALUES (NOW(), ?, ?, 'action')");
        if($object->getIgnoredDevices()) {
            foreach ($object->getIgnoredDevices() as $device) {
                $psth->execute([$device->getId(), $object->getId()]);
            }
        }
        return;
    }

    /**
     * @param NotificationActionConfig
     * @return NotificationActionConfig
     */
    function add($object)
    {
        $object->enabled = $object->enabled ? 1 : 0;
        $object->send_on_status_failed = $object->send_on_status_failed ? 1 : 0;
        $object->send_on_status_success = $object->send_on_status_success ? 1 : 0;
        $obj = parent::add($object); // TODO: Change the autogenerated stub
        $this->setDevicesByObject($obj);
        return $this->fill($obj);
    }

    /**
     * @param $name
     * @return NotificationActionConfig|null
     * @throws \Exception
     */
    function searchByName($name)
    {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE action_name = ?");
        $psth->execute([$name]);
        if ($psth->rowCount() == 0) {
            return null;
        }
        return $this->fill(new NotificationActionConfig($psth->fetchAll()[0]['id']));
    }

    /**
     * @param NotificationActionConfig $obj
     * @return Device[] | null
     */
    function getIgnoredDevicesByObject($obj) {
        if(!$this->_devices) {
            foreach ($this->deviceStorage->fetchAll() as $dev) {
                $this->_devices[$dev->getId()] = $dev;
            };
        }
        if(!$obj->getId()) {
            return  [];
        }
        $devices = [];
        $psth = $this->pdo->prepare("SELECT device_id FROM c_notifications_ignore_devices WHERE type = 'action' and notification_id = ?");
        $psth->execute([$obj->getId()]);
        foreach ($psth->fetchAll() as $d) {
            $devices[] = $this->_devices[$d['device_id']];
        }
        return  $devices;
    }
    protected $_devices = [];
}
