<?php

namespace WCC\Notifications\Storage;

use DI\Container;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\SystemActionsStorage;
use WCC\Notifications\Models\Notification;
use WCC\Notifications\Models\NotificationFilter;
use WCC\Events\Models\Event;
use WCC\Events\Storage\EventsStorage;

class NotificationsStorage extends AbstractStorage
{
    protected $tableName = 'c_notifications';


    function __construct(Container $ci)
    {
        $this->actionStorage = $ci->get(SystemActionsStorage::class);
        if (class_exists(EventsStorage::class)) {
            $this->eventsStorage = $ci->get(EventsStorage::class);
        }
        $this->contactsStorage = $ci->get(NotificationsContactsStorage::class);
    }

    /**
     * @var EventsStorage | null
     */
    protected $eventsStorage = null;

    /**
     * @var NotificationsContactsStorage
     */
    protected $contactsStorage;


    protected $actionStorage;


    /**
     * @param Notification $object
     * @return Notification
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        $obj->contact = $this->contactsStorage->getById($obj->contact_id);

        try {
            if ($obj->event_id && $this->eventsStorage) {
                $obj->event = $this->eventsStorage->getById($obj->event_id);
            }
        } catch (\Exception $e) {
            $this->logger->error("Event with id {$obj->event_id} not found in storage, but setted in notification with id={$object->getId()}");
        }
        try {
            if ($obj->action_id && $this->actionStorage) {
                $obj->action = $this->actionStorage->getById($obj->action_id);
            }
        } catch (\Exception $e) {
            $this->logger->error("Action with id {$obj->action_id} not found in storage, but setted in notification with id={$object->getId()}");
        }

        try {
            if ($obj->previous_notification_id) {
                $obj->previous_notification = $this->getById($obj->previous_notification_id);
            }
        } catch (\Exception $e) {
            $this->logger->error("Previous notification {$obj->previous_notification_id} not found in storage, but setted in notification with id={$object->getId()}");
        }
        return $obj;
    }

    /**
     * @param $id
     * @return Notification
     */
    public function getById($id)
    {
        return $this->getObjectById(new Notification(), $id);
    }

    /**
     * @param Notification $object
     * @param $fillArr
     * @return Notification
     */
    public function fillByArr($object, $fillArr = [])
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        if ($obj->event_id && $this->eventsStorage) {
            $obj->event = $this->eventsStorage->getById($obj->event_id);
        }
        if ($obj->action_id && $this->actionStorage) {
            $obj->action = $this->actionStorage->getById($obj->action_id);
        }
        $obj->contact = $this->contactsStorage->getById($obj->contact_id);
        if ($obj->previous_notification_id) {
            $obj->previous_notification = $this->getById($obj->previous_notification_id);
        }
        return $obj;
    }

    /**
     * @param Notification $object
     * @return Notification
     */
    public function add($object)
    {
        if ($object->getEvent()) {
            $object->event_id = $object->getEvent()->getId();
        }
        if ($object->getAction()) {
            $object->action_id = $object->getAction()->getId();
        }
        $object->contact_id = $object->getContact()->getId();
        if ($object->getPreviousnotification()) {
            $object->previous_notification_id = $object->getPreviousnotification()->getId();
        }
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param Notification $object
     * @return Notification
     */
    public function update($object)
    {
        if ($object->getEvent()) {
            $object->event_id = $object->getEvent()->getId();
        }

        if ($object->getAction()) {
            $object->action_id = $object->getAction()->getId();
        }
        if ($object->getPreviousnotification()) {
            $object->previous_notification_id = $object->getPreviousnotification()->getId();
        }
        $object->contact_id = $object->getContact()->getId();

        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param NotificationFilter $filter
     * @return Notification[]
     */

    public function getByEventFilter(NotificationFilter $filter, $limit = 200)
    {
        $where = ' 1=1 ';
        $params = [];
        if ($filter->getType()) {
            $where .= " and `type` = ?";
            $params[] = $filter->getType();
        }
        if ($filter->getAlertContact()) {
            $where .= " and contact_id = ?";
            $params[] = $filter->getAlertContact()->getId();
        }
        if ($filter->getUser()) {
            $where .= " and contact_id in (SELECT id FROM c_notifications_contacts WHERE user_id = ?)";
            $params[] = $filter->getUser()->getId();
        }
        if ($filter->getEvent()) {
            $where .= " and event_id = ?";
            $params[] = $filter->getEvent()->getId();
        }
        if ($filter->getAction()) {
            $where .= " and action_id = ?";
            $params[] = $filter->getAction()->getId();
        }
        if ($filter->getPreviousnotification()) {
            $where .= " and previous_notification_id = ?";
            $params[] = $filter->getPreviousnotification()->getId();
        }
        $psth = $this->pdo->prepare("SELECT id FROM c_notifications WHERE $where order by id desc LIMIT $limit");
        $psth->execute($params);
        $objects = [];
        foreach ($psth->fetchAll() as $elem) {
            $objects[] = $this->getById($elem['id']);
        }
        return $objects;
    }

    function getNotSendedNotifications()
    {
        $data = $this->pdo->query("
            SELECT id
FROM c_notifications
WHERE send_at <= NOW()
and status is null
and created_at > NOW() - INTERVAL 1 DAY order by id;
        ")->fetchAll();
        $notifications = [];
        foreach ($data as $d) {
            $notifications[] = $this->fill(new Notification($d['id']));
        }
        return $notifications;
    }
}
