<?php

namespace WCC\Pinger\Storage;

use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCC\Pinger\Models\DownLog;

class DownLogStorage extends AbstractStorage
{
    protected $tableName = 'c_pinger_down_logs';

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @param DownLog $object
     * @return DownLog
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj =  parent::fill($object); // TODO: Change the autogenerated stub
        $obj->device = $this->deviceStorage->getById($object->device_id);
        return $obj;
    }

    /**
     * @param DownLog $object
     * @param $fillArr
     * @return DownLog
     */
    public function fillByArr($object, $fillArr = [])
    {
        $obj =  parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        $obj->device = $this->deviceStorage->getById($object->device_id);
        return $obj;
    }

    /**
     * @param DownLog $object
     * @return DownLog
     */
    public function add($object)
    {
        $object->device_id = $object->device->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param DownLog $object
     * @return DownLog
     */
    public function update($object)
    {
        $object->device_id = $object->device->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }


    /**
     * @param Device $device
     * @return DownLog[]
     */
    public function getNoClosedLogsByDevice(Device $device) {
        $data = $this->pdo->prepare("SELECT * FROM c_pinger_down_logs WHERE device_id = ? and stop is null order by id desc ");
        $data->execute([$device->getId()]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->fillByArr(new DownLog(), $d);
        }
        return $response;
    }

    /**
     * @param Device $device
     * @return DownLog[]
     */
    public function getHistoryByDevice(Device $device)
    {
        $data = $this->pdo->prepare("SELECT * FROM c_pinger_down_logs WHERE device_id = ? order by id desc ");
        $data->execute([$device->getId()]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = (new DownLog())
            ->setDevice($device)
            ->setId($d['id'])
            ->setStart($d['start'])
            ->setStop($d['stop'])
            ;
        }
        return $response;
    }

}
