<?php

namespace WCC\Pinger\Storage;

use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCC\Pinger\Models\DownLog;
use WCC\Pinger\Models\PingerDeviceStatus;

class PingerDeviceStatusStorage extends AbstractStorage
{
    protected $tableName = 'c_pinger_statuses';

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @param PingerDeviceStatus $object
     * @return PingerDeviceStatus
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj =  parent::fill($object); // TODO: Change the autogenerated stub
        if($fillChildObjects) {
            $obj->device = $this->deviceStorage->getById($object->device_id);
        }
        return $obj;
    }
    /**
     * @param PingerDeviceStatus $object
     * @return PingerDeviceStatus
     * @throws \Exception
     */
    public function fillByArr($object, $fillArr = [], $fillDevice = true)
    {
        $obj =  parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        if($fillDevice) {
            $obj->device = $this->deviceStorage->getById($object->device_id);
        }
        return $obj;
    }

    /**
     * @param PingerDeviceStatus $object
     * @return PingerDeviceStatus
     */
    public function add($object)
    {
        $object->device_id = $object->device->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param PingerDeviceStatus $object
     * @return PingerDeviceStatus
     */
    public function update($object)
    {
        $object->device_id = $object->device->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return PingerDeviceStatus[]
     * @throws \Exception
     */
    public function getDownStatuses() {
        $response = [];
        foreach ($this->pdo->query("SELECT * FROM c_pinger_statuses WHERE latency < 0 order by last_change desc")->fetchAll() as $d) {
           $response[] = $this->fillByArr(new PingerDeviceStatus(), $d);
        }
        return $response;
    }

    /**
     * @param Device $d
     * @return PingerDeviceStatus
     * @throws \Exception
     */
    public function getDeviceStatus(Device $d) {
        $psth = $this->pdo->prepare("SELECT * FROM c_pinger_statuses WHERE device_id = ? LIMIT 1");
        $psth->execute([$d->getId()]);
        if($psth->rowCount() === 0) {
            return  null;
        }
        return $this->fillByArr(new PingerDeviceStatus(), $psth->fetch());
    }
    /**
     * @param string $ip
     * @return PingerDeviceStatus
     * @throws \Exception
     */
    public function getDeviceStatusByDeviceIP(string $ip) {
        $psth = $this->pdo->prepare("SELECT * FROM c_pinger_statuses WHERE device_id = (SELECT id FROM devices WHERE ip = ? LIMIT 1) LIMIT 1");

        $psth->execute([$ip]);
        if($psth->rowCount() === 0) {
            return  null;
        }
        return $this->fillByArr(new PingerDeviceStatus(), $psth->fetch());
    }

    /**
     * @return PingerDeviceStatus[]
     * @throws \Exception
     */
    public function getAllStatuses($fillDevice = true) {
        $response = [];
        foreach ($this->pdo->query("SELECT * FROM c_pinger_statuses")->fetchAll() as $d) {
            try {
                $response[] = $this->fillByArr(new PingerDeviceStatus(), $d, $fillDevice);
            } catch (\Exception $e) {}
        }
        return $response;
    }

    public function updateOnDuplicate($object)
    {
        return parent::updateOnDuplicate($object); // TODO: Change the autogenerated stub
    }
}
