<?php

namespace WCAA\Console\Poller\LastData;

use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use WCAA\App;
use WCAA\Console\AbstractCommand;
use WCAA\Infrastructure\Poller\PollerInterface;
use WCAA\Infrastructure\Poller\Pollers\CountersPoller;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;

abstract class LastDataAbstract extends AbstractCommand
{
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @var string
     */
    protected $pollerName;


    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    abstract protected function exec(InputInterface $input, OutputInterface $output, $data = []);

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $data = null;
        $device = $this->deviceStorage->getByIp($input->getArgument('device-ip'));
        if($ifaceName = $input->getArgument('interface')) {
            $interface = $this->deviceInterfaceStorage->getByDeviceAndName($device, $ifaceName);
            $data = App::getInstance()->getContainer()->get($this->pollerName)->getByInterface($interface);
        } else {
            $data = App::getInstance()->getContainer()->get($this->pollerName)->getByDevice($device);
        }
        return $this->exec($input, $output, $data);
    }

    protected function configure()
    {
        $this->addArgument("device-ip", InputArgument::REQUIRED, "Set device")
             ->addArgument("interface", InputArgument::OPTIONAL, "Set interface by name");
        parent::configure(); // TODO: Change the autogenerated stub
    }
}