<?php

namespace WCAA\Storage\System;

use WCAA\Models\System\Schedule;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\SystemComponentsStorage;

class ScheduleStorage extends AbstractStorage
{
    protected $tableName = 'system_schedule';

    /**
     * @Inject
     * @var SystemComponentsStorage
     */
    protected $componentStorage;

    /**
     * @param $object Schedule
     * @return Schedule
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        /**
         * @var $object Schedule
         */
        $object = parent::fill($object); // TODO: Change the autogenerated stub
        if($object->component_id) {
            $object->setComponent($this->componentStorage->getById($object->component_id));
        }
        if($object->getComponent() && !$object->getComponent()->isEnabled()) {
            $object->setState('DISABLED');
        }
        return $object;
    }

    /**
     * @param $object Schedule
     * @return Schedule
     */
    public function add($object)
    {
        if($object->getComponent()) {
            $object->component_id = $object->getComponent()->getId();
        }
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param Schedule
     * @return Schedule
     */
    public function update($object)
    {
        if($object->getComponent()) {
            $object->component_id = $object->getComponent()->getId();
        }
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return Schedule
     * @throws \Exception
     */
    public function getById($id) {
        return $this->fill(new Schedule($id));
    }

    /**
     * @param $key
     * @return Schedule
     * @throws \Exception
     */
    public function getByKey($key) {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE `key` = ?");
        $psth->execute([$key]);
        if($psth->rowCount() === 0) {
            throw new \InvalidArgumentException("Not found crontab job by key {$key}");
        }
        return $this->getById($psth->fetchAll()[0]['id']);
    }

    /**
     * @param bool $onlyEnabled
     * @return Schedule[]
     * @throws \Exception
     */
    public function fetchAll($onlyEnabled = true) {
        $responses = [];
        foreach ($this->pdo->query("SELECT id FROM `{$this->tableName}` order by 1")->fetchAll() as $d) {
           $d = $this->fill(new Schedule($d['id']));
           $responses[] = $d;
        }
        if($onlyEnabled) {
            $responses = array_filter($responses, function ($e) {
               /**
                * @var $e Schedule
                */
               return $e->getState() === 'ENABLED';
            });
        }
        return $responses;
    }
    /**
     * @param bool $onlyEnabled
     * @return Schedule[]
     * @throws \Exception
     */
    public function fetchCycle($onlyEnabled = true) {
        $responses = [];
        foreach ($this->pdo->query("SELECT id FROM `{$this->tableName}` WHERE crontab not like '@%' order by 1")->fetchAll() as $d) {
           $d = $this->fill(new Schedule($d['id']));
           $responses[] = $d;
        }
        if($onlyEnabled) {
            $responses = array_filter($responses, function ($e) {
               /**
                * @var $e Schedule
                */
               return $e->getState() === 'ENABLED';
            });
        }
        return $responses;
    }

    /**
     * @param bool $onlyEnabled
     * @return Schedule[]
     * @throws \Exception
     */
    public function fetchOnce($onlyEnabled = true) {
        $responses = [];
        foreach ($this->pdo->query("SELECT id FROM `{$this->tableName}`  WHERE crontab like '@%' order by 1")->fetchAll() as $d) {
           $d = $this->fill(new Schedule($d['id']));
           $responses[] = $d;
        }
        if($onlyEnabled) {
            $responses = array_filter($responses, function ($e) {
               /**
                * @var $e Schedule
                */
               return $e->getState() === 'ENABLED';
            });
        }
        return $responses;
    }
}
