<?php

namespace WCAA\Storage\System;

use WCAA\App;
use WCAA\Infrastructure\Events\EventObserverStorage;
use WCAA\Models\System\Schedule;
use WCAA\Models\System\ScheduleReport;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\SystemComponentsStorage;

class ScheduleReportsStorage extends AbstractStorage
{
    protected $tableName = 'system_schedule_reports';

    /**
     * @Inject
     * @var ScheduleStorage
     */
    protected $scheduleStorage;

    /**
     * @param $object ScheduleReport
     * @return ScheduleReport
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        /**
         * @var $object ScheduleReport
         */
        $object = parent::fill($object); // TODO: Change the autogenerated stub
        $object->setIsSuccessful($object->is_successful == 1);
        if($object->schedule_id) {
            $object->setSchedule($this->scheduleStorage->getById($object->schedule_id));
        }
        return $object;
    }

    /**
     * @param $object ScheduleReport
     * @return ScheduleReport
     */
    public function add($object)
    {
        $object->schedule_id = $object->getSchedule()->getId();
        $obj = parent::add($object); // TODO: Change the autogenerated stub
        App::getInstance()->getContainer()->get(EventObserverStorage::class)->notify("schedule:started", $obj);
        return  $obj;
    }

    /**
     * @param $object ScheduleReport
     * @return ScheduleReport
     */
    public function update($object)
    {
        $object->schedule_id = $object->getSchedule()->getId();
        $obj = parent::update($object);
        App::getInstance()->getContainer()->get(EventObserverStorage::class)->notify("schedule:updated", $obj);
        return $obj; // TODO: Change the autogenerated stub
    }

    /**
     * @param $start
     * @param $stop
     * @param string[] $scheduleKeys
     * @param bool $hideFinished
     * @param bool $only_failed
     * @return ScheduleReport[]
     * @throws \Exception
     */
    function getReportsByFilter($start, $stop, $scheduleKeys = [], $hideFinished = false, $only_failed = false)
    {
        $query = "SELECT id, start_at, stop_at, `output`, `error`, is_successful, schedule_id 
            FROM system_schedule_reports
            WHERE start_at BETWEEN ? AND ? 
            ";
        if ($scheduleKeys) {
            $ids = [-1];
            foreach ($scheduleKeys as $scheduleKey) {
                $ids[] = $this->scheduleStorage->getByKey($scheduleKey)->getId();
            }
            $query .= " and schedule_id in (".join(',', $ids).")";
        }
        if ($hideFinished) {
            $query .= " and stop_at is null";
        }
        if ($only_failed) {
            $query .= " and `is_successful` = 0";
        }

        $query .= " ORDER BY 1 desc limit ?";

        $psth = $this->pdo->prepare($query);
        $psth->execute([$start, $stop, $this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];

        foreach ($psth->fetchAll() as $d) {
            $r = $this->fillByArr(new ScheduleReport(), $d);
            $r->setSchedule($this->scheduleStorage->getById($d['schedule_id']));
            $r->setIsSuccessful($d['is_successful'] == 1);
            $resp[] = $r;
        }
        return $resp;
    }
}
