<?php


namespace WCAA\Storage\Devices;


use WCAA\Infrastructure\Security\Encryption;
use WCAA\Models\Devices\DeviceAccess;
use WCAA\Storage\AbstractStorage;

/**
 * Class DeviceAccessStorage
 * @package WCAA\Storage\Devices
 */
class DeviceAccessStorage extends AbstractStorage
{

    /**
     * @Inject
     * @var Encryption
     */
    protected $encryptor;

    protected $tableName = 'device_accesses';
    /**
     * @return DeviceAccess[]
     */
    function fetchAll() {
        return $this->fillAllFromIds(function ($id) {
            return new DeviceAccess($id);
        });
    }

    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object, $fillChildObjects); // TODO: Change the autogenerated stub
        $this->decrypt($obj);
        return $obj;
    }


    /**
     * @param $id
     * @return DeviceAccess
     */
    function getById($id) {
        /**
         * @var DeviceAccess $object
         */
        $object =  $this->getObjectById(DeviceAccess::class, $id);
        return $object;
    }


    /**
     * @param DeviceAccess $object
     * @return mixed
     */
    function update($object)
    {
        $this->encrypt($object);
        $this->observerStorage->notify("device-access:updated", $object);
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    function add($object)
    {
        $this->encrypt($object);
        $this->observerStorage->notify("device-access:added", $object);
        return parent::add($object);
    }

    private function encrypt(&$object) {
        if($this->encryptor->isEncryptEnabled()) {
            $object->login = $object->login !== null ? $this->encryptor->encryptValue($object->login) : null;
            $object->password = $object->password !== null ? $this->encryptor->encryptValue($object->password) : null;
            $object->public_community = $object->public_community !== null ? $this->encryptor->encryptValue($object->public_community) : null;
            $object->private_community = $object->private_community !== null ? $this->encryptor->encryptValue($object->private_community) : null;
        }
    }
    private function decrypt(&$object) {
        if($this->encryptor->isEncryptEnabled()) {
            $object->login = $object->login !== null ? $this->encryptor->decryptValue($object->login) : null;
            $object->password = $object->password !== null ? $this->encryptor->decryptValue($object->password) : null;
            $object->public_community = $object->public_community !== null ? $this->encryptor->decryptValue($object->public_community) : null;
            $object->private_community = $object->private_community !== null ? $this->encryptor->decryptValue($object->private_community) : null;
        }
    }

}
