<?php


namespace WCAA\Storage\Devices;


use DI\Annotation\Inject;
use Exception;
use WCAA\App;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Models\Devices\DeviceInterfaceHistory;
use WCAA\Models\Pollers\FdbHistory;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

/**
 * Class DeviceInterfaceStorage
 * @package WCAA\Storage\Devices
 */
class DeviceInterfaceStorage extends AbstractStorage
{

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    protected $tableName = 'device_interfaces';

    /**
     * @param DeviceInterface $object
     * @return DeviceInterface
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object, $fillChildObjects); // TODO: Change the autogenerated stub
        if ($fillChildObjects) $fill->device = $this->deviceStorage->getById($fill->device_id);
        $fill->poll_enabled = $object->poll_enabled == 1;
        return $fill;
    }

    protected function fillByArr($object, $fetchArr = [])
    {
        $filled = parent::fillByArr($object, $fetchArr);
        if (isset($fetchArr['poll_enabled']) && is_numeric($fetchArr['poll_enabled'])) {
            $filled->setPollEnabled($fetchArr['poll_enabled'] == 1);
        }
        return $filled;
    }


    /**
     * @param DeviceInterface $object
     * @return DeviceInterface
     */
    public function add($object)
    {
        $object->poll_enabled = $object->poll_enabled ? 1 : 0;
        $object->device_id = $object->getDevice()->getId();

        /**
         * @var $added DeviceInterface
         */
        $added = parent::add($object); // TODO: Change the autogenerated stub

        if (in_array($added->getStatus(), ['Up', 'Online'])) {
            App::getInstance()->getContainer()->get(DeviceInterfaceHistoryStorage::class)->add(
                (new DeviceInterfaceHistory())->setInterface($added)
            );
        }

        return $added;
    }

    /**
     * @param DeviceInterface $object
     * @return DeviceInterface
     */
    public function update($object, $updateHistory = true)
    {
        $object->device_id = $object->getDevice()->getId();
        $object->poll_enabled = $object->poll_enabled ? 1 : 0;

        $lastState = $this->getById($object->getId());
        if ($lastState->getStatus() != $object->getStatus()) {
            $object->setStatusChanged(date("Y-m-d H:i:s"));

            if($updateHistory) {
                if (in_array($object->getStatus(), ['Up', 'Online'])) {
                    App::getInstance()->getContainer()->get(DeviceInterfaceHistoryStorage::class)->add(
                        (new DeviceInterfaceHistory())->setInterface($object)
                    );
                } else {
                    $actives = App::getInstance()->getContainer()->get(DeviceInterfaceHistoryStorage::class)->getLastActive($object, false);
                    foreach ($actives as $active) {
                        App::getInstance()->getContainer()->get(DeviceInterfaceHistoryStorage::class)->update($active->setDown(date("Y-m-d H:i:s"))->setDownReason($object->getStatus()));
                    }
                }
            }
        }

        return parent::update($object); // TODO: Change the autogenerated stub
    }


    /**
     * @return DeviceInterface[]
     */
    function fetchAll($fillChildren = true)
    {
        $devices = [];
        $resp = [];
        $psth = $this->pdo->prepare("SELECT * FROM {$this->tableName}");
        $psth->execute();
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $elem) {
            /**
             * @var $iface DeviceInterface
             */
            $iface = $this->fillByArr(new DeviceInterface(), $elem);
            if($fillChildren) {
                if(!isset($devices[$iface->getDeviceId()])) {
                    $devices[$iface->getDeviceId()] = $this->deviceStorage->getById($iface->getDeviceId());
                }
                $iface->setDevice($devices[$iface->getDeviceId()]);
            }
            $resp[] = $iface;
        }
        return $resp;
    }
    /**
     * @return DeviceInterface[]
     */
    function fetchAllForTopology($fillChildren = true)
    {
        $devices = [];
        $resp = [];
        $psth = $this->pdo->prepare("SELECT * FROM {$this->tableName} WHERE id in (SELECT distinct src_iface_id FROM c_links WHERE src_iface_id is not null UNION  SELECT distinct dest_iface_id FROM c_links WHERE dest_iface_id is not null)");
        $psth->execute();
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $elem) {
            /**
             * @var $iface DeviceInterface
             */
            $iface = $this->fillByArr(new DeviceInterface(), $elem);
            if($fillChildren) {
                if(!isset($devices[$iface->getDeviceId()])) {
                    $devices[$iface->getDeviceId()] = $this->deviceStorage->getById($iface->getDeviceId());
                }
                $iface->setDevice($devices[$iface->getDeviceId()]);
            }
            $resp[] = $iface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return DeviceInterface
     */
    function getById($id)
    {
        return $this->getObjectById(DeviceInterface::class, $id);
    }

    /**
     * @param Device $device
     * @return DeviceInterface[]
     */
    function getByDevice(Device $device, $interfaceType = null, $fillDevice = true)
    {
        if ($interfaceType) {
            $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE device_id = ? and type = ? order by CAST(bind_key AS UNSIGNED)");
            $psth->execute([$device->getId(), $interfaceType]);
        } else {
            $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE device_id = ? order by CAST(bind_key AS UNSIGNED)");
            $psth->execute([$device->getId()]);
        }
        return array_map(function ($e) use ($fillDevice, $device) {
            $interface = $this->fillByArr(new DeviceInterface($e['id']), $e);
            if ($fillDevice) {
                $interface->setDevice($device);
            }
            return $interface;
        }, $psth->fetchAll());
    }

    /**
     * Fetch interfaces for many devices in a single query, grouped by device id.
     *
     * @param Device[] $devices
     * @return DeviceInterface[][] keyed by device id
     */
    function getByDevicesGrouped(array $devices, $interfaceType = null, $fillDevice = true)
    {
        $devicesById = [];
        foreach ($devices as $device) {
            $devicesById[$device->getId()] = $device;
        }
        if (!$devicesById) {
            return [];
        }
        $ids = array_keys($devicesById);
        $placeholders = implode(',', array_fill(0, count($ids), '?'));
        if ($interfaceType) {
            $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE device_id IN ($placeholders) and type = ? order by device_id, CAST(bind_key AS UNSIGNED)");
            $psth->execute(array_merge($ids, [$interfaceType]));
        } else {
            $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE device_id IN ($placeholders) order by device_id, CAST(bind_key AS UNSIGNED)");
            $psth->execute($ids);
        }
        $grouped = [];
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $e) {
            $interface = $this->fillByArr(new DeviceInterface($e['id']), $e);
            if ($fillDevice && isset($devicesById[$interface->getDeviceId()])) {
                $interface->setDevice($devicesById[$interface->getDeviceId()]);
            }
            $grouped[$interface->getDeviceId()][] = $interface;
        }
        return $grouped;
    }
    /**
     * Returns "deviceId-bindKey" strings for interfaces matching a type.
     *
     * Replaces the previous getBindKeysByWhere(), which interpolated a caller-supplied
     * SQL fragment straight into the statement.
     *
     * @param string $interfaceType
     * @return string[]
     */
    function getBindKeysByType($interfaceType)
    {
        $psth = $this->pdo->prepare("SELECT device_id, bind_key FROM device_interfaces WHERE `type` = ?");
        $psth->execute([$interfaceType]);
        return array_map(function ($e) {
            return "{$e['device_id']}-{$e['bind_key']}";
        }, $psth->fetchAll(\PDO::FETCH_ASSOC));
    }

    function deleteByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("DELETE FROM device_interfaces WHERE device_id = ?");
        $psth->execute([$device->getId()]);
        $this->clearByObject(new DeviceInterface());
        $this->_ids = null;
        return $this;
    }


    /**
     * @param Device $device
     * @param $key
     * @return DeviceInterface
     * @throws RecordNotFoundException
     */
    function getByDeviceAndKey(Device $device, $key)
    {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE device_id = ? and bind_key = ? order by id desc ");
        $psth->execute([$device->getId(), $key]);
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new DeviceInterface($e['id']), false);
            $interface->setDevice($device);
            return $interface;
        }
        throw new RecordNotFoundException("Interface not found by device_id={$device->getId()}, bind_key={$key}");
    }


    /**
     * @param Device $device
     * @param $key
     * @return DeviceInterface
     * @throws RecordNotFoundException
     */
    function getByDeviceAndName(Device $device, $name)
    {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE device_id = ? and name = ? order by id desc ");
        $psth->execute([$device->getId(), $name]);
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new DeviceInterface($e['id']), false);
            $interface->setDevice($device);
            return $interface;
        }
        throw new RecordNotFoundException("Interface not found by device_id={$device->getId()}, bind_key={$name}");
    }

    /**
     * @return array[]
     */
    function findNearestByCoordinates(float $lat, float $lon, float $distanceMeters, array $deviceGroupIds, int $limit = 100, string $type = DeviceInterface::TYPE_ONU)
    {
        $deviceGroupIds = array_values(array_filter($deviceGroupIds, 'is_numeric'));
        if (!$deviceGroupIds) {
            return [];
        }
        $limit = max(1, $limit);

        $placeholders = trim(str_repeat('?,', count($deviceGroupIds)), ',');
        $distanceSql = "(6371000 * 2 * ASIN(SQRT(
            POWER(SIN((RADIANS(coords.lat) - RADIANS(?)) / 2), 2) +
            COS(RADIANS(?)) * COS(RADIANS(coords.lat)) *
            POWER(SIN((RADIANS(coords.lon) - RADIANS(?)) / 2), 2)
        )))";
        $query = "
            SELECT coords.*, {$distanceSql} distance_m
            FROM (
                SELECT
                    i.id,
                    JSON_UNQUOTE(JSON_EXTRACT(i.coordinates, '$.lat')) + 0 lat,
                    JSON_UNQUOTE(JSON_EXTRACT(i.coordinates, '$.lon')) + 0 lon
                FROM device_interfaces i
                JOIN devices d ON d.id = i.device_id
                WHERE d.enabled = 1
                    AND i.coordinates IS NOT NULL
                    AND JSON_EXTRACT(i.coordinates, '$.lat') IS NOT NULL
                    AND JSON_EXTRACT(i.coordinates, '$.lon') IS NOT NULL
                    AND i.type = ?
                    AND d.group_id IN ({$placeholders})
            ) coords
            HAVING distance_m <= ?
            ORDER BY distance_m
            LIMIT {$limit}
        ";

        $params = array_merge([$lat, $lat, $lon, $type], $deviceGroupIds, [$distanceMeters]);
        $psth = $this->pdo->prepare($query);
        $psth->execute($params);

        return array_map(function ($row) {
            return [
                'type' => 'interface',
                'id' => (int)$row['id'],
                'distance_m' => round((float)$row['distance_m'], 2),
            ];
        }, $psth->fetchAll(\PDO::FETCH_ASSOC));
    }

    /**
     * @param $paramsKey
     * @param $value
     * @return array
     * @throws Exception
     */
    function searchByParams($paramsKey, $value)
    {
        $this->logger->error("SELECT id FROM `{$this->tableName}` WHERE JSON_EXTRACT(params, '$.{$paramsKey}') + 0 = ?");
        $this->logger->error($value);
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE JSON_EXTRACT(params, '$.{$paramsKey}') + 0 = ?");
        $psth->execute([$value]);
        $response = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new DeviceInterface($e['id']), true);
            $response[] = $interface;
        }
        $this->logger->error(json_encode($response));
        return  $response;
    }


    /**
     * @param $searchLine
     * @param int $limit
     * @return DeviceInterface[]
     */
    function searchBy($searchLine, $by = 'description', $limit = 10)
    {
        switch ($by) {
            case 'description':
                $data = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE `description` like ? order by  id desc limit ?");
                break;
            case 'name':
                $data = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE `name` like ? order by  id desc limit ?");
                break;
            case 'agreement':
                $data = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE `agreement` like ? order by  id desc limit ?");
                break;
        }
        $data->execute(["%{$searchLine}%", $limit]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->getById($d['id']);
        }
        return $response;
    }

    function getDeviceStat(Device $device)
    {
        $psth = $this->pdo->prepare("
        SELECT if(di.type = 'ONU', 'ONU', 'PHYSICAL') type,
           count(if(`status` in ('Up', 'Online'), 1, null)) up,
           count(if(`status` not in ('Up', 'Online'), 1, null)) down
        FROM device_interfaces di
        WHERE di.device_id = ?
        GROUP BY if(di.type = 'ONU', 'ONU', 'PHYSICAL')
        ORDER BY  1");
        $psth->execute([$device->getId()]);
        if ($psth->rowCount() == 0) {
            throw new \Exception("Stat by device {$device->getId()} not found");
        }
        $fetched = $psth->fetchAll();
        if (count($fetched) == 0) {
            return null;
        }
        $resp = [
            'up' => 0,
            'down' => 0,
            'last_stat' => null,
        ];
        foreach ($fetched as $dt) {
            if (!isset($dt['up'])) $resp['up'] = 0;
            if (!isset($dt['down'])) $resp['down'] = 0;
            $resp['up'] += $dt['up'];
            $resp['down'] += $dt['down'];
            $resp['splitted'][$dt['type']] = [
                'type' => $dt['type'],
                'up' => $dt['up'],
                'down' => $dt['down'],
            ];
        }
        $psth = $this->pdo->prepare("SELECT device_id, 
            max(stop_at) stop_at  
            FROM poller_processing 
            WHERE poller = 'interfaces_status'  
            and device_id = ? 
            GROUP BY device_id
            ");
        $psth->execute([$device->getId()]);
        if ($psth->rowCount()) {
            $resp['last_stat'] = $psth->fetchAll()[0]['stop_at'];
        }
        return $resp;
    }

    function getIfacesStatByType()
    {
        $psth = $this->pdo->prepare("
        SELECT di.type type,
           count(if(`status` in ('Up', 'Online'), 1, null)) up,
           count(if(`status` not in ('Up', 'Online'), 1, null)) down,
       count(if(status is null, 1, null)) unknown
        FROM device_interfaces di
        JOIN devices d ON d.id = di.device_id
        WHERE d.enabled = 1
        GROUP BY di.type
        ORDER BY  1");
        $psth->execute([]);
        $fetched = $psth->fetchAll();
        if (count($fetched) == 0) {
            return [
                'up' => 0,
                'down' => 0,
                'unknown' => 0,
                'last_stat' => null,
                'types' => [],
            ];
        }
        $resp = [
            'up' => 0,
            'down' => 0,
            'unknown' => 0,
            'last_stat' => null,
        ];
        foreach ($fetched as $dt) {
            if (!isset($dt['up'])) $resp['up'] = 0;
            if (!isset($dt['down'])) $resp['down'] = 0;
            if (!isset($dt['unknown'])) $resp['unknown'] = 0;
            $resp['up'] += $dt['up'];
            $resp['down'] += $dt['down'];
            $resp['unknown'] += $dt['unknown'];
            $resp['types'][$dt['type']] = [
                'type' => $dt['type'],
                'up' => $dt['up'],
                'down' => $dt['down'],
                'unknown' => $dt['unknown'],
            ];
        }
        return $resp;
    }

    function getStatByDeviceId()
    {
        if ($stat = $this->cache->get("STORAGE:interfaces_stat_by_dev_id")) {
            return $stat;
        }
        $psth = $this->pdo->prepare("
           SELECT di.device_id,
               if(di.type = 'ONU', 'ONU', 'PHYSICAL') type,
           count(if(`status` in ('Up', 'Online'), 1, null)) up,
           count(if(`status` not in ('Up', 'Online'), 1, null)) down
            FROM device_interfaces di
            GROUP BY di.device_id, if(di.type = 'ONU', 'ONU', 'PHYSICAL')
            ORDER BY 1;
        ");
        $psth->execute();
        $response = [];
        foreach ($psth->fetchAll() as $raw) {
            $response[$raw['device_id']]['splitted'][$raw['type']] = [
                'device_id' => $raw['device_id'],
                'type' => $raw['type'],
                'up' => (int)$raw['up'],
                'down' => (int)$raw['down'],
            ];

            if (!isset($response[$raw['device_id']]['up'])) $response[$raw['device_id']]['up'] = 0;
            if (!isset($response[$raw['device_id']]['down'])) $response[$raw['device_id']]['down'] = 0;

            $response[$raw['device_id']]['device_id'] = $raw['device_id'];
            $response[$raw['device_id']]['up'] += $raw['up'];
            $response[$raw['device_id']]['down'] += $raw['down'];

        }
        $psth = $this->pdo->prepare("SELECT device_id, max(stop_at) stop_at  FROM poller_processing WHERE poller = 'interfaces_status' GROUP BY device_id");
        $psth->execute([]);
        foreach ($psth->fetchAll() as $dt) {
            $response[$dt['device_id']]['last_stat'] = $dt['stop_at'];
        };
        $this->cache->set("STORAGE:interfaces_stat_by_dev_id", $response, 60);
        return $response;
    }

    function getOntStatuses($deviceGroupIds = [])
    {
        if ($deviceGroupIds) {
            $psth = $this->pdo->prepare("SELECT if(status = 'PowerOff', 'Offline', status) status, count(*) count
            FROM device_interfaces  i 
            JOIN devices d on d.id = i.device_id
            WHERE type = 'ONU' and `status` is not null 
            GROUP BY  if(status = 'PowerOff', 'Offline', status) order by  1");
            $psth->execute();
        } else {
            $deviceGroupIds = array_filter($deviceGroupIds, function ($n) {
                return is_numeric($n);
            });
            if(!$deviceGroupIds) {
                return [];
            }
            $ids = join(",", $deviceGroupIds);
            $psth = $this->pdo->prepare("SELECT if(status = 'PowerOff', 'Offline', status), count(*) count
            FROM device_interfaces  i 
            JOIN devices d on d.id = i.device_id
            WHERE type = 'ONU' and `status` is not null 
            and d.group_id in ($ids)
            GROUP BY  if(status = 'PowerOff', 'Offline', status) order by  1");
            $psth->execute();
        }
        return $psth->fetchAll();
    }

    /**
     * counts the number of enabled interfaces
     */
    public function countEnableInterfaces(): int
    {
        $sql = "
    SELECT count(di.id) с
    FROM `{$this->tableName}` di 
    JOIN `{$this->deviceStorage->getTableName()}` d ON d.id = di.device_id
    WHERE d.enabled = 1
";
        $stmt = $this->pdo->prepare($sql);
        $stmt->execute();
        return $stmt->fetchColumn();

    }

}
