<?php


namespace WCAA\Storage\Devices;


use DI\Annotation\Inject;
use Exception;
use WCAA\Exceptions\SupportException;
use WCAA\Infrastructure\SystemInfo;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Models\Devices\DeviceInterfaceHistory;
use WCAA\Storage\AbstractStorage;

/**
 * Class DeviceInterfaceHistoryStorage
 * @package WCAA\Storage\Devices
 */
class DeviceInterfaceHistoryStorage extends AbstractStorage
{


    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    protected $tableName = 'device_interfaces_history';

    /**
     * @param DeviceInterfaceHistory $object
     * @return DeviceInterfaceHistory
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object, $fillChildObjects); // TODO: Change the autogenerated stub
        if($fillChildObjects) $fill->interface = $this->deviceInterfaceStorage->getById($fill->interface_id);
        return $fill;
    }

    protected function fillByArr($object, $fetchArr = []) {
        $filled = parent::fillByArr($object, $fetchArr);
        $filled->interface = $this->deviceInterfaceStorage->getById($filled->interface_id);
        return $filled;
    }


    /**
     * @param DeviceInterfaceHistory $object
     * @return DeviceInterfaceHistory
     */
    public function add($object)
    {
        $object->interface_id = $object->getInterface()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param DeviceInterfaceHistory $object
     * @return DeviceInterfaceHistory
     */
    public function update($object)
    {
        $object->interface_id = $object->getInterface()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }


    /**
     * @return DeviceInterfaceHistory[]
     */
    function fetchAll($fillChildren = true)
    {
        $resp = [];
        foreach ($this->fetchAllIds(null) as $e) {
            $interface = $this->fill(new DeviceInterfaceHistory($e), $fillChildren);
            $resp[] = $interface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return DeviceInterface
     */
    function getById($id)
    {
        return $this->getObjectById(DeviceInterfaceHistory::class, $id);
    }

    /**
     * @param DeviceInterface $device
     * @return DeviceInterfaceHistory[]
     */
    function getByInterface(DeviceInterface $device, $fillChildren = false, $limit = 100)
    {
        $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE interface_id = ? order by id desc LIMIT ?");
        $psth->execute([$device->getId(), $limit]);
        return array_map(function ($e) use ($fillChildren, $device) {
            $interface = $this->fillByArr(new DeviceInterfaceHistory($e['id']), $e);
            if($fillChildren) {
                $interface->setInterface($device);
            }
            return $interface;
        }, $psth->fetchAll());
    }

    /**
     * @param DeviceInterface $iface
     * @return DeviceInterfaceHistory[]
     */
    function getLastActive(DeviceInterface $iface, $fillChildren = false)
    {
        $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE interface_id = ? and down is null order by id desc");
        $psth->execute([$iface->getId()]);
        return array_map(function ($e) use ($fillChildren, $iface) {
            $interface = $this->fillByArr(new DeviceInterfaceHistory($e['id']), $e);
            if($fillChildren) {
                $interface->setInterface($iface);
            }
            return $interface;
        }, $psth->fetchAll());
    }

    function deleteByInterface(DeviceInterface $device) {
        $psth = $this->pdo->prepare("DELETE FROM device_interfaces_history WHERE interface_id = ?");
        $psth->execute([$device->getId()]);
        $this->clearByObject(new DeviceInterfaceHistory());
        $this->_ids = null;
        return $this;
    }

    function getHistoryByDeviceAsLog(Device $device)
    {
        $psth = $this->pdo->prepare("
            SELECT *
            FROM (
                     SELECT
                         interface_id,
                         up AS time,
                         'up' AS status,
                         '' reason,
                         TIMESTAMPDIFF(SECOND, up, NOW()) AS seconds_from_time
                     FROM
                         support.device_interfaces_history
                     WHERE
                         interface_id  in (SELECT id FROM device_interfaces WHERE device_id = ?)
                     UNION ALL
                     SELECT
                         interface_id,
                         down AS time,
                         'down' AS status,
                         down_reason,
                         TIMESTAMPDIFF(SECOND, down, NOW()) AS seconds_from_time
                     FROM
                         support.device_interfaces_history
                     WHERE
                         interface_id in (SELECT id FROM device_interfaces WHERE device_id = ?) and
                         down IS NOT NULL
                 ) AS combined
            ORDER BY
                time DESC
            LIMIT 1000
            ;");
        $psth->execute([$device->getId(), $device->getId()]);

        $interfaces = [];
        foreach ($this->deviceInterfaceStorage->getByDevice($device, null, false) as $iface) {
            $interfaces[$iface->getId()] = $iface;
        };

        return array_map(function ($el) use ($device, $interfaces) {
            $el['interface'] = $interfaces[$el['interface_id']]->getAsArrayLite();
            return $el;
        }, $psth->fetchAll());
    }
}
