<?php

namespace WCAA\Storage\Devices;

use WCAA\Models\Devices\DeviceGroup;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

class DeviceGroupStorage extends AbstractStorage
{
    protected $tableName = 'device_groups';


    /**
     * @param $id
     * @return DeviceGroup
     */
    function getById($id)
    {
        return parent::getObjectById(new DeviceGroup(), $id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $name
     * @return DeviceGroup
     */
    function getByName($name) {
        $psth = $this->pdo->prepare("SELECT id FROM device_groups WHERE name = ? ");
        $psth->execute([$name]);
        if($psth->rowCount() === 0) {
            throw new RecordNotFoundException("Device group with name='$name' not found in storage");
        }
        return $this->getById($psth->fetchAll()[0]['id']);
    }

    /**
     * @return DeviceGroup[]
     * @throws \Exception
     */
    function fetchAll() {
        //Runs inside getSysUser() on the auth path, so one stale id here would
        //otherwise 500 every request in the panel.
        return $this->fillAllFromIds(function ($id) {
            return new DeviceGroup($id);
        });
    }

    function update($object)
    {
        return parent::update($object); // TODO: Change the autogenerated stub
    }
}
