<?php


namespace WCAA\Storage\Devices;


use DI\Annotation\Inject;
use Exception;
use WCAA\Infrastructure\Paginator\DbPagination;
use WCAA\Infrastructure\PrometheusMetrics;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceAccess;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Models\Devices\DeviceModel;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

/**
 * @method Device fillByArr($object, $fetchArr = [])
 * Class DeviceStorage
 * @package WCAA\Storage\Devices
 */
class DeviceStorage extends AbstractStorage
{

    /**
     * @Inject
     * @var DeviceGroupStorage
     */
    protected $deviceGroupStorage;

    /**
     * @Inject
     * @var PrometheusMetrics
     */
    protected $promExporter;

    /**
     * @Inject
     * @var DeviceAccessStorage
     */
    protected $accessStorage;

    /**
     * @Inject
     * @var DeviceModelStorage
     */
    protected $modelStorage;

    protected $tableName = 'devices';

    /**
     * @param Device $object
     * @return Device
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        if($fillChildObjects) {
            $fill->model = $this->modelStorage->fill((new DeviceModel($fill->model_id)));
            $fill->access = $this->accessStorage->fill((new DeviceAccess($fill->access_id)));
            $fill->group = $this->deviceGroupStorage->fill((new DeviceGroup($fill->group_id)));
        }
        $fill->enabled = $fill->enabled  ? true : false;
        return $fill;
    }

    public function getUniqDeviceMacAddresses($withCache = true)
    {
        if($withCache) {
            $addresses = $this->cache->get('STORAGE:UNIQ_DEVICE_MAC_ADDRESSES');
            if($addresses !== null) {
                return $addresses;
            }
        }
        $psth = $this->pdo->prepare("SELECT DISTINCT mac FROM devices WHERE mac != ''");
        $psth->execute();
        $macAddresses = [];
        foreach ($psth->fetchAll() as $mac) {
            $macAddresses[$mac['mac']] = $mac['mac'];
        }
        if($withCache) {
            $this->cache->set("STORAGE:UNIQ_DEVICE_MAC_ADDRESSES", $macAddresses, 300);
        }
        return $macAddresses;
    }

    /**
     * @param Device $object
     * @return Device
     */
    public function add($object)
    {
        $object->access_id = $object->getAccess()->getId();
        $object->model_id = $object->getModel()->getId();
        $object->group_id = $object->getGroup()->getId();
        $object->enabled = $object->enabled  ? 1 : 0;
        $this->observerStorage->notify("device:added", $object);
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    public function delete($object)
    {
        $this->promExporter->clearByDevice($object);
        $this->observerStorage->notify("device:deleted", $object);
        return parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param Device $object
     * @return Device
     */
    public function update($object)
    {
        $object->updated_at = date("Y-m-d H:i:s");
        $object->access_id = $object->getAccess()->getId();
        $object->model_id = $object->getModel()->getId();
        $object->group_id = $object->getGroup()->getId();
        $object->enabled = $object->enabled  ? 1 : 0;
        $oldObj = $this->getById($object->getId());
        if($oldObj->getIp() != $object->getIp()) {
            $this->promExporter->clearByDevice($object);
        }
        $this->observerStorage->notify("device:updated", $object);
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return Device[]
     */
    function fetchAll() {
        $resp = [];
        $models = [];
        $accesses = [];
        $groups = [];

        foreach ($this->fetchAllIds(null, " id desc") as $e) {
            $device = $this->fill(new Device($e), false);

            if(isset($accesses[$device->access_id])) {
                $access = $accesses[$device->access_id];
            } else {
                $access = $this->accessStorage->fill((new DeviceAccess())->setId($device->access_id));
                $accesses[$device->access_id] = $access;
            }
            if(isset($models[$device->model_id])) {
                $model = $models[$device->model_id];
            } else {
                $model = $this->modelStorage->fill((new DeviceModel())->setId($device->model_id));
                $models[$device->model_id] = $model;
            }
            if(isset($groups[$device->group_id])) {
                $group = $groups[$device->group_id];
            } else {
                $group = $this->deviceGroupStorage->fill((new DeviceGroup($device->group_id)));
                $groups[$device->group_id] = $group;
            }


            $device->setAccess($access);
            $device->setModel($model);
            $device->setGroup($group);
            $resp[] = $device;
        }
        return $resp;
    }
    /**
     * @return Device[]
     */
    function fetchByModelType($modelType) {
        $resp = [];
        $psth = $this->pdo->prepare("SELECT id FROM devices WHERE model_id in (SELECT id FROM device_models WHERE type = ?)");
        $psth->execute([$modelType]);
        foreach ($psth->fetchAll() as $e) {
            $device = $this->fill(new Device($e['id']));
            $device->setAccess($this->accessStorage->fill((new DeviceAccess())->setId($device->access_id)));
            $device->setModel($this->modelStorage->fill((new DeviceModel())->setId($device->model_id)));
            $device->setGroup($this->deviceGroupStorage->fill((new DeviceGroup($device->group_id))));
            $resp[] = $device;
        }
        return $resp;
    }

    /**
     * @return Device[]
     */
    function fetchByDeviceGroup(DeviceGroup $deviceGroup, $lite = false) {
        $resp = [];
        $models = [];
        $accesses = [];
        $groups = [];
        $psth = $this->pdo->prepare("SELECT * FROM devices WHERE group_id = ?");
        $psth->execute([$deviceGroup->getId()]);
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $row) {
            $device = $this->fillByArr(new Device($row['id']), $row);
            $device->enabled = $device->enabled ? true : false;

            if(isset($accesses[$device->access_id])) {
                $access = $accesses[$device->access_id];
            } else {
                $access = $this->accessStorage->fill((new DeviceAccess())->setId($device->access_id));
                $accesses[$device->access_id] = $access;
            }
            if(isset($models[$device->model_id])) {
                $model = $models[$device->model_id];
            } else {
                $model = $this->modelStorage->fill((new DeviceModel())->setId($device->model_id));
                $models[$device->model_id] = $model;
            }
            if(isset($groups[$device->group_id])) {
                $group = $groups[$device->group_id];
            } else {
                $group = $this->deviceGroupStorage->fill((new DeviceGroup($device->group_id)));
                $groups[$device->group_id] = $group;
            }

            $device->setAccess($access);
            $device->setModel($model);
            $device->setGroup($group);
            $resp[] = $device;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return Device
     */
    function getById($id) {
        return $this->getObjectById(Device::class, $id);
    }
    /**
     * @param $ip_address
     * @return Device
     */
    function getByIp($ip_address) {
        $psth = $this->pdo->prepare("SELECT id FROM devices WHERE ip = ?");
        $psth->execute([$ip_address]);
        if($psth->rowCount() === 0) {
            throw new RecordNotFoundException("Device with ip $ip_address not found in storage");
        }
        return $this->getById($psth->fetchAll()[0]['id']);
    }

    function getCountDevices(bool $enabled = true) {
        $enabled = $enabled ? "1" : "0";
        return $this->pdo->query("SELECT count(*) count FROM devices WHERE enabled = $enabled")->fetchAll()[0]['count'];
    }

    /**
     * @return array[]
     */
    function findNearestByCoordinates(float $lat, float $lon, float $distanceMeters, array $deviceGroupIds, int $limit = 100)
    {
        $deviceGroupIds = array_values(array_filter($deviceGroupIds, 'is_numeric'));
        if (!$deviceGroupIds) {
            return [];
        }
        $limit = max(1, $limit);

        $placeholders = trim(str_repeat('?,', count($deviceGroupIds)), ',');
        $distanceSql = "(6371000 * 2 * ASIN(SQRT(
            POWER(SIN((RADIANS(coords.lat) - RADIANS(?)) / 2), 2) +
            COS(RADIANS(?)) * COS(RADIANS(coords.lat)) *
            POWER(SIN((RADIANS(coords.lon) - RADIANS(?)) / 2), 2)
        )))";
        $query = "
            SELECT coords.*, {$distanceSql} distance_m
            FROM (
                SELECT
                    d.id,
                    JSON_UNQUOTE(JSON_EXTRACT(d.coordinates, '$.lat')) + 0 lat,
                    JSON_UNQUOTE(JSON_EXTRACT(d.coordinates, '$.lon')) + 0 lon
                FROM devices d
                WHERE d.enabled = 1
                    AND d.coordinates IS NOT NULL
                    AND JSON_EXTRACT(d.coordinates, '$.lat') IS NOT NULL
                    AND JSON_EXTRACT(d.coordinates, '$.lon') IS NOT NULL
                    AND d.group_id IN ({$placeholders})
            ) coords
            HAVING distance_m <= ?
            ORDER BY distance_m
            LIMIT {$limit}
        ";

        $params = array_merge([$lat, $lat, $lon], $deviceGroupIds, [$distanceMeters]);
        $psth = $this->pdo->prepare($query);
        $psth->execute($params);

        return array_map(function ($row) {
            return [
                'type' => 'device',
                'id' => (int)$row['id'],
                'distance_m' => round((float)$row['distance_m'], 2),
            ];
        }, $psth->fetchAll(\PDO::FETCH_ASSOC));
    }

    /**
     * @param $line
     * @return Device[]
     * @throws Exception
     */
    function getBySearchLine($line) {
        $data = $this->pdo->prepare("SELECT d.*
FROM devices d
JOIN device_models m on m.id = d.model_id
WHERE concat(d.description, ';', d.ip, ';', d.name, ';', d.mac, ';', d.serial, ';', m.name, ';', m.vendor, ';', m.model) LIKE ? order by d.name");
        $data->execute(["%{$line}%"]);
        $resp = [];
        foreach ($data->fetchAll() as $e) {
            $device = $this->fillByArr(new Device(), $e);
            $device->enabled = $device->enabled  == 1 ? true : false;
            $device->setAccess($this->accessStorage->fill((new DeviceAccess())->setId($device->access_id)));
            $device->setModel($this->modelStorage->fill((new DeviceModel())->setId($device->model_id)));
            $device->setGroup($this->deviceGroupStorage->fill((new DeviceGroup($device->group_id))));
            $resp[] = $device;
        }
        return $resp;
    }
    function getByPaginator(DbPagination $pagination) {
        $query = "SELECT d.*
            FROM devices d
            JOIN device_models m on m.id = d.model_id
            ";
        if($where  = $pagination->getWhereQuery()) {
            $query .= " WHERE concat(d.description, ';', d.ip, ';', d.name, ';', d.mac, ';', d.serial, ';', m.name, ';', m.vendor, ';', m.model) LIKE " . $this->pdo->quote("%{$where}%") . " ";
        }
        $pagination->setTotalRecords($this->pdo->query($query)->rowCount());
        if($order = $pagination->getOrderQuery()) {
            $query .= $order;
        }
        if($limit = $pagination->getLimitsQuery()) {
            $query .= $limit;
        }
        $data = $this->pdo->query($query);
        $resp = [];
        foreach ($data->fetchAll() as $e) {
            $device = $this->fillByArr(new Device(), $e);
            $device->enabled = $device->enabled  == 1 ? true : false;
            $device->setAccess($this->accessStorage->fill((new DeviceAccess())->setId($device->access_id)));
            $device->setModel($this->modelStorage->fill((new DeviceModel())->setId($device->model_id)));
            $device->setGroup($this->deviceGroupStorage->fill((new DeviceGroup($device->group_id))));
            $resp[] = $device;
        }
        $pagination->setRecords($resp);
        return $resp;
    }
}
