<?php


namespace WCAA\Storage\Devices;


use WCAA\App;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceModel;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

/**
 *
 * Class DeviceModelStorage
 * @package WCAA\Storage\Devices
 */
class DeviceModelStorage extends AbstractStorage
{
    protected $tableName = 'device_models';

    function getByName($name) {
        $id = $this->getOneIdByWhere("name = ? limit 1", [$name]);
        if(!$id) {
            throw new RecordNotFoundException("Model with name='{$name}' not found in storage");
        }
        return $this->fill((new DeviceModel())->setId($id));
    }
    function getByKey($key) {
        $id = $this->getOneIdByWhere("`key` = ? limit 1", [$key]);
        if(!$id) {
            throw new \Exception("Model with key='{$key}' not found in storage");
        }
        return $this->fill((new DeviceModel())->setId($id));
    }
    public function fill($object, $fillChildObjects = true)
    {
        if($this->isCacheExist($object) && $cache = $this->getCache($object)) {
            return  $cache;
        }
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        return $obj;
    }

    /**
     * @return DeviceModel[]
     */
    function fetchAll() {
        $resp = [];
        foreach ($this->fetchAllIds(null, "name") as $e) {
            $model = $this->fill(new DeviceModel($e));
            $resp[] = $model;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return DeviceModel
     */
    function getById($id) {
        return $this->getObjectById(DeviceModel::class, $id);
    }

    function update($object)
    {
        return parent::update($object); // TODO: Change the autogenerated stub
    }
}
