<?php


namespace WCC\Links\Storage;


use DI\Container;
use WCAA\App;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCC\Links\Models\Link;
use WCC\Pinger\Storage\PingerDeviceStatusStorage;

/**
 * @method Device fillByArr($object, $fetchArr = [])
 * Class DeviceStorage
 * @package WCAA\Storage\Devices
 */
class LinkStorage extends AbstractStorage
{
    const MAX_DEPTH = 15;
    protected $tableName = 'c_links';


    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    /**
     * @var PingerDeviceStatusStorage
     */
    protected $pingerStatus = null;

    function __construct(App $app)
    {
        if($app->getContainer()->get(PingerDeviceStatusStorage::class)) {
            $this->pingerStatus = $app->getContainer()->get(PingerDeviceStatusStorage::class);
        }
    }

    /**
     * @param $object Link
     * @return Link
     */
    function add($object)
    {
        $object->src_device_id = $object->getSrcDevice()->getId();
        $object->dest_device_id = $object->getDestDevice()->getId();
        if ($object->getSrcIface()) {
            $object->src_iface_id = $object->getSrcIface()->getId();
        }
        if ($object->getDestIface()) {
            $object->dest_iface_id = $object->getDestIface()->getId();
        }
        $object = parent::add($object);
        return $this->fill($object);
    }

    /**
     * @param $object Link
     * @return Link
     */
    function update($object)
    {
        $object->src_device_id = $object->getSrcDevice()->getId();
        $object->dest_device_id = $object->getDestDevice()->getId();
        if ($object->getSrcIface()) {
            $object->src_iface_id = $object->getSrcIface()->getId();
        }
        if ($object->getDestIface()) {
            $object->dest_iface_id = $object->getDestIface()->getId();
        }
        $object = parent::update($object);
        return $this->fill($object);
    }


    /**
     * @param $object Link
     * @return Link
     */
    public function fill($object, $fillChildObjects = true)
    {
        /**
         * @var $object Link
         */
        $object = parent::fill($object);
        if($fillChildObjects) $object->setSrcDevice($this->deviceStorage->getById($object->src_device_id));
        if($fillChildObjects) $object->setDestDevice($this->deviceStorage->getById($object->dest_device_id));

        if ($object->src_iface_id) {
            if($fillChildObjects) $object->setSrcIface($this->deviceInterfaceStorage->getById($object->src_iface_id));
        }
        if ($object->dest_iface_id) {
            if($fillChildObjects) $object->setDestIface($this->deviceInterfaceStorage->getById($object->dest_iface_id));
        }
        return $object;
    }

    /**
     * @param $id
     * @return Link
     */
    function getById($id)
    {
        return parent::getObjectById(new Link(), $id); // TODO: Change the autogenerated stub
    }

    /**
     * @param Device $device
     * @return Link[]
     */
    function getBySourceDevice(Device $device)
    {
        $fetched = $this->fetchAllIds("src_device_id = " . $this->pdo->quote($device->getId()));
        $items = [];
        foreach ($fetched as $id) {
            $items[] = $this->fill(new Link($id));
        }
        return $items;
    }

    /**
     * @param Device $device
     * @return Link[]
     */
    function getByDestDevice(Device $device)
    {

        $fetched = $this->fetchAllIds("dest_device_id = " . $this->pdo->quote($device->getId()));
        $items = [];
        foreach ($fetched as $id) {
            $items[] = $this->fill(new Link($id));
        }
        return $items;
    }

    /**
     * @param DeviceInterface $iface
     * @return Link[]
     */
    function getByDeviceInterface(DeviceInterface $iface)
    {
        $ifaceId = $this->pdo->quote($iface->getId());
        $fetched = $this->fetchAllIds("src_iface_id = $ifaceId or dest_iface_id = $ifaceId");
        $items = [];
        foreach ($fetched as $id) {
            $items[] = $this->fill(new Link($id));
        }
        return $items;
    }

    /**
     * @return Link[]
     */
    function fetchAll()
    {
        $devices = [];
        foreach ($this->deviceStorage->fetchAll() as $device) {
            $devices[$device->getId()] = $device;
        }
        $ifaces = [];
        foreach ($this->deviceInterfaceStorage->fetchAllForTopology(false) as $iface) {
            $ifaces[$iface->getId()] = $iface->setDevice($devices[$iface->getDeviceId()]);
        }

        $links = $this->pdo->prepare("SELECT * FROM c_links order by id desc");
        $links->execute();
        $objects = [];
        foreach ($links->fetchAll(\PDO::FETCH_ASSOC) as $link) {
            /**
             * @var $obj Link
             */
            $obj = $this->fillByArr(new Link(), $link);
            if(isset($devices[$obj->getSrcDeviceId()])) {
                $obj->setSrcDevice($devices[$obj->getSrcDeviceId()]);
            }
            if(isset($devices[$obj->getDestDeviceId()])) {
                $obj->setDestDevice($devices[$obj->getDestDeviceId()]);
            }
            if(isset($ifaces[$obj->getSrcIfaceId()])) {
                $obj->setSrcIface($ifaces[$obj->getSrcIfaceId()]);
            }
            if(isset($ifaces[$obj->getDestIfaceId()])) {
                $obj->setDestIface($ifaces[$obj->getDestIfaceId()]);
            }
            $objects[] = $obj;
        }
        return $objects;
    }

    function getUplinkTree(Device $device)
    {
        $psth = $this->pdo->prepare("WITH RECURSIVE tree AS (
                SELECT l.id, src_device_id, dest_device_id, src_iface_id, 1 as depth
                FROM c_links l
                WHERE dest_device_id = ?
                UNION ALL
                SELECT t.id, t.src_device_id, t.dest_device_id, t.src_iface_id, np.depth + 1
                FROM c_links t
                         INNER JOIN tree np ON t.dest_device_id = np.src_device_id
                WHERE np.depth < ".self::MAX_DEPTH."
            )
            SELECT *
            FROM tree
            order by depth desc;");
        $psth->execute([$device->getId()]);
        $links = [];
        $last = null;
        foreach ($psth->fetchAll() as $dt) {
            $last = $dt;
            $device = $this->deviceStorage->getById($dt['src_device_id']);
            $link = [
                'id' => $dt['id'],
                'device' => $device,
                'uplink_interface' => $this->getUplinkPortByDeviceId($device->getId()),
                'downlink_interface' => $this->getDownlinkInterfaceOnSourceDevice($device->getId(), $dt['dest_device_id']),
                'depth' => $dt['depth'],
            ];
            $links[] = $link;
        }
        if($last) {
            $device = $this->deviceStorage->getById($dt['dest_device_id']);
            $link = [
                'id' => $dt['id'],
                'device' => $device,
                'uplink_interface' => $this->getUplinkPortByDeviceId($device->getId()),
                'downlink_interface' => null,
                'depth' => 0,
            ];
            $links[] = $link;
        };

        return $links;
    }
    protected function getUplinkPortByDeviceId($deviceId)
    {
        $psth = $this->pdo->prepare("SELECT dest_iface_id FROM c_links WHERE dest_device_id = ?");
        $psth->execute([$deviceId]);
        $ph = $psth->fetch();
        if($ph && $ph['dest_iface_id']) {
            return $this->deviceInterfaceStorage->getById($ph['dest_iface_id']);
        }
        return null;
    }
    protected function getDownlinkInterfaceOnSourceDevice($srcDeviceId, $destDeviceId)
    {
        $psth = $this->pdo->prepare("SELECT src_iface_id
            FROM c_links l
            WHERE src_device_id = ? and dest_device_id = ?");
        $psth->execute([$srcDeviceId, $destDeviceId]);
        $dt = $psth->fetch();
        if ($dt && $dt['src_iface_id']) {
            return $this->deviceInterfaceStorage->getById($dt['src_iface_id']);
        }
        return null;
    }

    function getLevelsWithDeviceIds() {
        $psth =  $this->pdo->prepare("WITH RECURSIVE NodeLevels AS (
                    -- Базовый случай: выбираем все узлы, которые не имеют родителя (уровень 0)
                    SELECT src_device_id AS node_id, 0 AS level
                    FROM c_links
                    WHERE src_device_id NOT IN (SELECT dest_device_id FROM c_links)
                    UNION ALL
                    -- Рекурсивный случай: для каждого дочернего узла увеличиваем уровень на 1
                    SELECT t.dest_device_id AS node_id, nl.level + 1 AS level
                    FROM c_links t
                             JOIN NodeLevels nl ON t.src_device_id = nl.node_id
                    WHERE nl.level < 50
                )
                -- Выводим результат
                SELECT DISTINCT node_id, level
                FROM NodeLevels
                ORDER BY level, node_id;");
        $psth->execute();
        $deviceIds = [];
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $device) {
            $deviceIds[$device['node_id']] = $device['level'];

        }
        return $deviceIds;
    }
    function getChildCountByDeviceId() {
        $psth =  $this->pdo->prepare("WITH RECURSIVE DeviceCounts AS (
                -- Базовый случай: выбираем все устройства, которые являются источниками
                SELECT
                    src_device_id AS node_id,
                    COUNT(dest_device_id) AS direct_children_count,
                    0 as lvl  
                -- Количество прямых дочерних узлов
                FROM c_links
                GROUP BY src_device_id
            
                UNION ALL
            
                -- Рекурсивный случай: суммируем количество дочерних узлов для каждого устройства
                SELECT
                    t.src_device_id AS node_id,
                    dc.direct_children_count + 1 AS total_children_count, -- Добавляем дочерние узлы
                    dc.lvl + 1 lvl  
                FROM c_links t
                         JOIN DeviceCounts dc ON t.dest_device_id = dc.node_id
                WHERE dc.lvl < 50 
            )
            SELECT
                node_id,
                SUM(direct_children_count) AS total_children
            FROM DeviceCounts
            GROUP BY node_id
            ORDER BY 2;");
        $psth->execute();
        $deviceIds = [];
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $device) {
            $deviceIds[$device['node_id']] = $device['total_children'];

        }
        return $deviceIds;
    }


    /**
     * @param Device $device
     * @return Device|null
     */
    function getCoreByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("WITH RECURSIVE reverse_path AS (
                SELECT src_device_id, dest_device_id, 1 AS depth
                FROM c_links
                WHERE dest_device_id = ?
                UNION ALL
                SELECT t.src_device_id, t.dest_device_id,  rp.depth + 1
                FROM c_links t
                JOIN reverse_path rp ON t.dest_device_id = rp.src_device_id
                WHERE rp.depth < ".self::MAX_DEPTH."
            )
            SELECT * FROM reverse_path ORDER BY 3 desc limit 1;");
        $psth->execute([$device->getId()]);
        if($psth->rowCount() == 0) {
            return null;
        }
        return $this->deviceStorage->getById($psth->fetchAll(\PDO::FETCH_ASSOC)[0]['src_device_id']);
    }

    function buildDownArray($deviceId, int $level = 0)
    {
        if ($level > self::MAX_DEPTH) return [];
        $data = $level === 0 ? $this->getRootInfo($deviceId) : $this->getTreeInfo($deviceId);
        if ($level === 0) {
            $data['nodes'] = $this->buildDownArray($deviceId, $level + 1);
            return $data;
        }

        foreach ($data as $k => $entry) {
            $data[$k]['nodes'] = $this->buildDownArray($entry['device_id'], $level + 1);
        }

        return $data;
    }

    private function getTreeInfo($deviceId): array
    {
        $psth = $this->pdo->prepare("
                SELECT l.src_iface_id, l.src_device_id,
                       l.dest_device_id, l.dest_iface_id,
                       d.ip device_ip,
                       d.id device_id,
                       REPLACE(REPLACE(d.name, '\"', ''), '\\\', '') name,
                       REPLACE(REPLACE(d.location, '\"', ''), '\\\', '') location,
                       ps.latency, 
                       dm.name model_name,
                       si.name src_iface_name,
                       si.description src_iface_description,
                       si.bind_key src_iface_bind_key,
                       si.status src_iface_status,
                       di.name dest_iface_name,
                       di.description dest_iface_description,
                       di.bind_key dest_iface_bind_key,
                       di.status dest_iface_status,
                       l.id link_id,
                       si.bind_key sort_id
                FROM c_links l
                         JOIN devices d ON d.id = l.dest_device_id
                         JOIN device_models dm on dm.id = d.model_id
                         JOIN c_pinger_statuses ps ON ps.device_id = d.id
                         LEFT JOIN device_interfaces si on si.id = l.src_iface_id
                         LEFT JOIN device_interfaces di on di.id = l.dest_iface_id
                WHERE l.src_device_id = ? ORDER BY sort_id
        ");
        $psth->execute([$deviceId]);
        $ports = [];
        foreach ($psth->fetchAll() as $f) {
            $ports[] = $f;
        }
        return $ports;
    }

    private function getRootInfo($deviceId): array
    {
        $psth = $this->pdo->prepare("
             SELECT d.id device_id, 
                   d.ip device_ip,
                       REPLACE(REPLACE(d.name, '\"', ''), '\\\', '') name,
                       REPLACE(REPLACE(d.location, '\"', ''), '\\\', '') location,
                   ps.latency,
                   dm.name 
            FROM devices d
            JOIN device_models dm on dm.id = d.model_id
            JOIN c_pinger_statuses ps ON ps.device_id = d.id
            WHERE d.id = ?
        ");
        $psth->execute([$deviceId]);
        if($psth->rowCount() == 0) {
            throw new \Exception("Root device not found");
        }
        return $psth->fetchAll()[0];
    }
}
