<?php


namespace WCAA\Console\SwitcherCore;


use DI\Annotation\Inject;
use SwitcherCore\Switcher\Console\ConsoleInterface;
use Symfony\Component\Console\Input\InputOption;
use WCAA\Console\AbstractCommand;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\UserStorage;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use WCAA\SwitcherCore\SwitcherCore;
use WCAA\SwitcherCore\Request;

class SwitcherCoreCallModuleCommand extends AbstractCommand
{
    /**
     * @Inject
     * @var SwitcherCore
     */
    protected $swc;
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $devStorage;
    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    function configure()
    {
        $this->setName("switcher-core:call")
            ->addArgument("ip", InputArgument::REQUIRED, "Device ip address")
            ->addArgument("module", InputArgument::REQUIRED, "Module name")
            ->addArgument("arguments", InputArgument::IS_ARRAY, "Arguments. For example interface=pon0/1/1")
            ->addOption('telnet', 't', InputOption::VALUE_NEGATABLE, "Print telnet output", false )
            ->addOption("meta", "m", InputArgument::OPTIONAL, "Show meta", false)
            ->addOption("source", "s", InputArgument::OPTIONAL, "Source to use. Can be device(every call from device),store(every call from store) and cache(if not found in store - can be call from device)", 'device');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    function execute(InputInterface $input, OutputInterface $output)
    {
        $user = $this->userStorage->getById(-2);
        $this->swc->setUser($user);
        $arguments = [];
        foreach ($input->getArgument('arguments') as $argkv) {
            list($key, $value) = @explode("=", $argkv);
            $arguments[$key] = $value;
        }
        $device = $this->devStorage->getByIp($input->getArgument('ip'));
        $request = (new Request())
            ->setDevice($device)
            ->setModule($input->getArgument('module'))
            ->setArguments($arguments);;
        if ($output->isVerbose()) {
            $output->writeln("<info>=================================================================================</info>");
            $output->writeln(" <comment>Start calling from device {$device->getName()} ({$device->getIp()})</comment>");
            $output->writeln("   Module: <info>{$input->getArgument('module')}</info>");
            $output->writeln("   Arguments: <info>" . json_encode($arguments) . "</info>");
            $output->writeln("<info>=================================================================================</info>");
        }
        $response = null;
        $start = microtime(true);
        switch ($input->getOption('source')) {
            case 'device':
                $response = $this->swc->fromDevice([$request]);
                break;
            case 'store':
                $response = $this->swc->fromStore([$request]);
                break;
            case 'cache':
                $response = $this->swc->fromCache([$request]);
                break;
            default:
                throw new \InvalidArgumentException("Invalid source {$input->getOption('source')}");
        }
        $time = microtime(true) - $start;
        $response = $response->getFirstByModule($input->getArgument('module'));
        if ($response->getError()) {
            $output->writeln("<error>

   Error call module with message: {$response->getError()['message']}
</error>
");
            $output->writeln("
In: {$response->getError()['file']}:{$response->getError()['line']}
            
            ");
            $output->writeln("Exception trace:");
            $output->writeln($response->getError()['trace']);
        } else {
            $output->writeln(json_encode($response->getData(), JSON_PRETTY_PRINT | JSON_NUMERIC_CHECK | JSON_UNESCAPED_UNICODE));
            if ($output->isVerbose()) {
                $output->writeln("<info>=================================================================================</info>");
                $output->writeln("<info>\tSpent time: " . round($time, 4) . " sec</info>");
                $output->writeln("<info>=================================================================================</info>");
            }
        }

        if($input->getOption('telnet')) {
            /**
             * @var ConsoleInterface $telnet
             */
            $output->writeln("<comment>Telnet output:</comment>");
            $output->writeln("<comment>-------------------------------------------------------------------------------</comment>");
            $telnet = $this->swc->getCore($device)->getContainer()->get(ConsoleInterface::class);
            $output->writeln($telnet->getGlobalBuffer());
            $output->writeln("<comment>-------------------------------------------------------------------------------</comment>");

        }
        return self::SUCCESS;
    }
}