<?php


namespace WCAA\Console\SwitcherCore;


use DI\Annotation\Inject;
use SwitcherCore\Config\ModelCollector;
use SwitcherCore\Config\ModuleCollector;
use WCAA\Console\AbstractCommand;
use WCAA\Storage\Devices\DeviceStorage;
use Symfony\Component\Console\Helper\Table;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use WCAA\SwitcherCore\SwitcherCore;

class SwitcherCoreModulesCommand extends AbstractCommand
{
    /**
     * @Inject
     * @var ModelCollector
     */
    protected $modelCollector;

    /**
     * @Inject
     * @var ModuleCollector
     */
    protected $moduleCollector;


    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $devStorage;

    function configure()
    {
        $this->setName("switcher-core:modules")
            ->addArgument("ip", InputArgument::REQUIRED, "Device ip address");
        parent::configure(); // TODO: Change the autogenerated stub
    }
    function execute(InputInterface $input, OutputInterface $output)
    {
        $model = $this->modelCollector->getModelByKey($this->devStorage->getByIp($input->getArgument('ip'))->getModel()->getKey());

        $output->writeln("<comment>Information of device {$input->getArgument('ip')}</comment>");
        $output->writeln("Model: <info>{$model->getName()} ({$model->getKey()})</info>");
        $output->writeln("DeviceType: <info>{$model->getDeviceType()}</info>");
        $output->writeln("");
        $output->writeln("<comment>Modules: </comment>");
        $table = new Table($output);
        $table->setHeaders([
           'Module name',
           'Called class',
           'Arguments',

        ]);
        foreach ($model->getModulesListAssoc() as $moduleName=>$calledClass) {
            $module = $this->moduleCollector->getByName($moduleName);
            $arguments = '';
            foreach ($module->getArguments() as $argData) {
                $req = $argData['required'] ? "*" : "";
                $arguments .= "{$argData['name']}$req, pattern: /{$argData['pattern']}/\n";
            }
            $table->addRow([
                $module->getName(),
                $calledClass,
                trim($arguments),
            ]);
        }
        $table->render();
        return self::SUCCESS;
    }
}