<?php


namespace WCC\Console\Storage;


use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Models\SystemAction;
use WCAA\Models\User\User;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;
use WCAA\Storage\UserStorage;
use WCC\Console\Models\ConsoleHistory;

/**
 * @method ConsoleHistory fillByArr($object, $fetchArr = [])
 * Class DeviceStorage
 * @package WCAA\Storage\Devices
 */
class ConsoleHistoryStorage extends AbstractStorage
{
    protected $tableName = 'c_console_history';


    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;


    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;


    /**
     * @param $object ConsoleHistory
     * @return mixed
     */
    function add($object)
    {
        if ($object->getDevice()) {
            $object->device_id = $object->getDevice()->getId();
        }
        if ($object->getUser()) {
            $object->user_id = $object->getUser()->getId();
        }
        parent::add($object);
        return $this->fill($object);
    }

    /**
     * @param $object ConsoleHistory
     * @return mixed
     */
    function update($object)
    {
        if ($object->getDevice()) {
            $object->device_id = $object->getDevice()->getId();
        }
        if ($object->getUser()) {
            $object->user_id = $object->getUser()->getId();
        }
        parent::update($object);
        $this->clearCache($object);
        return $this->fill($object);
    }

    /**
     * @param $object ConsoleHistory
     * @return ConsoleHistory
     */
    public function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object, $fillChildObjects);
        if ($fillChildObjects) {
            if ($object->device_id) {
                $object->device = $this->deviceStorage->getById($object->device_id);
            }
            if ($object->user_id) {
                $object->user = $this->userStorage->getById($object->user_id);
            }
        }
        $object->is_autologin = $object->is_autologin == 1;
        $this->setCache($object);
        return $object;
    }

    /**
     * @param $id
     * @return ConsoleHistory
     */
    function getById($id)
    {
        return parent::getObjectById(new ConsoleHistory(), $id); // TODO: Change the autogenerated stub
    }

    /**
     *
     * @return ConsoleHistory[]
     */
    function fetchAll()
    {
        $devices = $this->getDevicesMap();
        $users = $this->getUsersMap();
        $objects = [];
        $stale = false;
        foreach ($this->fetchAllIds() as $id) {
            try {
                $obj = $this->fill(new ConsoleHistory($id), false);
            } catch (RecordNotFoundException $e) {
                //Cached id list can outlive the row in a long-running worker.
                $stale = true;
                continue;
            }
            $obj->setLog("");
            if ($obj->device_id && isset($devices[$obj->device_id])) {
                $obj->device = $devices[$obj->device_id];
            }
            if ($obj->user_id && isset($users[$obj->user_id])) {
                $obj->user = $users[$obj->user_id];
            }
            $objects[] = $obj;
        }
        if ($stale) {
            $this->flushIds();
        }
        return $objects;
    }


    protected function getDevicesMap()
    {
        $olts = [];
        foreach ($this->deviceStorage->fetchAll() as $olt) {
            $olts[$olt->getId()] = $olt;
        };
        return $olts;
    }

    protected function getUsersMap()
    {
        $users = [];
        foreach ($this->userStorage->fetchAll() as $user) {
            $users[$user->getId()] = $user;
        };
        return $users;
    }


    /**
     * @param ConsoleHistory $object
     * @return ConsoleHistory
     * @throws \Exception
     */
    function updateOnDuplicate($object)
    {
        $object->user_id = $object->getUser()->getId();
        $object->device_id = $object->getDevice()->getId();
        return parent::updateOnDuplicate($object); // TODO: Change the autogenerated stub
    }

    function getByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("
            SELECT
                id, start_at, stop_at, user_id, device_id, is_autologin, log, error
            FROM c_console_history
            WHERE device_id = ? 
            ORDER BY id DESC LIMIT ?
        ");
        $psth->execute([$device->getId()]);
        return $this->prepareResults($psth, ['device' => $device, $this->app->conf('panel.logs_return_result_limit')]);
    }

    function getResultsByUser(User $user)
    {
        $psth = $this->pdo->prepare("
            SELECT
                id, start_at, stop_at, user_id, device_id, is_autologin, log, error
            FROM c_console_history
            WHERE user_id = ? 
            ORDER BY id DESC LIMIT ?
        ");
        $psth->execute([$user->getId(), $this->app->conf('panel.logs_return_result_limit')]);
        return $this->prepareResults($psth);
    }

    private function prepareResults(\PDOStatement $psth, $definedObjects = [])
    {
        if ($psth->rowCount() === 0) {
            throw new RecordNotFoundException('Records not found');
        }
        $response = [];
        foreach ($psth->fetchAll() as $row) {
            $log = $this->fillByArr(new Device(), $row);
            if (isset($definedObjects['device'])) {
                $log->device = $definedObjects['device'];
            } else {
                $log->device = $this->deviceStorage->getById($row['device_id']);
            }
            if (isset($definedObjects['user'])) {
                $log->user = $definedObjects['user'];
            } else {
                $log->user = $this->userStorage->getById($row['user_id']);
            }
        }
        return $response;
    }


    /**
     * @param $periodStart
     * @param null|string $periodStop
     * @param Device[] $devices
     * @param User[] $users
     * @param bool $hasErrors
     * @return ConsoleHistory[]
     */
    function getConsoleHistory($periodStart, $periodStop, $devices = [], $users = [], $hasErrors = false, $onlyOpenSessions = false)
    {
        $query = "SELECT id, start_at, stop_at, user_id, device_id, is_autologin,  error
            FROM c_console_history WHERE (start_at BETWEEN ? and ?) ";
        if ($devices) {
            $deviceIds = array_map(function ($e) {
                return $this->pdo->quote($e->getId(), \PDO::PARAM_INT);
            }, $devices);
            $query .= " and device_id in (" . join(',', $deviceIds) . ")";
        }
        if ($users) {
            $userIds = array_map(function ($e) {
                return $this->pdo->quote($e->getId(), \PDO::PARAM_INT);
            }, $users);
            $query .= " and user_id in (" . join(',', $userIds) . ")";
        }
        if ($hasErrors) {
            $query .= " and `error` is not null ";
        }
        if ($onlyOpenSessions) {
            $query .= " and `stop_at` is null";
        }
        $query .= " ORDER BY 1 desc limit ?";
        $psth = $this->pdo->prepare($query);
        $psth->execute([$periodStart, $periodStop, $this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];
        $users = [];
        $devices = [];
        foreach ($psth->fetchAll() as $d) {
            $r = $this->fillByArr(new ConsoleHistory(), $d);
            if($d['user_id']) {
                if(isset($users[$d['user_id']])) {
                    $user = $users[$d['user_id']];
                } else {
                    $user = $this->userStorage->fill(new User($d['user_id']));
                    $users[$d['user_id']] = $user;
                }
                $r->setUser($user);
            }
            if($d['device_id']) {
                if(isset($devices[$d['device_id']])) {
                    $device = $devices[$d['device_id']];
                } else {
                    $device = $this->deviceStorage->fill(new Device($d['device_id']));
                    $devices[$d['device_id']] = $device;
                }
                $r->setDevice($device);
            }
            $resp[] = $r;
        }
        return $resp;
    }

    /**
     * @param $periodStart
     * @param null|string $periodStop
     * @param array $devices
     * @param array $users
     * @param bool $hasErrors
     * @return int
     */
    function getCountByFilter($periodStart, $periodStop, $devices = [], $users = [], $hasErrors = false, $onlyOpenSessions = false)
    {
        $query = "SELECT count(*) c 
                    FROM  `{$this->tableName}` WHERE (start_at BETWEEN ? and ?) ";
        if ($devices) {
            $deviceIds = array_map(function ($e) {
                return $this->pdo->quote($e->getId(), \PDO::PARAM_INT);
            }, $devices);
            $query .= " and device_id in (" . join(',', $deviceIds) . ")";
        }
        if ($users) {
            $userIds = array_map(function ($e) {
                return $this->pdo->quote($e->getId(), \PDO::PARAM_INT);
            }, $users);
            $query .= " and user_id in (" . join(',', $userIds) . ")";
        }
        if ($hasErrors) {
            $query .= " and `error` is not null ";
        }
        if ($onlyOpenSessions) {
            $query .= " and `stop_at` is null";
        }
        $query .= " ORDER BY 1 desc limit ?";
        $psth = $this->pdo->prepare($query);
        $psth->execute([$periodStart, $periodStop, $this->app->conf('panel.logs_return_result_limit')]);


        return (int)$psth->fetch()['c'];
    }

}
