max_execution_time=3600
display_errors=1
memory_limit=128M

[xdebug]
xdebug.mode=off
xdebug.default_enable=0
xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.profiler_enable=0

#Test preloading
#opcache.preload_user=www-data
#opcache.preload=/www/app/init.php

