#!/usr/bin/env bash
# Demo: two redundant transport paths Kathmandu -> Pathari.
#
#   ./demo-setup.sh up      create demo devices, links and paths
#   ./demo-setup.sh status  show current path/group state
#   ./demo-setup.sh down    remove everything this script created
#
# Devices are created with unroutable TEST-NET-3 addresses (203.0.113.x), so the
# pinger will report them as unreachable and every path will show as down. That
# is the point: it proves the alerting path works. Point the IPs at real gear to
# see them come up.
#
# Optional env:
#   API=http://127.0.0.1:8088    base URL
#   WCA_AUTH_KEY=<key>           sent as X-Auth-Key when set
set -euo pipefail

API="${API:-http://127.0.0.1:8088}"
BASE="${API}/api/v1"
GROUP_ID="${GROUP_ID:-1}"
ACCESS_ID="${ACCESS_ID:-2}"
# 106 = Alcatel switch, a generic SWITCH model with a valid controller.
# (144/161/162 shipped with a malformed controller column - see error-log notes.)
MODEL_ID="${MODEL_ID:-106}"
GROUP_KEY="ktm-pathari-demo"
TAG="[paths-demo]"

need() { command -v "$1" >/dev/null || { echo "Missing command: $1"; exit 1; }; }
need curl
need python3

auth_args=()
[[ -n "${WCA_AUTH_KEY:-}" ]] && auth_args=(-H "X-Auth-Key: ${WCA_AUTH_KEY}")

api() {
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -sS -X "$method" "${BASE}${path}" "${auth_args[@]}" \
      -H 'Content-Type: application/json' -d "$body"
  else
    curl -sS -X "$method" "${BASE}${path}" "${auth_args[@]}"
  fi
}

jget() { python3 -c "import sys,json;d=json.load(sys.stdin);print(eval('d'+sys.argv[1]))" "$1"; }

create_device() {
  local name="$1" ip="$2" lat="$3" lon="$4"
  local payload id
  payload=$(python3 - "$name" "$ip" "$GROUP_ID" "$ACCESS_ID" "$MODEL_ID" <<'PY'
import json,sys
name,ip,g,a,m = sys.argv[1:6]
print(json.dumps({
  "name": name, "ip": ip,
  "description": "[paths-demo] generated by components/Paths/examples/demo-setup.sh",
  "group": {"id": int(g)}, "access": {"id": int(a)}, "model": {"id": int(m)},
}))
PY
)
  id=$(api POST /device "$payload" | jget "['data']['id']")

  #Coordinates are only settable through the update endpoint, not on create.
  #The model stores them as an object, despite the OpenAPI annotation showing a string.
  api PUT "/device/${id}" "{\"coordinates\":{\"lat\":${lat},\"lon\":${lon}}}" >/dev/null
  echo "$id"
}

create_link() {
  local src="$1" dst="$2"
  api POST /component/links "{\"src_device\":{\"id\":${src}},\"dest_device\":{\"id\":${dst}}}" \
    | jget "['data']['id']"
}

create_path() {
  local name="$1" a="$2" b="$3" prio="$4" links="$5"
  api POST /component/paths \
    "{\"name\":\"${name}\",\"group_key\":\"${GROUP_KEY}\",\"priority\":${prio},\"endpoint_a_id\":${a},\"endpoint_b_id\":${b},\"link_ids\":[${links}]}" \
    | jget "['data']['id']"
}

cmd_up() {
  echo "==> Creating demo devices"
  KTM=$(create_device     "DEMO-KATHMANDU" "203.0.113.11" 27.7172 85.3240)
  BELBARI=$(create_device "DEMO-BELBARI"   "203.0.113.12" 26.6333 87.3500)
  DAMAK=$(create_device   "DEMO-DAMAK"     "203.0.113.13" 26.6667 87.7000)
  PATHARI=$(create_device "DEMO-PATHARI"   "203.0.113.14" 26.6500 87.4667)
  echo "    KTM=$KTM  BELBARI=$BELBARI  DAMAK=$DAMAK  PATHARI=$PATHARI"

  echo "==> Creating links"
  L1=$(create_link "$KTM" "$BELBARI")
  L2=$(create_link "$BELBARI" "$PATHARI")
  L3=$(create_link "$KTM" "$DAMAK")
  L4=$(create_link "$DAMAK" "$PATHARI")
  echo "    links: $L1 $L2 $L3 $L4"

  echo "==> Creating paths (both in group '${GROUP_KEY}')"
  P1=$(create_path "Kathmandu -> Belbari -> Pathari" "$KTM" "$PATHARI" 10 "$L1,$L2")
  P2=$(create_path "Kathmandu -> Damak -> Pathari"   "$KTM" "$PATHARI" 20 "$L3,$L4")
  echo "    paths: $P1 (primary), $P2 (backup)"

  echo
  echo "Done. Now run:"
  echo "  docker compose exec -T wca sh -lc 'cd /www && ./console paths:calc-state'"
  echo "  $0 status"
}

cmd_status() {
  api GET /component/paths/groups | python3 -c "
import sys,json
for g in json.load(sys.stdin).get('data') or []:
    if g.get('group_key') != '${GROUP_KEY}': continue
    print(f\"group={g['group_key']}  state={g['state'].upper()}  usable={g['usable']}/{g['total']}  protected={g['protected']}\")
    for m in g['members']:
        print(f\"   [{m['state']:9}] prio={m['priority']:<4} {m['name']}\")
"
}

cmd_down() {
  echo "==> Removing demo paths"
  api GET /component/paths | python3 -c "
import sys,json
for p in json.load(sys.stdin).get('data') or []:
    if p.get('group_key') == '${GROUP_KEY}': print(p['id'])
" | while read -r id; do [[ -n "$id" ]] && api DELETE "/component/paths/${id}" >/dev/null && echo "    path $id"; done

  echo "==> Removing demo devices (links cascade)"
  api GET /device | python3 -c "
import sys,json
for d in json.load(sys.stdin).get('data') or []:
    if str(d.get('name','')).startswith('DEMO-'): print(d['id'])
" | while read -r id; do [[ -n "$id" ]] && api DELETE "/device/${id}" >/dev/null && echo "    device $id"; done
  echo "Done."
}

case "${1:-}" in
  up) cmd_up ;;
  status) cmd_status ;;
  down) cmd_down ;;
  *) echo "Usage: $0 {up|status|down}"; exit 1 ;;
esac
