<?php

namespace WCC\TrapService\Storage;

use WCAA\Exceptions\SupportException;
use WCAA\Infrastructure\Paginator\DbPagination;
use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCC\TrapService\Models\TrapFilter;
use WCC\TrapService\Models\TrapLog;

class TrapLogStorage extends AbstractStorage
{
    protected $tableName = 'c_trap_logs';

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    protected $cached = [
        'interfaces' => [],
        'devices' => [],
    ];

    /**
     * @param TrapLog $object
     * @return TrapLog
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        if ($fillChildObjects) {
            if (isset($this->cached['devices'][$obj->device_id])) {
                $obj->device = $this->cached['devices'][$obj->device_id];
            } else {
                $obj->device = $this->deviceStorage->getById($obj->device_id);
                $this->cached['devices'][$obj->device_id] = $obj->device;
            }

            if ($obj->interface_id) {
                if (isset($this->cached['interfaces'][$obj->interface_id])) {
                    $obj->device = $this->cached['interfaces'][$obj->interface_id];
                } else {
                    $obj->interface = $this->deviceInterfaceStorage->getById($obj->interface_id);
                    $this->cached['interfaces'][$obj->interface_id] = $obj->interface;
                }
            }
        }
        return $obj;
    }

    /**
     * @param TrapLog $object
     * @param $fillArr
     * @return TrapLog
     */
    public function fillByArr($object, $fillArr = [])
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        if (isset($this->cached['devices'][$obj->device_id])) {
            $obj->device = $this->cached['devices'][$obj->device_id];
        } else {
            $obj->device = $this->deviceStorage->getById($obj->device_id);
            $this->cached['devices'][$obj->device_id] = $obj->device;
        }
        if ($obj->interface_id) {
            if (isset($this->cached['interfaces'][$obj->interface_id])) {
                $obj->interface = $this->cached['interfaces'][$obj->interface_id];
            } else {
                $obj->interface = $this->deviceInterfaceStorage->getById($obj->interface_id);
                $this->cached['interfaces'][$obj->interface_id] = $obj->interface;
            }
        }
        return $obj;
    }

    /**
     * @param TrapLog $object
     * @return TrapLog
     */
    public function add($object)
    {
        $object->device_id = $object->device->getId();
        if ($object->getInterface()) {
            $object->interface_id = $object->getInterface()->getId();
        }
        return parent::add($object);
    }

    /**
     * @param TrapLog $object
     * @return TrapLog
     */
    public function update($object)
    {
        $object->device_id = $object->device->getId();
        if ($object->getInterface()) {
            $object->interface_id = $object->getInterface()->getId();
        }
        return parent::update($object);
    }


    /**
     * @param TrapFilter $filter
     * @param DbPagination|null $paginator
     * @return TrapLog[]
     */
    function getFilteredActions(TrapFilter $filter, ?DbPagination $paginator)
    {
        $WHERE = " WHERE 1=1 ";
        $ORDER = " order by  id desc ";
        $LIMIT = " LIMIT 50 ";

        if ($filter->device) {
            $WHERE .= " AND `device_id` = " . $this->pdo->quote($filter->getDevice()->getId());
        }
        if ($filter->interface) {
            $WHERE .= " AND `interface_id` = " . $this->pdo->quote($filter->getInterface()->getId());
        }
        if ($filter->object) {
            $WHERE .= " AND `object` = " . $this->pdo->quote($filter->getObject());
        }
        if ($filter->names) {
            $WHERE .= " AND `name` in (" . join(",", array_map(function ($n) {return $this->pdo->quote($n); }, $filter->getNames())) . ")";
        }
        if ($filter->timePeriod) {
            $WHERE .= " AND (`created_at` BETWEEN {$this->pdo->quote($filter->timePeriod[0])} AND {$this->pdo->quote($filter->timePeriod[1])})";
        }

        if($filter->getUser()) {
            if($filter->getUser()->getRole()->getId() > 0 && !in_array('events_see_all', $filter->getUser()->getRole()->getPermissions())) {
                $deviceGroupIds = [-10];
                foreach ($filter->getUser()->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = $gr->getId();
                }
                $WHERE .= " AND device_id in (SELECT id FROM devices WHERE group_id in (".join(",", $deviceGroupIds).")) ";
            }
        }

        if ($paginator) {
            if ($paginator->getWhereQuery()) {
                $query = $this->pdo->quote('%' . strtolower($paginator->getWhereQuery()) . '%');
                $WHERE .= " and concat(description, ':', name, ':', object) like {$query}";
            }
            $psth = $this->pdo->prepare("SELECT count(*) c FROM {$this->tableName} {$WHERE}");
            $psth->execute();
            $paginator->setTotalRecords($psth->fetch()['c']);
            if ($paginator->getPaginator()->getOrderBy()) {
                $ORDER = $paginator->getOrderQuery();
            }
            $LIMIT = $paginator->getLimitsQuery();
        }

        $psth = $this->pdo->prepare("SELECT * FROM {$this->tableName} {$WHERE} {$ORDER} {$LIMIT}");
        $psth->execute();

        /**
         * @var $data TrapLog[]
         */
        $data = [];
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $row) {
            $data[] = $this->fillByArr(new TrapLog(), $row);
        }

        return $data;
    }

    function getObjectNames()
    {
        $psth = $this->pdo->prepare("SELECT distinct name FROM {$this->tableName} WHERE name IS NOT NULL and name != '' ORDER BY 1");
        $psth->execute();

        return array_map(function ($e) { return $e['name']; }, $psth->fetchAll(\PDO::FETCH_ASSOC));
    }

    function clearOldLogs($days = 30)
    {
        $psth = $this->pdo->prepare("DELETE FROM `{$this->tableName}` WHERE created_at < NOW() - INTERVAL ? day");
         $psth->execute([$days]);

        $this->cache->deleteByRegex('/TrapLogStorage/');
        return $psth->rowCount();
    }
}
