{
 "title": "Interfaces stat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Кількість інтерфейсів в системі",
   "type": "stat",
   "description": "Кількість інтерфейсів може не відповідати статистичним даним у Support у випадках, коли частина мережевого обладнання була недоступною протягом більш ніж 6 годин та не підлягала опитуванню",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(device_interface)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Інтерфейси по типам",
   "type": "bargauge",
   "description": "Серед типів можуть бути інтерфейси типу Unknown, Eth, Ge. Слід враховувати, що типи інтерфейсів повертаються з обладнання «як є». Точне визначення типу інтерфейсу гарантується лише для ONU та PON-портів.",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface) by (iface_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статуси інтерфейсів",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface_status{iface_type != \"ONU\"} == 1)",
     "legendFormat": "Up"
    },
    {
     "expr": "count(device_interface_status{iface_type != \"ONU\"} <= 0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Статуси ОНУ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == 1)",
     "legendFormat": "Online"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == 0)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == -1)",
     "legendFormat": "PowerOff"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == -2)",
     "legendFormat": "LOS"
    }
   ]
  },
  {
   "title": "Зміна інтерфейсів за 7 днів",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface) - count(device_interface offset 7d)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Зміна інтерфейсів за 3 дня",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface) - count(device_interface offset 3d)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Динаміка інтерфейсів",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "count(device_interface) - count(device_interface offset 1d)",
     "legendFormat": "Приріст інтерфейсів"
    }
   ]
  },
  {
   "title": "Зміна інтерфейсів за 1 день",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface) - count(device_interface offset 1d)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Зміна інтерфейсів за 30 днів",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_interface) - count(device_interface offset 30d)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статуси ОНУ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == 1)",
     "legendFormat": "Online"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == 0)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == -1)",
     "legendFormat": "PowerOff"
    },
    {
     "expr": "count(device_interface_status{iface_type=\"ONU\"} == -2)",
     "legendFormat": "LOS"
    }
   ]
  }
 ]
}