"""The real trap definitions from the legacy switcher-core configs (backend/app/registry/trap_profile_data.py,
generated by tools/gen_trap_profile_catalogue.py). Every BDCOM OID is cross-checked against the real MIB corpus by
tools/bdcom-trap-audit.py separately; these tests check the catalogue's own shape and content."""
from app.registry.trap_profile_data import TRAP_PROFILES
from app.seed import seed


def test_the_real_profile_count_and_vendor_split():
    assert len(TRAP_PROFILES) == 28
    by_vendor: dict[str, int] = {}
    for vendor, *_ in TRAP_PROFILES:
        by_vendor[vendor] = by_vendor.get(vendor, 0) + 1
    assert by_vendor == {"global": 2, "bdcom": 18, "cdata": 4, "huawei": 4}


def test_every_entry_has_a_well_formed_oid_with_no_leading_dot():
    for vendor, name, oid, *_ in TRAP_PROFILES:
        assert not oid.startswith("."), f"{vendor}/{name} keeps the legacy leading dot"
        parts = oid.split(".")
        assert len(parts) >= 4 and all(p.isdigit() for p in parts), f"{vendor}/{name}: {oid!r}"


def test_every_name_is_unique_within_its_vendor():
    seen: set[tuple[str, str]] = set()
    for vendor, name, *_ in TRAP_PROFILES:
        key = (vendor, name)
        assert key not in seen, f"duplicate: {key}"
        seen.add(key)


def test_a_few_known_real_traps_by_name_and_oid():
    by_key = {(v, n): (oid, is_iface, modules) for v, n, oid, is_iface, modules, _d in TRAP_PROFILES}
    assert by_key[("global", "LinkDown")][0] == "1.3.6.1.6.3.1.1.5.3"
    assert by_key[("global", "LinkUp")][0] == "1.3.6.1.6.3.1.1.5.4"
    # The documented off-by-one: the MIB's real NOTIFICATION-TYPE is one below what the legacy config declares, kept
    # deliberately in case some firmware really emits the declared value (see the comment in bdcom.yml itself).
    assert by_key[("bdcom", "OnuSfpParameterAlarm")][0] == "1.3.6.1.4.1.3320.10.3.6.3"
    assert by_key[("bdcom", "OnuSfpParameterAlarmNotification")][0] == "1.3.6.1.4.1.3320.10.3.6.2"
    assert by_key[("bdcom", "OnuDyingGaspNotification")][1] is True  # is_interface
    assert by_key[("bdcom", "OnuDyingGaspNotification")][2] == ("pon_onts_status",)


def test_every_entry_has_a_non_empty_description():
    for vendor, name, _oid, _is_iface, _modules, description in TRAP_PROFILES:
        assert description.strip(), f"{vendor}/{name} has no description"


async def test_reseeding_keeps_trap_profiles_in_sync_with_the_code(db):
    # Unlike alarm_rules, these are code-owned vendor facts (like device_models): a hand-edit in the database is
    # overwritten by the next seed, not preserved.
    before = await db.fetchval("select count(*) from trap_profiles")
    await db.execute("update trap_profiles set oid = '9.9.9.9', description = 'tampered' where name = 'LinkDown'")
    await seed(db, admin_username="boot", admin_password="Boot-Strap-Password-1!")
    assert await db.fetchval("select count(*) from trap_profiles") == before
    row = await db.fetchrow("select oid, description from trap_profiles where name = 'LinkDown'")
    assert row["oid"] == "1.3.6.1.6.3.1.1.5.3" and row["description"] != "tampered"
