"""Plan 18: the per-model switch capability table, which modules the UI shows, and the FDB policy (off by default,
bounded when on). Pure logic, no device."""
import ast
from pathlib import Path

import pytest

from app.registry.device_model_data import DEVICE_MODELS
from app.registry.switch_capability_data import SWITCH_MODELS
from app.vendors.switch_capabilities import (
    ACTIONS_BY_MODEL,
    DISABLED,
    MAX_FDB_ROWS,
    MAX_FDB_VLANS,
    SWITCH_CAPABILITIES,
    FdbPolicy,
    fdb_enabled,
    fdb_problems,
    model_capabilities,
    visible_modules,
)

GOOD = FdbPolicy(enabled=True, max_rows=2048, timeout_ms=8000, vlan_ids=(10, 20))


def test_the_table_covers_every_switch_in_the_detection_catalogue_and_uses_only_known_capabilities():
    keys = {row[0] for row in SWITCH_MODELS}
    assert len(keys) == len(SWITCH_MODELS)
    assert {d[2] for d in DEVICE_MODELS if d[4] == "switch"} <= keys
    assert all(set(row[3]) <= set(SWITCH_CAPABILITIES) for row in SWITCH_MODELS)
    assert all({"system", "link_status", "counters"} <= set(row[3]) for row in SWITCH_MODELS)


def test_the_generated_file_says_it_is_generated_and_parses():
    path = Path(__file__).resolve().parents[1] / "app/registry/switch_capability_data.py"
    text = path.read_text()
    assert "Generated by tools/gen_switch_capabilities.py" in text and "Do not edit by hand" in text
    ast.parse(text)


def test_fdb_is_off_by_default_and_hidden_even_where_the_model_supports_it():
    assert "fdb" in model_capabilities("bdcom_s2200_series")
    assert DISABLED.enabled is False and fdb_enabled("bdcom_s2200_series") is False
    assert "fdb" not in visible_modules("bdcom_s2200_series")


def test_a_valid_enabled_policy_shows_fdb_last():
    modules = visible_modules("bdcom_s2200_series", GOOD)
    assert modules[-1] == "fdb" and fdb_problems("bdcom_s2200_series", GOOD) == []


def test_modules_a_model_lacks_are_hidden_and_order_follows_the_display_order():
    caps = model_capabilities("tplink_general_switch")
    modules = visible_modules("tplink_general_switch", GOOD)
    assert "fdb" not in caps and "fdb" not in modules
    assert set(modules) == caps and modules == [c for c in SWITCH_CAPABILITIES if c in caps]


@pytest.mark.parametrize("policy, problem", [
    (FdbPolicy(enabled=True, timeout_ms=8000, vlan_ids=(10,)), "max_rows"),
    (FdbPolicy(enabled=True, max_rows=0, timeout_ms=8000, vlan_ids=(10,)), "max_rows"),
    (FdbPolicy(enabled=True, max_rows=MAX_FDB_ROWS + 1, timeout_ms=8000, vlan_ids=(10,)), "max_rows"),
    (FdbPolicy(enabled=True, max_rows=100, vlan_ids=(10,)), "timeout_ms"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=199, vlan_ids=(10,)), "timeout_ms"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=30001, vlan_ids=(10,)), "timeout_ms"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=8000), "name the VLANs"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=8000, vlan_ids=tuple(range(1, MAX_FDB_VLANS + 2))), "at most"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=8000, vlan_ids=(0,)), "1 to 4094"),
    (FdbPolicy(enabled=True, max_rows=100, timeout_ms=8000, vlan_ids=(4095,)), "1 to 4094"),
])
def test_an_incomplete_or_unbounded_policy_is_refused_and_fdb_stays_hidden(policy, problem):
    problems = fdb_problems("bdcom_s2200_series", policy)
    assert any(problem in p for p in problems), problems
    assert not fdb_enabled("bdcom_s2200_series", policy) and "fdb" not in visible_modules("bdcom_s2200_series", policy)


def test_the_bounds_themselves_are_allowed():
    for policy in (FdbPolicy(True, 1, 200, (1,)), FdbPolicy(True, MAX_FDB_ROWS, 30000, tuple(range(4094 - MAX_FDB_VLANS + 1, 4095)))):
        assert fdb_problems("bdcom_s2200_series", policy) == []


def test_a_repeated_vlan_is_counted_once():
    assert fdb_problems("bdcom_s2200_series", FdbPolicy(True, 100, 8000, (10,) * (MAX_FDB_VLANS + 5))) == []


def test_fdb_on_a_model_without_it_is_refused_and_a_disabled_policy_is_never_a_problem():
    assert fdb_problems("tplink_general_switch", GOOD) == ["this model has no FDB support"]
    assert fdb_problems("tplink_general_switch", FdbPolicy(enabled=False, max_rows=-5)) == []


def test_unknown_models_are_configuration_errors():
    with pytest.raises(KeyError):
        visible_modules("no_such_switch")


def test_action_modules_are_recorded_apart_from_capabilities():
    assert ACTIONS_BY_MODEL["bdcom_s2200_series"] == {"console_command", "ctrl_port_descr", "multi_console_command", "save_config"}
    assert all(not (actions & set(SWITCH_CAPABILITIES)) for actions in ACTIONS_BY_MODEL.values())
