insert IGNORE into c_events_alertmanager_rules (created_at, updated_at, group_name, alert_name, expression, `for`, severity, annotation_summary, annotation_description, enabled)
values  ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'router', 'bgp_session_down', 'router_bgp_session_state_established == 0 and router_bgp_session_state_disabled == 0', '5m', 'warning', 'BGP Session Down', 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} DOWN', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'router', 'bgp_session_restarted', 'router_bgp_session_uptime < 300 and router_bgp_session_state_established == 1', '1m', 'warning', 'BGP Session reloaded', 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} RELOADED', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'interfaces', 'iface_increase_in_errors', 'delta(iface_stat_in_errors[15m]) > 30', '10m', 'warning', 'Errors increased', 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'interfaces', 'iface_increase_out_errors', 'delta(iface_stat_out_errors[15m]) > 30', '30m', 'warning', 'Errors increased', 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'interfaces', 'interface_is_down', 'device_interface_status == 0 and device_interface_admin_state == 1', '5m', 'info', 'Interface is DOWN', 'Interface {{ $labels.iface_name }} DOWN on host {{ $labels.ip }}', 0),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'optical', 'olt_rx_signal_deteriorated', 'avg_over_time(optical_olt_rx[1d:1h]) - avg_over_time(optical_olt_rx[30m]) > 2', '10m', 'warning', 'OLT RX signal deteriorated', 'OLT RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'pinger', 'pinger_host_down', 'pinger_host_status <= 0', '1m', 'warning', 'Device is down by ICMP', 'Device {{ $labels.ip }} is DOWN', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'interfaces', 'pon_box_status', 'pon_box_status == 0', '1m', 'info', 'PON box down', 'PON box with name {{ $labels.pon_iface }} on device {{ $labels.ip }}, port {{ $labels.pon_iface }} is DOWN', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'pon', 'pon_mass_onts_down', 'round(delta(count(label_replace(device_interface_status{iface_name=~".*:.*"}, "pon_port", "$1", "iface_name", "^(.*):[0-9]{1,4}$") == 0) by (dev_id, ip, pon_port)[15m:])) >= 3', '10m', 'warning', 'Mass ONTs is offile on PON port', '{{humanize $value}} ONTs was OFFLINE now on device {{ $labels.ip }}, on PON port {{ $labels.pon_port }}', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'pon', 'pon_ports_is_full', 'pon_port_current_onts_count / pon_port_max_onts_count * 100 > 90', '10m', 'warning', 'PON port is full', 'Port {{ $labels.iface_name }} on host {{ $labels.ip }} loaded to {{ humanize $value }}%', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'optical', 'rx_signal_deteriorated', 'avg_over_time(optical_rx[1d:1h]) - avg_over_time(optical_rx[30m]) > 2', '30m', 'warning', 'RX signal deteriorated', 'RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'device_resources', 'sys_cpu_highload', 'device_resources_cpu_util > 80', '15m', 'warning', 'CPU highload', 'CPU on device {{ $labels.ip }} highload, value {{humanize $value}}', 1),
        ('2023-04-20 16:09:26', '2023-04-20 16:09:26', 'system', 'system_not_enough_pollers', 'avg_over_time(system_poller_procs_busy_count[10m]) / avg_over_time(system_poller_procs_all_count[10m]) * 100 >= 99', '10m', 'warning', 'System problem', 'Not anough processes for pollers. Current pollers load is  {{ humanize $value }}% (You can increase parameter POLLER_COUNT_PROCS in .env or system configuration)', 1);

UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'router', alert_name = 'bgp_session_down' , expression = 'router_bgp_session_state_established == 0 and router_bgp_session_state_disabled == 0', `for` = '5m', severity = 'warning', annotation_summary = 'BGP Session Down', annotation_description = 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} DOWN', enabled = 1 WHERE alert_name = 'bgp_session_down';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'router', alert_name = 'bgp_session_restarted' , expression = 'router_bgp_session_uptime < 300 and router_bgp_session_state_established == 1', `for` = '1m', severity = 'warning', annotation_summary = 'BGP Session reloaded', annotation_description = 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} RELOADED', enabled = 1 WHERE alert_name = 'bgp_session_restarted';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'interfaces', alert_name = 'iface_increase_in_errors' , expression = 'delta(iface_stat_in_errors[15m]) > 30', `for` = '10m', severity = 'warning', annotation_summary = 'Errors increased', annotation_description = 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', enabled = 1 WHERE alert_name = 'iface_increase_in_errors';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'interfaces', alert_name = 'iface_increase_out_errors' , expression = 'delta(iface_stat_out_errors[15m]) > 30', `for` = '30m', severity = 'warning', annotation_summary = 'Errors increased', annotation_description = 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', enabled = 1 WHERE alert_name = 'iface_increase_out_errors';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'interfaces', alert_name = 'interface_is_down' , expression = 'device_interface_status == 0 and device_interface_admin_state == 1', `for` = '5m', severity = 'info', annotation_summary = 'Interface is DOWN', annotation_description = 'Interface {{ $labels.iface_name }} DOWN on host {{ $labels.ip }}', enabled = 0 WHERE alert_name = 'interface_is_down';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'optical', alert_name = 'olt_rx_signal_deteriorated' , expression = 'avg_over_time(optical_olt_rx[1d:1h]) - avg_over_time(optical_olt_rx[30m]) > 2', `for` = '10m', severity = 'warning', annotation_summary = 'OLT RX signal deteriorated', annotation_description = 'OLT RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', enabled = 1 WHERE alert_name = 'olt_rx_signal_deteriorated';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'pinger', alert_name = 'pinger_host_down' , expression = 'pinger_host_status <= 0', `for` = '1m', severity = 'warning', annotation_summary = 'Device is down by ICMP', annotation_description = 'Device {{ $labels.ip }} is DOWN', enabled = 1 WHERE alert_name = 'pinger_host_down';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'interfaces', alert_name = 'pon_box_status' , expression = 'pon_box_status == 0', `for` = '1m', severity = 'info', annotation_summary = 'PON box down', annotation_description = 'PON box with name {{ $labels.pon_iface }} on device {{ $labels.ip }}, port {{ $labels.pon_iface }} is DOWN', enabled = 1 WHERE alert_name = 'pon_box_status';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'pon', alert_name = 'pon_mass_onts_down' , expression = 'round(delta(count(label_replace(device_interface_status{iface_name=~".*:.*"}, "pon_port", "$1", "iface_name", "^(.*):[0-9]{1,4}$") == 0) by (dev_id, ip, pon_port)[15m:])) >= 3', `for` = '10m', severity = 'warning', annotation_summary = 'Mass ONTs is offile on PON port', annotation_description = '{{humanize $value}} ONTs was OFFLINE now on device {{ $labels.ip }}, on PON port {{ $labels.pon_port }}', enabled = 1 WHERE alert_name = 'pon_mass_onts_down';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'pon', alert_name = 'pon_ports_is_full' , expression = 'pon_port_current_onts_count / pon_port_max_onts_count * 100 > 90', `for` = '10m', severity = 'warning', annotation_summary = 'PON port is full', annotation_description = 'Port {{ $labels.iface_name }} on host {{ $labels.ip }} loaded to {{ humanize $value }}%', enabled = 1 WHERE alert_name = 'pon_ports_is_full';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'optical', alert_name = 'rx_signal_deteriorated' , expression = 'avg_over_time(optical_rx[1d:1h]) - avg_over_time(optical_rx[30m]) > 2', `for` = '30m', severity = 'warning', annotation_summary = 'RX signal deteriorated', annotation_description = 'RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', enabled = 1 WHERE alert_name = 'rx_signal_deteriorated';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'device_resources', alert_name = 'sys_cpu_highload' , expression = 'device_resources_cpu_util > 80', `for` = '15m', severity = 'warning', annotation_summary = 'CPU highload', annotation_description = 'CPU on device {{ $labels.ip }} highload, value {{humanize $value}}', enabled = 1 WHERE alert_name = 'sys_cpu_highload';
UPDATE  c_events_alertmanager_rules SET  created_at = '2023-04-20 16:09:26', updated_at = '2023-04-20 16:09:26', group_name = 'system', alert_name = 'system_not_enough_pollers' , expression = 'avg_over_time(system_poller_procs_busy_count[10m]) / avg_over_time(system_poller_procs_all_count[10m]) * 100 >= 99', `for` = '10m', severity = 'warning', annotation_summary = 'System problem', annotation_description = 'Not anough processes for pollers. Current pollers load is  {{ humanize $value }}% (You can increase parameter POLLER_COUNT_PROCS in .env or system configuration)', enabled = 1 WHERE alert_name = 'system_not_enough_pollers';
