"""The real, production alarm rule set, frozen from a live export (see tools/gen_alarm_rule_catalogue.py).

29 rules, read directly from c_events_alertmanager_rules on 2026-09-29. Every expression is the real PromQL
already running in production, character for character, not retyped from memory. Do not edit by hand;
regenerate from a fresh export if the live rules ever change."""
from __future__ import annotations

# (group_name, alert_name, expression, for_duration, severity, audience, isp_focus, reseller_focus,
#  annotation_summary, annotation_description, enabled, internal, legacy_id)
ALARM_RULES: list[tuple[str, str, str, str, str, str | None, str, str, str, str, bool, bool, int]] = [
    ('interfaces', 'iface_increase_in_errors', 'delta(iface_stat_in_errors[15m]) > 30', '10m', 'warning', 'isp', 'secondary', 'muted', 'Errors increased', 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', True, False, 1),
    ('interfaces', 'iface_increase_out_errors', 'delta(iface_stat_out_errors[15m]) > 30', '30m', 'warning', 'isp', 'secondary', 'muted', 'Errors increased', 'Errors increased on {{ $labels.iface_name }} on host {{ $labels.ip }} more than {{ humanize $value }} per 15minutes', True, False, 2),
    ('interfaces', 'interface_is_down', 'device_interface_status{iface_type=~"ETH|FE|GE|TGE|LACP"} == 0 and device_interface_admin_state{iface_type=~"ETH|FE|GE|TGE|LACP"} == 1', '5m', 'info', 'isp', 'primary', 'muted', 'Port down', 'Port {{ $labels.iface_name }} on {{ $labels.ip }} is administratively up but operationally down', True, False, 3),
    ('optical', 'olt_rx_signal_deteriorated', 'avg_over_time(optical_olt_rx[1d:1h]) - avg_over_time(optical_olt_rx[30m]) > 2', '10m', 'warning', 'reseller', 'muted', 'primary', 'OLT RX signal deteriorated', 'OLT RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', True, False, 4),
    ('pon', 'pon_mass_onts_down', 'round(delta(count( (label_replace(device_interface_status{iface_name=~".*:.*"}, "pon_port", "$1", "iface_name", "^(.*):[0-9]{1,4}$") == 0) or (label_replace(device_interface_status{iface_name=~".*:.*"}, "pon_port", "$1", "iface_name", "^(.*):[0-9]{1,4}$") == -2) ) by (dev_id, ip, pon_port)[15m:])) >= 3', '10m', 'warning', 'both', 'secondary', 'primary', 'Several ONTs down on one PON port', 'Three or more ONTs on {{ $labels.pon_port }} at {{ $labels.ip }} went offline or lost signal within fifteen minutes', True, False, 5),
    ('optical', 'rx_signal_deteriorated', 'avg_over_time(optical_rx[1d:1h]) - avg_over_time(optical_rx[30m]) > 2', '30m', 'warning', 'reseller', 'muted', 'primary', 'RX signal deteriorated', 'RX signal deteriorated on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }}', True, False, 6),
    ('device_resources', 'sys_cpu_highload', 'device_resources_cpu_util > 80', '15m', 'warning', 'isp', 'secondary', 'muted', 'CPU highload', 'CPU on device {{ $labels.ip }} highload, value {{humanize $value}}', True, False, 7),
    ('interfaces', 'pon_box_status', 'pon_box_status == 0', '1m', 'info', 'reseller', 'muted', 'secondary', 'PON box down', 'PON box with name {{ $labels.pon_iface }} on device {{ $labels.ip }}, port {{ $labels.pon_iface }} is DOWN', True, False, 10000),
    ('router', 'bgp_session_down', 'router_bgp_session_state_established == 0 and router_bgp_session_state_disabled == 0', '5m', 'warning', 'isp', 'primary', 'muted', 'BGP Session Down', 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} DOWN', True, False, 10001),
    ('router', 'bgp_session_restarted', 'router_bgp_session_uptime < 300 and router_bgp_session_state_established == 1', '1m', 'warning', 'isp', 'secondary', 'muted', 'BGP Session reloaded', 'BGP session with AS num {{ $labels.remote_as }} ({{ $labels.remote_address }}) on router {{ $labels.router_ip }} RELOADED', True, False, 10002),
    ('pinger', 'pinger_host_down', 'pinger_host_status <= 0', '1m', 'warning', 'both', 'primary', 'secondary', 'Device is down by ICMP', 'Device {{ $labels.ip }} is DOWN', True, False, 10003),
    ('pon', 'pon_ports_is_full', 'pon_port_current_onts_count / pon_port_max_onts_count * 100 > 90', '10m', 'warning', 'reseller', 'muted', 'secondary', 'PON port is full', 'Port {{ $labels.iface_name }} on host {{ $labels.ip }} loaded to {{ humanize $value }}%', True, False, 10004),
    ('system', 'system_not_enough_pollers', 'avg_over_time(system_poller_procs_busy_count[10m]) / avg_over_time(system_poller_procs_all_count[10m]) * 100 >= 99', '10m', 'warning', 'operator', 'secondary', 'muted', 'System problem', 'Not anough processes for pollers. Current pollers load is  {{ humanize $value }}% (You can increase parameter POLLER_COUNT_PROCS in .env or system configuration)', True, False, 10005),
    ('interfaces', 'favorite_interface_down', '(device_interface_status == 0 and device_interface_admin_state == 1) * on(iface_id, iface_name, iface_type, ip, dev_id) storage_iface_favorite', '2m', 'warning', 'isp', 'primary', 'muted', 'Marked interface is DOWN', 'Interface {{ $labels.iface_name }} DOWN on host {{ $labels.ip }}', True, False, 10017),
    ('analytics', 'bad_optical_level_olt_rx', 'optical_olt_rx{iface_type="ONU"} > -10 or optical_olt_rx{iface_type="ONU"} < -28', '15m', 'warning', 'reseller', 'muted', 'primary', 'Signal Level Issues', 'The OLT RX signal level on OLT for ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }} has exceeded the limit - {{ humanize $value }}dBm', True, True, 10018),
    ('analytics', 'bad_optical_level_rx', 'optical_rx{iface_type="ONU"} > -10 or optical_rx{iface_type="ONU"} < -28', '15m', 'warning', 'reseller', 'muted', 'primary', 'Signal Level Issues', 'The RX signal level on ONU {{ $labels.iface_name }}, OLT {{ $labels.ip }} has exceeded the limit - {{ humanize $value }}dBm', True, True, 10019),
    ('sensors', 'sensor_test_alert', 'device_sensor{name="Temperature"} > 18', '10m', 'info', 'isp', 'secondary', 'muted', 'High temperature', 'High temp - {{$value}},  on sensor {{$labels.ip}}', True, False, 10020),
    ('sensors', 'sensors_low_battery_level', 'device_sensor{type="analog_line", name="Battery"}  < 44  ', '10m', 'warning', 'isp', 'secondary', 'muted', 'Low battery level', 'Battery voltage {{humanize $value}} on sensor {{$labels.ip}} is very low', True, False, 10021),
    ('sensors', 'sensors_no_power_supply', 'device_sensor{type="power_sensor"} == 0', '5m', 'warning', 'isp', 'secondary', 'muted', 'No power supply', 'No power on sensor {{ $labels.ip }}', True, False, 10022),
    ('links', 'high_link_utilization', 'max_over_time(link_utilization_prc[15m]) > 85', '15m', 'warning', 'isp', 'secondary', 'muted', 'High link utilization', 'Link {{ $labels.src_device_ip }} -> {{ $labels.dest_device_ip }} utilization is too high in one direction - {{ humanize $value }}% ', True, True, 10023),
    ('analytics', 'bad_optical_sfp_rx', 'optical_rx{iface_type != "ONU"} > 5 or optical_rx{iface_type != "ONU"} < -15', '5m', 'warning', 'isp', 'secondary', 'muted', 'Bad SFP signal', 'The RX signal level on SFP {{ $labels.iface_name }}, IP {{ $labels.ip }} has exceeded the limit - {{ humanize $value }}dBm', True, True, 10026),
    ('paths', 'path_down', 'path_state == 0', '2m', 'critical', 'isp', 'primary', 'muted', 'Transport path is down', 'Path {{ $labels.path_name }} ({{ $labels.endpoint_a_name }} -> {{ $labels.endpoint_b_name }}) is down.', True, True, 10027),
    ('paths', 'path_degraded', 'path_state == 0.5', '5m', 'warning', 'isp', 'secondary', 'muted', 'Transport path is degraded', 'Path {{ $labels.path_name }} is up but latency on at least one hop is above the configured threshold.', True, True, 10028),
    ('paths', 'path_group_unprotected', 'path_group_protected == 0 and path_group_up_count > 0', '2m', 'warning', 'isp', 'secondary', 'muted', 'Redundancy lost - group is unprotected', 'Group {{ $labels.group_key }} still carries traffic but has lost redundancy: {{ $labels.group_key }} has {{ $value }} protected state. A further failure will cause an outage.', True, True, 10029),
    ('paths', 'path_group_outage', 'path_group_up_count == 0', '1m', 'critical', 'isp', 'primary', 'muted', 'All paths in group are down', 'Every path in group {{ $labels.group_key }} is down - the destination is unreachable.', True, True, 10030),
    ('links', 'link_down', 'link_status == 0', '2m', 'warning', 'isp', 'primary', 'muted', 'Link down', 'Link between {{ $labels.src_device_name }} {{ $labels.src_iface_name }} and {{ $labels.dest_device_name }} {{ $labels.dest_iface_name }} is down', True, False, 10031),
    ('interfaces', 'mass_interfaces_down', 'round(delta(count(device_interface_status{iface_type=~"ETH|FE|GE|TGE|LACP"} == 0) by (dev_id, ip)[15m:])) >= 3', '5m', 'warning', 'isp', 'primary', 'muted', 'Several ports down at once', 'Three or more ports went down within fifteen minutes on {{ $labels.ip }}', True, False, 10032),
    ('device_resources', 'high_memory_load', 'device_resources_memory_util > 80', '10m', 'warning', 'isp', 'secondary', 'muted', 'High memory load', 'Memory use on {{ $labels.ip }} has been above 80 per cent for ten minutes', True, False, 10033),
    ('pon', 'pon_mass_onts_power_loss', 'round(delta(count( label_replace(device_interface_status{iface_name=~".*:.*"}, "pon_port", "$1", "iface_name", "^(.*):[0-9]{1,4}$") == -1 ) by (dev_id, ip, pon_port)[15m:])) >= 3', '10m', 'info', 'reseller', 'muted', 'secondary', 'Several ONTs lost power on one PON port', 'Three or more ONTs on {{ $labels.pon_port }} at {{ $labels.ip }} reported their own power off within fifteen minutes', True, False, 10034),
]
