"""Device model detection catalogue.

Generated by tools/gen_device_model_catalogue.py from the legacy vendor model files listed in SOURCES there.
Every regex here is the real, unmodified detection rule the legacy PHP ModelCollector uses today — read from
the checked-in YAML, never invented. Do not edit by hand; regenerate."""
from __future__ import annotations

# (vendor_slug, family_slug, key, name, device_type, sysobjectid_pattern, sysdescr_pattern, priority, source_note)
DEVICE_MODELS: list[tuple[str, str, str, str, str, str | None, str | None, int, str]] = [
    ('bdcom', 'bdcom-olt', 'bdcom_gp3600_series', 'BDCOM GP3600 series', 'olt', '^.1.3.6.1.4.1.3320', '.*GP3600', 0, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3612_2te', 'BDCOM P3612-2TE', 'olt', '^.1.3.6.1.4.1.3320.1.2010.0', '^BDCOM.*P3612-2TE.*', 1, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3616_2te', 'BDCOM P3616-2TE', 'olt', '.1.3.6.1.4.1.3320.1.2011.0', '^BDCOM.*P3616-2TE.*', 2, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3608b', 'BDCOM P3608B', 'olt', '^.1.3.6.1.4.1.3320', '^BDCOM.*P3608B.*', 3, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p36xx_series', 'BDCOM P36xx series', 'olt', '^.1.3.6.1.4.1.3320', '^BDCOM.*?P36.*', 4, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3310c', 'BDCOM P3310C', 'olt', '^.1.3.6.1.4.1.3320.1.294.0$', '^BDCOM.*P3310C.*', 5, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3310d', 'BDCOM P3310D', 'olt', '^.1.3.6.1.4.1.3320.1.441.0$', '^BDCOM.*P3310D.*', 6, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-olt', 'bdcom_p3310b', 'BDCOM P3310B', 'olt', '^.1.3.6.1.4.1.3320.*', '^BDCOM.*P3310B.*', 7, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s5612', 'BDCOM S5612', 'switch', '^.1.3.6.1.4.1.3320.1.283.0', '^BDCOM.*S5612', 8, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s1000_series', 'BDCOM S1000 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS10\\d\\d', 9, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s2200_series', 'BDCOM S2200 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS22\\d\\d', 10, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s2500_series', 'BDCOM S2500 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS25\\d\\d', 11, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s2900_series', 'BDCOM S2900 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS29\\d\\d', 12, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s3700_series', 'BDCOM S3700 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS37\\d\\d', 13, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s3900_series', 'BDCOM S3900 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS39\\d\\d', 14, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s5600_series', 'BDCOM S5600 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS56\\d\\d', 15, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s5700_series', 'BDCOM S5700 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS57\\d\\d', 16, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s5800_series', 'BDCOM S5800 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS58\\d\\d', 17, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s6500_series', 'BDCOM S6500 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS65\\d\\d', 18, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s8500_series', 'BDCOM S8500 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS85\\d\\d', 19, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_s9500_series', 'BDCOM S9500 series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS95\\d\\d', 20, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_ies_series', 'BDCOM IES industrial series', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bIES\\d{3,4}', 21, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_legacy_switch', 'BDCOM legacy S2xxx/S3xxx switch', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\bS(2008|2026|2108|2116|3224|3448|3512)', 22, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('bdcom', 'bdcom-switch', 'bdcom_switch_generic', 'BDCOM switch (generic)', 'switch', '^.1.3.6.1.4.1.3320', '^BDCOM.*\\b(S|IES)\\d{3,4}', 23, 'vendor/meklis/switcher-core/configs/models/BDcom.yml'),
    ('huawei', 'huawei-olt', 'huawei_ma5680t', 'Huawei MA5680T', 'olt', '.1.3.6.1.4.1.2011.2.115', '^Huawei*', 0, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('huawei', 'huawei-olt', 'huawei_ma5603t', 'Huawei MA5603T', 'olt', '1.3.6.1.4.1.2011.2.123', '^Huawei*', 1, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('huawei', 'huawei-olt', 'huawei_ma5608t', 'Huawei MA5608T', 'olt', '1.3.6.1.4.1.2011.2.248', '^Huawei*', 2, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('huawei', 'huawei-olt', 'huawei_ma5683t', 'Huawei MA5683T', 'olt', '.1.3.6.1.4.1.2011.2.133', '^Huawei*', 3, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('huawei', 'huawei-olt', 'huawei_smart_ax', 'Huawei MA56xx/MA58xx series', 'olt', '.1.3.6.1.4.1.2011.2', '^Huawei*', 4, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('huawei', 'huawei-olt', 'huawei_ma5801', 'Huawei MA5801', 'olt', '.1.3.6.1.4.1.2011.2.381', '^Huawei*', 5, 'vendor/meklis/switcher-core/configs/models/HuaweiOLT.yml'),
    ('zte', 'zte-c-olt', 'zte_c320', 'ZTE C320 (FW 2.1)', 'olt', '.*\\.1001\\.320\\.2\\.1$', 'ZTE', 0, 'vendor/meklis/switcher-core/configs/models/ZTE-C-series.yml'),
    ('zte', 'zte-c-olt', 'zte_c300', 'ZTE C300 (FW 2.1)', 'olt', '1082.1001.300.2.1$', 'C300', 1, 'vendor/meklis/switcher-core/configs/models/ZTE-C-series.yml'),
    ('zte', 'zte-c-olt', 'zte_c320_fw_1_2', 'ZTE C320 (FW 1.2)', 'olt', '.*\\.320.1.2$', 'ZTE', 2, 'vendor/meklis/switcher-core/configs/models/ZTE-C-series.yml'),
    ('zte', 'zte-c-olt', 'zte_c300_fw_1_2', 'ZTE C300 (FW 1.2)', 'olt', '.*\\.1015.300.3.1$', 'ZTE', 3, 'vendor/meklis/switcher-core/configs/models/ZTE-C-series.yml'),
    ('zte', 'zte-c-olt', 'zte_zxpon_olt_series', 'ZTE C600 series', 'olt', '.3902.1082.1001', 'ZTE.*', 4, 'vendor/meklis/switcher-core/configs/models/ZTE-C-series.yml'),
]
