<?php


namespace WCAA\Console\Tests;


use DI\Annotation\Inject;
use SwitcherCore\Config\ModelCollector;
use SwitcherCore\Config\OidCollector;
use SwitcherCore\Switcher\Console\ConsoleInterface;
use SwitcherCore\Switcher\CoreConnector;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;
use WCAA\Console\AbstractCommand;
use WCAA\Exceptions\SupportException;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\UserStorage;
use WCAA\SwitcherCore\Request;
use WCAA\SwitcherCore\SwitcherCore;

class TestSnmpWalk extends AbstractCommand
{
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $devStorage;
    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    function configure()
    {
        $this->setName("test:snmpwalk")
            ->setDescription("Run snmpwalk command by IP")
            ->addArgument("device_ip", InputArgument::REQUIRED, "Device IP")
            ->addArgument("oid", InputArgument::OPTIONAL, "OID ident. Can be numeric or name from switcher-core", '.1')
        ;
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @Inject
     * @var SwitcherCore
     */
    protected $swc;


    function execute(InputInterface $input, OutputInterface $output)
    {
        $device = $this->devStorage->getByIp($input->getArgument("device_ip"));
        $oid = $input->getArgument("oid");
        if(!preg_match('/^(\.1|1)/', $oid)) {
            $oid = $this->swc
                ->getCore($device)
                ->getContainer()
                ->get(OidCollector::class)
                ->getOidByName($oid)
                ->getOid();
            ;
        }
        $port = 161;
        if(isset($device->getAccess()->getParams()['sw_core_connection']['snmp_port'])) {
            $port = $device->getAccess()->getParams()['sw_core_connection']['snmp_port'];
        }
        if(isset($device->getParams()['sw_core_connection']['snmp_port'])) {
            $port = $device->getParams()['sw_core_connection']['snmp_port'];
        }

        $command = "snmpwalk -r3 -t3 -v2c -On -Cc -c {$device->getAccess()->getPublicCommunity()} {$device->getIp()}:{$port} {$oid}";
        $this->runCommand($command);
        return self::SUCCESS;
    }

    public function runCommand($cmd)
    {
        if($this->output->isVerbose()) {
            $this->output->writeln($cmd);
        }
        $process = Process::fromShellCommandline($cmd);
        $process->setTimeout(0);
        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                echo 'ERR: ' . $buffer;
            } else {
                echo $buffer;
            }
        });
        // executes after the command finishes
        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }
        if($err = $process->getErrorOutput()) {
            throw new SupportException("Error execute command '{$cmd}': {$err}");
        };
    }
}