<?php


namespace WCAA\Console\Tests;


use DI\Annotation\Inject;
use SwitcherCore\Switcher\Console\ConsoleInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use WCAA\Console\AbstractCommand;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\UserStorage;
use WCAA\SwitcherCore\Request;
use WCAA\SwitcherCore\SwitcherCore;

class TestSwitcherCoreCallModules extends AbstractCommand
{
    /**
     * @Inject
     * @var SwitcherCore
     */
    protected $swc;
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $devStorage;
    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    function configure()
    {
        $this->setName("test:switcher-core:call")
            ->setDescription("Allow to test switcher core call by device group. ")
            ->addUsage("wca test:switcher-core:call  interfaces_list -f [0].name")
            ->addArgument("module", InputArgument::REQUIRED, "Module name")
            ->addArgument("arguments", InputArgument::IS_ARRAY, "Arguments. For example interface=pon0/1/1")
            ->addOption('show-field', 'f', InputOption::VALUE_OPTIONAL, 'Show some field in result. Must be as twig definition', '')
            ->addOption("source", "s", InputOption::VALUE_OPTIONAL, "Source to use. Can be device(every call from device),store(every call from store) and cache(if not found in store - can be call from device)", 'device')
            ->addOption("group-id", "g", InputOption::VALUE_OPTIONAL, "Group ID to call", '')
            ->addOption("console", "c", InputOption::VALUE_NEGATABLE, "Show console output", false);
        parent::configure(); // TODO: Change the autogenerated stub
    }

    function execute(InputInterface $input, OutputInterface $output)
    {
        $user = $this->userStorage->getById(-2);
        $this->swc->setUser($user);
        $arguments = [];
        foreach ($input->getArgument('arguments') as $argkv) {
            list($key, $value) = @explode("=", $argkv);
            $arguments[$key] = $value;
        }
        if ($groupId = $this->input->getOption("group-id")) {
            $devices = $this->devStorage->fetchByDeviceGroup(new DeviceGroup($groupId));
        } else {
            $devices = $this->devStorage->fetchAll();
        }
        foreach ($devices as $device) {
            $request = (new Request())
                ->setDevice($device)
                ->setModule($input->getArgument('module'))
                ->setArguments($arguments);
            if ($output->isVerbose()) {
                $output->writeln("<info>=================================================================================</info>");
                $output->writeln(" <comment>Start calling from device {$device->getName()} ({$device->getIp()})</comment>");
                $output->writeln("   Module: <info>{$input->getArgument('module')}</info>");
                $output->writeln("   Arguments: <info>" . json_encode($arguments) . "</info>");
                $output->writeln("<info>=================================================================================</info>");
            }
            $response = null;
            $start = microtime(true);
            switch ($input->getOption('source')) {
                case 'device':
                    $response = $this->swc->fromDevice([$request]);
                    break;
                case 'store':
                    $response = $this->swc->fromStore([$request]);
                    break;
                case 'cache':
                    $response = $this->swc->fromCache([$request]);
                    break;
                default:
                    throw new \InvalidArgumentException("Invalid source {$input->getOption('source')}");
            }
            $time = microtime(true) - $start;
            $response = $response->getFirstByModule($input->getArgument('module'));
            if ($response->getError()) {
                if ($output->isVerbose()) {
                    $output->writeln("<error>
   DEVICE: {$device->getIp()}
   Error call module with message: {$response->getError()['message']}
</error>
");
                    $output->writeln("
In: {$response->getError()['file']}:{$response->getError()['line']}
            
            ");
                    $output->writeln("Exception trace:");
                    $output->writeln($response->getError()['trace']);
                } else {
                    $error = str_replace(["\n", "\r"], '; ', $response->getError()['message']);
                    $error = substr($error, 0,  150 ) . '...';
                    $output->writeln("<error>{$device->getIp()}({$device->getModel()->getKey()}): $error</error>");
                }
            } else {
                if ($output->isVerbose()) {
                    $output->writeln(json_encode($response->getData(), JSON_PRETTY_PRINT | JSON_NUMERIC_CHECK | JSON_UNESCAPED_UNICODE));
                    $output->writeln("<info>=================================================================================</info>");
                    $output->writeln("<info>\tSpent time: " . round($time, 4) . " sec</info>");
                    $output->writeln("<info>=================================================================================</info>");
                } else if($fieldDefinition = $input->getOption('show-field')) {
                    $val = getArrayElementByKey($response->getData(), $fieldDefinition);
                    $output->writeln("{$device->getIp()}({$device->getModel()->getKey()}): " . json_encode($val, JSON_PRETTY_PRINT));
                } else {
                    $output->writeln("{$device->getIp()}({$device->getModel()->getKey()}): No error");
                }

            }

            if ($input->getOption('console') && $output->isVerbose()) {
                /**
                 * @var ConsoleInterface $telnet
                 */
                $output->writeln("<comment>console output:</comment>");
                $output->writeln("<comment>-------------------------------------------------------------------------------</comment>");
                $telnet = $this->swc->getCore($device)->getContainer()->get(ConsoleInterface::class);
                $output->writeln($telnet->getGlobalBuffer());
                $output->writeln("<comment>-------------------------------------------------------------------------------</comment>");

            }
        }

        return self::SUCCESS;
    }
}