<?php
declare(strict_types=1);

namespace WCAA\Api\Actions;

use IPv4\SubnetCalculator;
use Monolog\Logger;
use Slim\Exception\HttpForbiddenException;
use WCAA\App;
use WCAA\Infrastructure\SystemActionLogger;
use WCAA\Models\SystemAction;
use WCAA\Models\User\User;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use WCAA\Storage\SystemActionsStorage;

abstract class PrivateAction extends Action
{

    /**
     * @var bool
     */
    protected $forbiddenInDemo = false;

    public function isForbiddenInDemo(): bool
    {
        return $this->forbiddenInDemo;
    }

    public function setForbiddenInDemo(bool $forbiddenInDemo): PrivateAction
    {
        $this->forbiddenInDemo = $forbiddenInDemo;
        return $this;
    }

    private function getUserIp(Request $request) {
        $remoteIPs = $request->getHeader('WCA-Real-Ip');
        $ipAddr = $_SERVER['REMOTE_ADDR'];
        if($remoteIPs) {
            $ipAddr = $remoteIPs[0];
        }
        $proxyConf = App::getInstance()->conf('api.proxy');
        if ($proxyConf['enabled']) {
            $proxiedAddress = $request->getHeader($proxyConf['real_ip_header']);
            if ($proxiedAddress && is_array($proxiedAddress) && count($proxiedAddress) > 0) {
                $ipAddr = $proxiedAddress[0];
            } else if($proxiedAddress && is_string($ipAddr)) {
                $ipAddr = $proxiedAddress;
            }
        }
        return $ipAddr;
    }
    function isDisableDemoFor(string $ip)
    {
        if (in_array($ip, App::getInstance()->conf('demo.disable_for'))) {
            return true;
        }
        foreach (array_filter(App::getInstance()->conf('demo.disable_for'), function ($e) {
            return strpos($e, "/");
        }) as $network) {
            list($neth, $cidr) = explode("/", $network);
            if ((new SubnetCalculator($neth, $cidr))->isIPAddressInSubnet($ip)) {
                return true;
            }
        }
        return false;
    }

    function isAllowedByDemoRules(Request $request)
    {
        if($this->isDisableDemoFor($this->getUserIp($request))) {
            return true;
        }
        if (App::getInstance()->conf('demo.enabled') && !$this->forbiddenInDemo) {
            return true;
        } elseif (App::getInstance()->conf('demo.enabled') && $this->forbiddenInDemo) {
            return  false;
        }
        return true;
    }

    /**
     * @var User
     */
    protected $user;

    /**
     * @Inject
     * @var SystemActionLogger
     */
    protected $actionLog;


     function __construct(Logger $logger)
     {
         parent::__construct($logger);
     }
     function __invoke(Request $request, Response $response, $args): Response
     {
         $this->user = $request->getAttribute('AUTH_USER');
         if(!$this->isAllowedByDemoRules($request)) {
            throw new HttpForbiddenException($request, "This action forbid in DEMO mode");
         }
         return parent::__invoke($request, $response, $args); // TODO: Change the autogenerated stub
     }

     function addActionSuccess($actionName, $message,  $meta = [], $device = null) {
         return $this->actionLog
             ->success(
                 $actionName,
                 $message,
                 $meta,
                 $device,
                 $this->user
             );
     }
     function addActionFailed($actionName, $message, \Throwable $error = null, $meta = [], $device = null) {
         if($error !== null) {
             $meta['error'] = [
               'message' => $error->getMessage(),
               'breakpoint' => $error->getFile() . ":" . $error->getLine(),
               'trace' => $error->getTraceAsString(),
             ];
         }
         return $this->actionLog->failed(
             $actionName,
             $message,
             $meta,
             $device,
             $this->user
         );
     }

    function getDeviceGroupsIdsFromUser()
    {
        $groupIds = [];
        foreach ($this->user->getDeviceGroups() as $group) {
            $groupIds[] = $group->getId();
        }
        return $groupIds;
    }
}
