<?php

namespace WCC\Events\Storage;

use WCAA\Infrastructure\Paginator\DbPagination;
use WCAA\Infrastructure\Paginator\Paginator;
use WCAA\Models\Devices\Device;
use WCAA\Models\User\User;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\UserStorage;
use WCC\Events\Models\AlertmanagerRule;
use WCC\Events\Models\Event;
use WCC\Events\Models\EventFilter;

class AlertmanagerRulesStorage extends AbstractStorage
{
    protected $tableName = 'c_events_alertmanager_rules';

    /**
     * @return AlertmanagerRule[]
     * @throws \Exception
     */
    function fetchAll() {
        $rules = [];
        foreach ($this->pdo->query("SELECT id FROM `{$this->tableName}` order by `internal`,  alert_name") as $id) {
            $rules[] = $this->fill(new AlertmanagerRule($id['id']));
        }
        return $rules;
    }

    function getAlertByAlertName($name)
    {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE alert_name = :alert_name");
        $psth->execute(['alert_name' => $name]);
        return $this->fill(new AlertmanagerRule($psth->fetch()['id']));
    }

    /**
     * @param AlertmanagerRule $object
     * @return AlertmanagerRule
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true) {
        $object = parent::fill($object);
        $object->enabled = $object->enabled == 1 ? true : false;
        $object->internal = $object->internal == 1 ? true : false;
        return  $object;
    }

    /**
     * @param AlertmanagerRule
     * @return AlertmanagerRule
     */
    function update($object)
    {
        $object->enabled = $object->enabled ? 1 : 0;
        $object->internal = $object->internal ? 1 : 0;
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $object
     * @return AlertmanagerRule[]
     * @throws \Exception
     */
    function updateAll(array $objects) {
        $this->pdo->beginTransaction();
        foreach ($this->fetchAll() as $obj) {
            $this->delete($obj);
        }
        foreach ($objects as $obj) {
            $this->add($obj);
        }
        $this->pdo->commit();
        return $this->fetchAll();
    }

    /**
     * @param AlertmanagerRule
     * @return AlertmanagerRule
     */
    function add($object)
    {
        $object->enabled = $object->enabled ? 1 : 0;
        $object->internal = $object->internal ? 1 : 0;
        return parent::add($object); // TODO: Change the autogenerated stub
    }


}
