<?php

namespace WCC\Events\Storage;

use WCAA\Infrastructure\Paginator\DbPagination;
use WCAA\Infrastructure\Paginator\Paginator;
use WCAA\Models\Devices\Device;
use WCAA\Models\User\User;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\UserStorage;
use WCC\Events\Models\Event;
use WCC\Events\Models\EventFilter;

class EventsStorage extends AbstractStorage
{
    protected $tableName = 'c_events';

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    /**
     * @param Event $object
     * @return Event
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        if ($obj->device_id) $obj->device = $this->deviceStorage->getById($obj->device_id);
        if ($obj->creator_id) $obj->creator = $this->userStorage->getById($obj->creator_id);
        if ($obj->resolved_by_id) $obj->resolved_by = $this->userStorage->getById($obj->resolved_by_id);
        return $obj;
    }

    /**
     * @param Event $object
     * @param $fillArr
     * @return Event
     */
    public function fillByArr($object, $fillArr = [], $fillChildren = true)
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        if ($object->device_id) $obj->device = $this->deviceStorage->getById($object->device_id);
        if ($object->creator_id) $obj->creator = $this->userStorage->getById($object->creator_id);
        if ($object->resolved_by_id) $obj->resolved_by = $this->userStorage->getById($object->resolved_by_id);

        return $obj;
    }

    /**
     * @param Event $object
     * @return Event
     */
    public function add($object)
    {
        $object->creator_id = $object->getCreator()->getId();
        if ($object->getResolvedBy()) $object->resolved_by_id = $object->getResolvedBy()->getId();
        if ($object->getDevice()) $object->device_id = $object->device->getId();

        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param Event $object
     * @return Event
     */
    public function update($object)
    {
        $object->creator_id = $object->getCreator()->getId();
        if ($object->getResolvedBy()) $object->resolved_by_id = $object->getResolvedBy()->getId();
        if ($object->getDevice()) $object->device_id = $object->device->getId();

        return parent::update($object); // TODO: Change the autogenerated stub
    }

    public function getByEventFilter(EventFilter $filter, ?DbPagination $paginator)
    {
        $where = " 1 = 1";
        $order = "order by if(resolved_at is null, 1, 0) desc, severity , id desc";
        $limit = "LIMIT 50";
        $variables = [];

        if($filter->getUser()) {
            if($filter->getUser()->getRole()->getId() > 0 && !in_array('events_see_all', $filter->getUser()->getRole()->getPermissions())) {
                $deviceGroupIds = [-10];
                foreach ($filter->getUser()->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = $gr->getId();
                }
                $where .= " and device_id in (SELECT id FROM devices WHERE group_id in (".join(",", $deviceGroupIds)."))";
            }
        }


        if ($filter->getName()) {
            $where .= " and name = ?";
            $variables[] = $filter->getName();
        }
        if ($filter->getDevice()) {
            $where .= " and device_id = ? ";
            $variables[] = $filter->getDevice()->getId();
        }
        if ($filter->getKey()) {
            $where .= " and `key` = ?";
            $variables[] = $filter->getKey();
        }
        if ($filter->getOnlyNotResolved()) {
            $where .= " and `resolved_at` is null ";
        }
        if ($filter->getSeverity()) {
            $where .= " and `severity` = ? ";
            $variables[] = $filter->getSeverity();
        }
        if ($names = $filter->getNames()) {
            $placeholders = join(",", array_fill(0, count($names), '?'));
            $where .= " and `name` in ({$placeholders}) ";
            foreach ($names as $name) {
                $variables[] = $name;
            }
        }

        // Keep only the alarms that rank a given way on a given console. The
        // column name is built from a fixed whitelist rather than the caller's
        // string, and the tiers are bound, so nothing here reaches the
        // statement text unchecked.
        if ($filter->getFocusConsole() && $filter->getFocusTiers()) {
            $columns = ['isp' => 'isp_focus', 'reseller' => 'reseller_focus'];
            $column = $columns[$filter->getFocusConsole()] ?? null;
            $tiers = array_values(array_intersect(
                $filter->getFocusTiers(),
                ['primary', 'secondary', 'muted']
            ));
            if ($column && $tiers) {
                $placeholders = join(",", array_fill(0, count($tiers), '?'));
                $where .= " and name in (SELECT alert_name FROM c_events_alertmanager_rules WHERE {$column} in ({$placeholders})) ";
                foreach ($tiers as $tier) {
                    $variables[] = $tier;
                }
            }
        }

        if ($filter->getStart() && $filter->getStop()) {
            $where .= " and (created_at between ? and ?) ";
            $variables[] = $filter->getStart();
            $variables[] = $filter->getStop();
        }

        if ($filter->getLabels()) {
            $whereLabels = [];
            foreach ($filter->getLabels() as $key => $value) {
                //The JSON path is part of the statement text, so only a plain label
                //name is accepted - anything else is dropped rather than escaped.
                if (!preg_match('/^[A-Za-z0-9_]+$/', (string)$key)) {
                    continue;
                }
                $whereLabels[] = "labels->'\$.{$key}' = ?";
                $variables[] = is_numeric($value) ? (float)$value : $value;
            }
            if ($whereLabels) {
                $where .= " and (" . join(" and ", $whereLabels) . ") ";
            }
        }
        if ($paginator) {
            if ($paginator->getWhereQuery()) {
                $where .= " and concat(description, ':', name, ':', labels) like ?";
                $variables[] = '%' . strtolower($paginator->getWhereQuery()) . '%';
            }
            $psth = $this->pdo->prepare("SELECT count(*) c FROM c_events WHERE $where");
            $psth->execute($variables);
            $paginator->setTotalRecords($psth->fetch()['c']);
            if ($paginator->getPaginator()->getOrderBy()) {
                $order = $paginator->getOrderQuery();
            }
            $limit = $paginator->getLimitsQuery();
        }
        $psth = $this->pdo->prepare("SELECT * FROM c_events WHERE $where $order $limit");
        $psth->execute($variables);
        /**
         * @var $objects Event[]
         */
        $objects = [];
        foreach ($psth->fetchAll() as $elem) {
            $objects[] = $this->fillByArr(new Event(), $elem, true);
        }

        if ($paginator) {
            $paginator->setRecords($objects);
        }
        return $objects;
    }

    /**
     * @param $name
     * @param Device|null $device
     * @param $labels
     * @param $key
     * @return Event[]
     */
    /**
     * Every open event, flat, for grouping into incidents.
     *
     * getByEventFilter() pages at fifty, which is right for a list and wrong
     * for grouping — you cannot tell that forty ONTs share a PON port by
     * looking at the first fifty rows of a thousand. This returns the columns
     * the grouper needs and nothing else, under the same device-group scoping
     * and the same focus filter the list uses.
     *
     * @return array raw rows: id, name, severity, device_id, labels, created_at
     */
    public function getOpenForGrouping(EventFilter $filter, int $limit = 5000): array
    {
        $limit = max(1, min(20000, $limit));
        $where = " resolved_at is null ";
        $variables = [];

        if ($filter->getUser()) {
            if ($filter->getUser()->getRole()->getId() > 0
                && !in_array('events_see_all', $filter->getUser()->getRole()->getPermissions())) {
                $deviceGroupIds = [-10];
                foreach ($filter->getUser()->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = (int)$gr->getId();
                }
                $where .= " and device_id in (SELECT id FROM devices WHERE group_id in (" . join(",", $deviceGroupIds) . ")) ";
            }
        }
        if ($filter->getDevice()) {
            $where .= " and device_id = ? ";
            $variables[] = $filter->getDevice()->getId();
        }
        if ($filter->getFocusConsole() && $filter->getFocusTiers()) {
            $columns = ['isp' => 'isp_focus', 'reseller' => 'reseller_focus'];
            $column = $columns[$filter->getFocusConsole()] ?? null;
            $tiers = array_values(array_intersect($filter->getFocusTiers(), ['primary', 'secondary', 'muted']));
            if ($column && $tiers) {
                $placeholders = join(",", array_fill(0, count($tiers), '?'));
                $where .= " and name in (SELECT alert_name FROM c_events_alertmanager_rules WHERE {$column} in ({$placeholders})) ";
                foreach ($tiers as $tier) {
                    $variables[] = $tier;
                }
            }
        }

        $psth = $this->pdo->prepare(
            "SELECT id, name, severity, device_id, labels, created_at
             FROM c_events WHERE {$where} ORDER BY created_at ASC LIMIT {$limit}"
        );
        $psth->execute($variables);
        return $psth->fetchAll();
    }

    public function getNotResolvedBy($name = '', Device $device = null, $labels = [], $key = '')
    {
        $labelHash = '';
        if ($labels) {
            ksort($labels);
            $labelHash = md5(json_encode($labels));
        }
        $where = "`resolved_at` is null";
        $variables = [];
        if ($name) {
            $where .= " and name = ?";
            $variables[] = $name;
        }
        if ($device) {
            $where .= " and device_id = ? ";
            $variables[] = $device->getId();
        }
        if ($labelHash) {
            $where .= " and (`key` = ? or `key` = ?) ";
            $variables[] = $labelHash;
            $variables[] = $key;
        }
        if ($key) {
            $where .= " and `key` = ?";
            $variables[] = $key;
        }
        $psth = $this->pdo->prepare("SELECT * FROM c_events WHERE $where order by id desc");
        $psth->execute($variables);
        $objects = [];
        foreach ($psth->fetchAll() as $elem) {
            $objects[] = $this->fillByArr(new Event(), $elem);
        }
        return $objects;
    }

    /**
     * @param $name
     * @param Device|null $device
     * @param $labels
     * @param $key
     * @return bool
     */
    public function isNotResolvedExist($name = '', Device $device = null, $labels = [], $key = '')
    {
        $labelHash = '';
        if ($labels) {
            ksort($labels);
            $labelHash = md5(json_encode($labels));
        }
        $where = "`resolved_at` is null";
        $variables = [];
        if ($name) {
            $where .= " and name = ?";
            $variables[] = $name;
        }
        if ($device) {
            $where .= " and device_id = ? ";
            $variables[] = $device->getId();
        }
        if ($labelHash) {
            $where .= " and (`key` = ? or `key` = ?) ";
            $variables[] = $labelHash;
            $variables[] = $key;
        }
        if ($key) {
            $where .= " and `key` = ?";
            $variables[] = $key;
        }
        $psth = $this->pdo->prepare("SELECT id FROM c_events WHERE $where order by id desc");
        $psth->execute($variables);

        return $psth->rowCount() > 0;
    }

    /**
     * @param $id
     * @return Event
     */
    function getById($id)
    {

        return $this->fill(new Event($id));
    }

    function getSeverityStat($notResolved = true, User $user = null)
    {
        $where = " 1 = 1 ";
        if ($notResolved) {
            $where .= " and resolved_at is null ";
        }
        if($user) {
            if($user->getRole()->getId() > 0 && !in_array('events_see_all', $user->getRole()->getPermissions())) {
                $deviceGroupIds = [-100];
                foreach ($user->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = $gr->getId();
                }
                $where .= " and device_id in (SELECT id FROM devices WHERE group_id in (".join(",", $deviceGroupIds)."))";
            }
        }

        $query = "SELECT count(*) count, severity
                FROM c_events
                WHERE $where
                GROUP BY  severity";
        $resp = [
            'INFO' => 0,
            'WARNING' => 0,
            'CRITICAL' => 0,
        ];
        foreach ($this->pdo->query($query)->fetchAll() as $elem) {
            $resp[$elem['severity']] = (int)$elem['count'];
        }
        return $resp;
    }

    function getStatByEventName($notResolved = true, User $user = null)
    {
        $where = " 1 = 1 ";
        if ($notResolved) {
            $where .= " and resolved_at is null ";
        }
        if($user) {
            if($user->getRole()->getId() > 0 && !in_array('events_see_all', $user->getRole()->getPermissions())) {
                $deviceGroupIds = [-100];
                foreach ($user->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = $gr->getId();
                }
                $where .= " and device_id in (SELECT id FROM devices WHERE group_id in (".join(",", $deviceGroupIds)."))";
            }
        }

        $query = "SELECT count(*) count, name, severity
                FROM c_events
                WHERE $where
                GROUP BY  name,severity
                order by 3,1
                ";
        $resp = [];
        foreach ($this->pdo->query($query)->fetchAll() as $elem) {
            $key = $elem['name'];

            $resp[] = [
                'name' => $map[$key] ?? $key,
//                'name' => $this->getAnnotationsMap()[$elem['name']],
                'severity' => $elem['severity'],
                'count' => (int)$elem['count'],
            ];
        }
        return $resp;
    }

    function getEventNames()
    {
        $psth = $this->pdo->query("SELECT alert_name name, annotation_summary annotation
FROM c_events_alertmanager_rules WHERE alert_name in (SELECT distinct name
                                                      FROM c_events
                                                      )
order by 1");
        $resp = [];
        foreach ($psth->fetchAll() as $r) {
            $resp[] = $r;
        }
        return $resp;
    }
    protected $_keys = [];
    function getAnnotationsMap()
    {
        if($this->_keys) {
            return $this->_keys;
        }
        $psth = $this->pdo->query("SELECT `alert_name` `key`, annotation_summary name FROM  c_events_alertmanager_rules order by 1");
        $resp = [];
        foreach ($psth->fetchAll() as $r) {
            $resp[$r['key']] = $r['name'];
        }
        $this->_keys = $resp;
        return $resp;
    }

    /**
     * @param $days
     * @return Event[]
     */
    function getForRetentionByDays($days, $limit = 10000)
    {
        $psth = $this->pdo->prepare("SELECT *
FROM c_events
WHERE created_at <= NOW() - INTERVAL ? DAY and resolved_at is not null limit ?");
        $psth->execute([$days, $limit]);
        $data = [];
        foreach ($psth->fetchAll() as $d) {
            $data[] = $this->fillByArr(new Event(), $d);
        }
        return $data;
    }
}
