<?php


namespace WCAA\Infrastructure\CacheSystems;


use Monolog\Logger;
use WCAA\App;
use WCAA\Interfaces\CacheInterface;

class MemCacheSwitcherCore extends MemCache implements \SwitcherCore\Switcher\CacheInterface
{
    public function get($key, $cache_cb = null, $flags = null)
    {
        return parent::get("SCL:" . $key);
    }

    public function set($key, $value, $timeout = 0, $udf_flags = 0)
    {
        return parent::set("SCL:" . $key, $value, $timeout); // TODO: Change the autogenerated stub
    }

    public function isExist($key)
    {
        return $this->get("SCL:" . $key) !==  null;
    }

}