<?php


namespace WCAA\Infrastructure\CacheSystems;


use Monolog\Logger;
use WCAA\App;
use WCAA\Interfaces\CacheInterface;

class MemCache extends \Memcached implements CacheInterface
{
    public function __construct($server = '127.0.0.1', $port = 11211)
    {
        parent::__construct();
        $this->addServer($server, $port);
    }

    function delete($key, $time = 0)
    {
        parent::delete($key, $time); // TODO: Change the autogenerated stub
        parent::flushBuffers();
    }

    public function get($key, $cache_cb = null, $flags = null)
    {
        $value = parent::get($key);
        $code = parent::getResultCode();
        if ($code == \Memcached::RES_DELETED) {
            return  null;
        }
        if ($code == \Memcached::RES_SUCCESS) {
            return  $value;
        }
        return  null;
    }

    public function set($key, $value, $timeout = 0, $udf_flags = 0)
    {
        parent::set($key, $value, $timeout); // TODO: Change the autogenerated stub
        $code = parent::getResultCode();
        if($code !== \Memcached::RES_SUCCESS) {
            throw new \MemcachedException(parent::getResultMessage());
        }
        parent::flushBuffers();
        return $this;
    }
    public function flush($delay = 0)
    {
        parent::flush($delay); // TODO: Change the autogenerated stub
        return $this;
    }

    public function isExist($key)
    {
        return parent::get($key) !==  null;
    }

    function deleteByRegex($mask)
    {
        $keys = array_filter($this->getAllKeys(), function ($e) use ($mask) {
            return preg_match($mask, $e);
        });
        if($keys) {
            parent::deleteMulti($keys, 0);
        }

        parent::flushBuffers();
        return $this;
    }
}
