<?php


namespace WCAA\Infrastructure\CacheSystems;


use WCAA\Interfaces\CacheInterface;

class PhpCacheSwitcherCore extends PhpCache implements  \SwitcherCore\Switcher\CacheInterface
{
    public function get($key, $cache_cb = null, $flags = null)
    {
        return parent::get("SwitcherCore:" . $key);
    }

    public function set($key, $value, $timeout = 0, $udf_flags = 0)
    {
        return parent::set("SwitcherCore:" . $key, $value, $timeout); // TODO: Change the autogenerated stub
    }

    public function isExist($key)
    {
        return $this->get("SwitcherCore:" . $key) !==  null;
    }
}