global:
  resolve_timeout: 30s

route:
  receiver: 'wca'
  group_wait: 1s
  group_interval: 1s
  group_by: ['...']
  repeat_interval: 1h
receivers:
  - name: "wca"
    webhook_configs:
      - url: 'http://wca-nginx/api/v1/system/webhook/alertmanager'
        send_resolved: true
