max_execution_time=180
display_errors=1
memory_limit=1024M

[xdebug]
xdebug.mode=off
xdebug.default_enable=0
xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.profiler_enable=0

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.max_accelerated_files=32531
opcache.memory_consumption=512
opcache.interned_strings_buffer=16

#Test preloading
#opcache.preload_user=www-data
#opcache.preload=/www/app/init.php

