<?php


namespace WCAA\Models\Devices;


use WCAA\App;
use WCAA\Models\AbstractModel;

class DeviceInterfaceHistory extends AbstractModel
{

    /**
     * @morm
     * @morm string
     */
    protected $up;

    /**
     * @morm
     * @morm string
     */
    protected $down;

    /**
     * @morm
     * @var string
     */
    protected $down_reason = '';

    /**
     * @morm
     * @prop.display=no
     * @var int
     */
    protected $interface_id;

    /**
     * @var DeviceInterface
     */
    protected $interface = null;

    /**
     * @return mixed
     */
    public function getUp()
    {
        return $this->up;
    }

    /**
     * @param mixed $up
     * @return DeviceInterfaceHistory
     */
    public function setUp($up)
    {
        $this->up = $up;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getDown()
    {
        return $this->down;
    }

    /**
     * @param mixed $down
     * @return DeviceInterfaceHistory
     */
    public function setDown($down)
    {
        $this->down = $down;
        return $this;
    }

    public function getDownReason(): string
    {
        return $this->down_reason;
    }

    public function setDownReason(string $down_reason): DeviceInterfaceHistory
    {
        $this->down_reason = $down_reason;
        return $this;
    }

    public function getInterface(): ?DeviceInterface
    {
        return $this->interface;
    }

    public function setInterface(?DeviceInterface $interface): DeviceInterfaceHistory
    {
        $this->interface = $interface;
        return $this;
    }

    public function getInterfaceId(): int
    {
        return $this->interface_id;
    }

    public function setInterfaceId(int $interface_id): DeviceInterfaceHistory
    {
        $this->interface_id = $interface_id;
        return $this;
    }

    function __construct($id = null) {
        parent::__construct($id);
        $this->up = date("Y-m-d H:i:s");
    }

    /**
     * @param DeviceInterfaceHistory $object
     * @param $displayAllProps
     * @return array|void
     */
    function getAsArray($object = null, $displayAllProps = false)
    {
        if($object == null) {
            $object = $this;
        }
        $arr =  parent::getAsArray($object, $displayAllProps); // TODO: Change the autogenerated stub
        $arr['duration_sec'] = null;
        if($object->getDown()) {
            $arr['duration_sec'] = \DateTime::createFromFormat("Y-m-d H:i:s", $object->getDown())->getTimestamp() - \DateTime::createFromFormat("Y-m-d H:i:s", $object->getUp())->getTimestamp();
        }
        return $arr;
    }


}
