<?php


namespace WCAA\Models\Devices;


use InvalidArgumentException;
use WCAA\Models\AbstractModel;

class DeviceAccess extends AbstractModel
{

    /**
     * @prop.display=root
     * @morm.name=params
     * @var array
     */
    protected $params = [];

    /**
     * @morm
     * @var string
     */
    protected $name;

    /**
     * @prop.display=no
     * @morm
     * @var string
     */
    protected $public_community;
    /**
     * @prop.display=no
     * @morm
     * @var string | null
     */
    protected $private_community;

    /**
     * @prop.display=no
     * @morm
     * @var string
     */
    protected $login;

    /**
     * @prop.display=no
     * @morm
     * @var string
     */
    protected $password;

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return DeviceAccess
     */
    public function setName(string $name): DeviceAccess
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getPublicCommunity(): string
    {
        return $this->public_community;
    }

    /**
     * @param string $public_community
     * @return DeviceAccess
     */
    public function setPublicCommunity(string $public_community): DeviceAccess
    {
        if(!$public_community) {
            throw new InvalidArgumentException("Community can't be empty");
        }
        //if(!preg_match('/^[A-Za-z0-9_-]{1,}$/', $community)) {
        //    throw new InvalidArgumentException("Community isn't correct");
        //}
        $this->public_community = trim($public_community);
        return $this;
    }

    /**
     * @return string
     */
    public function getLogin(): string
    {
        return $this->login;
    }

    /**
     * @param string $login
     * @return DeviceAccess
     */
    public function setLogin(string $login): DeviceAccess
    {
        if(!$login) {
            throw new InvalidArgumentException("Login can't be empty");
        }
        $this->login = $login;
        return $this;
    }

    /**
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return DeviceAccess
     */
    public function setPassword(string $password): DeviceAccess
    {
        if(!$password) {
            throw new InvalidArgumentException("Password can't be empty");
        }
        $this->password = $password;
        return $this;
    }

    function __toString()
    {
        return $this->name; // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\ArrayObject
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * @param  $params
     * @return DeviceAccess
     */
    public function setParams($params): DeviceAccess
    {
        $this->params = $params;
        return $this;
    }

    /**
     * @return string | null
     */
    public function getPrivateCommunity()
    {
        return $this->private_community;
    }

    /**
     * @param string $private_community
     * @return DeviceAccess
     */
    public function setPrivateCommunity(string $private_community): DeviceAccess
    {
        $this->private_community = $private_community;
        return $this;
    }
}