<?php

namespace WCC\Notifications\Controllers\Channels;

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use SwitcherCore\Modules\Helper;
use WCC\Notifications\Models\NotificationContact;
use WCC\Notifications\Models\Notification;
use WCC\Events\Models\Event;

class Mail extends AbstractChannel
{
    /**
     * @var null | PHPMailer
     */
    protected $mail = null;

    function send(Notification $alertEvent)
    {
        $alertTemplate = $this->buildTemplate($alertEvent->getType(), [
            'event' => $alertEvent->getEvent() ? $alertEvent->getEvent()->getAsArray() : null,
            'action' => $alertEvent->getAction() ? $alertEvent->getAction()->getAsArray() : null,
            'recipient' => $alertEvent->getContact()->getAsArray(),
        ]);

        $mail = clone $this->mail;
        switch ($alertEvent->getType()) {
            case 'notification':
                $mail->Subject = "Support - System action";
                break;
            case 'alert':
            case 'resolved':
                $mail->Subject = $alertEvent->getEvent()->getDescription();
                break;

        }

        $mail->Body = $alertTemplate;
        $mail->addAddress($alertEvent->getContact()->getValue());
        return [
            'sended' =>$mail->send()
        ];
    }


    function isConfigured()
    {
        return $this->config &&
            !empty($this->config['host']) &&
            !empty($this->config['username']);
    }

    function prepareConfig($config)
    {
        $preparedConf = [
            'templates' => [
                'alert' => file_get_contents(__DIR__ . '/../../files/email_alert.html'),
                'resolved' =>  file_get_contents(__DIR__ . '/../../files/email_resolved.html'),
                'notification' =>  file_get_contents(__DIR__ . '/../../files/email_notification.html'),
            ],
            'host' => '',
            'auth_enabled' => true,
            'username' => '',
            'password' => '',
            'smtp_secure' => 'ssl',
            'port' => 465,
            'from_email' => '',
            'from_name' => '',
        ];

        if($config == null) {
            return  $preparedConf;
        }
        foreach ($preparedConf as $key=>$value) {
            if(isset($config[$key]) && $config[$key]) {
                $preparedConf[$key] = $config[$key];
            }
        }
        return $preparedConf;
    }


    function init() {
        if(!$this->isConfigured()) {
            throw new \Exception("Source email not configured");
        }

        $mail = new PHPMailer(true);
        $mail->SMTPOptions = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            )
        );
        $mail->CharSet = 'UTF-8';
        $mail->isHTML(true);
        $mail->SMTPDebug = SMTP::DEBUG_OFF;                      //Enable verbose debug output
        $mail->isSMTP();                                            //Send using SMTP
        $mail->Host       = $this->config['host'];           //Set the SMTP server to send through
        $mail->SMTPAuth   = $this->config['auth_enabled'];   //Enable SMTP authentication
        $mail->Username   = $this->config['username'];       //SMTP username
        $mail->Password   = $this->config['password'];       //SMTP password
        $mail->SMTPSecure = $this->config['smtp_secure'];    //Enable implicit TLS encryption
        $mail->Port       = $this->config['port'];           //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`
        $mail->setFrom($this->config['from_email'],$this->config['from_name']);
        $this->mail = $mail;
        return $this;
    }

    function getSourceName() {
        return 'email';
    }

    function updateConfiguration($config)
    {
        if(!$config['host']) {
            throw new \InvalidArgumentException("Host is required");
        }
        if(!$config['from_email'] || !filter_var($config['from_email'], FILTER_VALIDATE_EMAIL)) {
            throw new \InvalidArgumentException("Incorrect From email address");
        }
        return parent::updateConfiguration($config); // TODO: Change the autogenerated stub
    }


}