<?php


namespace WCAA\Storage;


use DI\Annotation\Inject;
use WCAA\App;
use WCAA\Models\Devices\Device;
use WCAA\Models\SwitcherCoreAction;
use WCAA\Models\SystemAction;
use WCAA\Models\User\User;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

class SwitcherCoreActionStorage extends AbstractStorage
{

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    protected $tableName = 'switcher_core_actions';

    /**
     * @param SwitcherCoreAction $object
     * @return SwitcherCoreAction
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object);
        if($fillChildObjects) {
            $object->device = $this->deviceStorage->getById($object->device_id);
            $object->user = $this->userStorage->getById($object->user_id);
        }
        return $object;
    }

    /**
     * @param SwitcherCoreAction $object
     * @return SwitcherCoreAction
     * @throws \Exception
     */
    public function add($object)
    {
        $object->user_id = $object->getUser()->getId();
        $object->device_id = $object->getDevice()->getId();
        $obj = parent::add($object); // TODO: Change the autogenerated stub
        return  $obj;
    }

    public function update($object)
    {
        $object->user_id = $object->getUser()->getId();
        $object->device_id = $object->getDevice()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param SwitcherCoreAction $object
     * @return SwitcherCoreAction
     * @throws \Exception
     */
    function updateOnDuplicate($object)
    {
        $object->user_id = $object->getUser()->getId();
        $object->device_id = $object->getDevice()->getId();
        return parent::updateOnDuplicate($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param Device $device
     * @param $method
     * @param array $arguments
     * @return SwitcherCoreAction
     * @throws RecordNotFoundException
     */
    function getLastByHash($hash)
    {
        $hashTimeout = $this->app->conf('switcher_core.cache_actualize_timeout_sec');
        $psth = $this->pdo->prepare("SELECT id FROM switcher_core_actions WHERE `hash` = ? and time > NOW() - INTERVAL ? SECOND ORDER BY id desc LIMIT 1");
        $psth->execute([$hash, $hashTimeout ]);
        if ($psth->rowCount() === 0) {
            throw (new RecordNotFoundException("Not found success record by hash $hash"))->setObjectName("SwitcherCoreActionStorage");
        }
        $storeId = $psth->fetchAll()[0]['id'];
        $object =  ($this->getObjectById(SwitcherCoreAction::class, $storeId));
        return $object;
    }

    /**
     * @param Device $device
     * @param $method
     * @param array $arguments
     * @return SwitcherCoreAction
     * @throws RecordNotFoundException
     */
    function getLastWithoutTimeoutByHash($hash)
    {
        $psth = $this->pdo->prepare("SELECT id FROM switcher_core_actions WHERE `status` = 'SUCCESS' and `hash` = ? ORDER BY id desc LIMIT 1");
        $psth->execute([$hash]);
        if ($psth->rowCount() === 0) {
            throw new RecordNotFoundException("Not found success record by hash $hash");
        }
        $object =  ($this->getObjectById(SwitcherCoreAction::class, $psth->fetchAll()[0]['id']));
        return $object;
    }

    /**
     * @param $id
     * @return SwitcherCoreAction
     */
    function getById($id)
    {
        return ($this->getObjectById(SwitcherCoreAction::class, $id));
    }

    function getResultsByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("
            SELECT id, time, user_id, device_id, status, hash, module, arguments, data
            FROM switcher_core_actions WHERE device_id = ? order by  id desc LIMIT ? 
        ");
        $psth->execute([$device->getId()]);
        return $this->prepareResults($psth, ['device' => $device, $this->app->conf('panel.logs_return_result_limit')]);
    }

    function getResultsByMethod($methodName)
    {
        $psth = $this->pdo->prepare("
            SELECT id, time, user_id, device_id, status, hash, module, arguments, data
            FROM switcher_core_actions WHERE  module = ? order by  id desc  limit ?
        ");
        $psth->execute([$methodName, $this->app->conf('panel.logs_return_result_limit')]);
        return $this->prepareResults($psth);
    }

    private function prepareResults(\PDOStatement $psth, $definedObjects = [])
    {
        if ($psth->rowCount() === 0) {
            throw new RecordNotFoundException('Records not found');
        }
        $response = [];
        foreach ($psth->fetchAll() as $row) {
            $coreAction = $this->fillByArr(new Device(), $row);
            if (isset($definedObjects['device'])) {
                $coreAction->device = $definedObjects['device'];
            } else {
                $coreAction->device = $this->deviceStorage->getById($row['device_id']);
            }
            if (isset($definedObjects['user'])) {
                $coreAction->user = $definedObjects['user'];
            } else {
                $coreAction->user = $this->userStorage->getById($row['user_id']);
            }
        }
        return $response;
    }


    function getModulesList()
    {
        $data = $this->pdo->query("SELECT DISTINCT module 
FROM `switcher_core_actions` 
ORDER BY 1;")->fetchAll();
        $resp = [];
        foreach ($data as $d) {
            $resp[] = $d['module'];
        }
        return $resp;
    }

    /**
     * @param $start
     * @param $stop
     * @param array $modules
     * @param array $userIds
     * @param string $status
     * @return SystemAction[]
     */
    function getActionsByFilter($start, $stop, $modules = [], $userIds = [], $status = '', $deviceId = null)
    {
        $query = "SELECT id, time, user_id, device_id, `status`, `hash`, module, arguments, data, meta
                    FROM  `{$this->tableName}` WHERE (time BETWEEN ? and ?) ";
        if ($modules) {
            $modules = array_map(function ($e) {
                return $this->pdo->quote($e, \PDO::PARAM_STR);
            }, $modules);
            $query .= " and module in (" . join(',', $modules) . ")";
        }
        if ($userIds) {
            $userIds = array_map(function ($e) {
                return $this->pdo->quote($e, \PDO::PARAM_INT);
            }, $userIds);
            $query .= " and user_id in (" . join(',', $userIds) . ")";
        }
        if ($status) {
            $status = $this->pdo->quote($status);
            $query .= " and `status` = $status";
        }
        if ($deviceId) {
            $deviceId = $this->pdo->quote($deviceId);
            $query .= " and `device_id` = $deviceId";
        }
        $query .= " ORDER BY 1 desc limit ?";
        $psth = $this->pdo->prepare($query);
        $psth->execute([$start, $stop, $this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];
        foreach ($psth->fetchAll() as $d) {
            $r = $this->fillByArr(new SwitcherCoreAction(), $d);
            $r->setUser($this->userStorage->fill(new User($d['user_id'])));
            $r->setDevice($this->deviceStorage->fill(new Device($d['device_id'])));
            $resp[] = $r;
        }
        return $resp;
    }

    /**
     * @param $start
     * @param $stop
     * @param array $modules
     * @param array $userIds
     * @param string $status
     */
    function getCountByFilter($start, $stop, $modules = [], $userIds = [], $status = '')
    {
        $query = "SELECT count(*) c 
                    FROM  `{$this->tableName}` WHERE (time BETWEEN ? and ?) ";
        if ($modules) {
            $modules = array_map(function ($e) {
                return $this->pdo->quote($e, \PDO::PARAM_STR);
            }, $modules);
            $query .= " and module in (" . join(',', $modules) . ")";
        }
        if ($userIds) {
            $userIds = array_map(function ($e) {
                return $this->pdo->quote($e, \PDO::PARAM_INT);
            }, $userIds);
            $query .= " and user_id in (" . join(',', $userIds) . ")";
        }
        if ($status) {
            $status = $this->pdo->quote($status);
            $query .= " and `status` = $status ";
        }
        $psth = $this->pdo->prepare($query );
        $psth->execute([$start, $stop]);

        return (int)$psth->fetch()['c'];
    }

    public function callingErrorsStatByDevice(?User $user = null) {

        $where = "WHERE 1=1";
        if($user) {
            if($user->getRole()->getId() > 0) {
                $deviceGroupIds = [-1];
                foreach ($user->getDeviceGroups() as $gr) {
                    $deviceGroupIds[] = $gr->getId();
                }
                $where .= " and d.id in (SELECT id FROM devices WHERE group_id in (".join(",", $deviceGroupIds)."))";
            }
        }
        $psth = $this->pdo->prepare("SELECT d.id,  cc.count_errors critical_errors, cnr.count_errors not_respond_errors
FROM devices d
LEFT JOIN (
    SELECT a.device_id, count(*) count_errors
    FROM switcher_core_actions a
    WHERE status='FAILED'
      and JSON_EXTRACT(meta, '\$.error.message') not like '%not respond over%' 
      and JSON_EXTRACT(meta, '\$.error.message') not like '%No response from%' 
      and `time` > NOW() - INTERVAL 1 day
    GROUP BY a.device_id
) cc on cc.device_id = d.id
LEFT JOIN (
    SELECT a.device_id, count(*) count_errors
    FROM switcher_core_actions a
    WHERE status='FAILED'
      and (JSON_EXTRACT(meta, '\$.error.message') like '%not respond over%' 
              or JSON_EXTRACT(meta, '\$.error.message') like '%No response from%' 
             )
      and `time` > NOW() - INTERVAL 1 day
    GROUP BY a.device_id
) cnr on cnr.device_id = d.id
{$where} 
order by 2 desc, 3 desc");
        $psth->execute();
        $response = [];
        foreach ($psth->fetchAll() as $i) {
            $response[] = [
                'device' => $this->deviceStorage->getById($i['id']),
                'errors_count' => (int)$i['critical_errors'],
                'not_responding_count' => (int)$i['not_respond_errors'],
            ];
        }
        return $response;
    }

}