<?php


namespace WCAA\Storage;



use WCAA\App;
use WCAA\Infrastructure\Events\EventObserverStorage;
use WCAA\Models\SystemAction;
use WCAA\Models\User\User;
use WCAA\Storage\Devices\DeviceStorage;

class SystemActionsStorage extends AbstractStorage
{
    protected $tableName = 'system_actions';

    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    public function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object); // TODO: Change the autogenerated stub
        $object->user = $this->userStorage->getById($object->user_id);
        try {
            if ($object->device_id) {
                $object->device = $this->deviceStorage->getById($object->device_id);
            }
        } catch (\Exception $e) {}
        return $object;
    }

    /**
     * @param $object
     * @return SystemAction
     * @throws \DI\DependencyException
     * @throws \DI\NotFoundException
     */
    public function add($object)
    {
        $object->user_id = $object->user->getId();
        if($object->device) {
            $object->device_id = $object->device->getId();
        }
        $obj = parent::add($object);
        App::getInstance()->getContainer()->get(EventObserverStorage::class)->notify("sys_action:added", $obj);
        return $object;
    }

    public function update($object)
    {
        $object->user_id = $object->user->getId();
        if($object->device) {
            $object->device_id = $object->device->getId();
        }
        return parent::update($object);
    }

    /**
     * @return SystemAction[]
     */
    public function fetchAll()
    {
        $psth = $this->pdo->prepare("SELECT id FROM {$this->tableName} order by id desc limit ?");
        $psth->execute([$this->app->conf('panel.logs_return_result_limit')]);
        $response = [];
        foreach ($psth->fetchAll() as $arr) {
            $response[] = $this->fill(new SystemAction($arr['id']));
        }
        return $response;
    }

    function getById($id)
    {
        return $this->getObjectById(SystemAction::class, $id);
    }

    function getActionsList()
    {
        $data = $this->pdo->query("SELECT DISTINCT action FROM `system_actions` ORDER BY 1 ;")->fetchAll();
        $resp = [];
        foreach ($data as $d) {
            $resp[] = $d['action'];
        }
        return $resp;
    }

    /**
     * @param $start
     * @param $stop
     * @param array $actions
     * @param array $userIds
     * @param string $status
     * @return SystemAction[]
     */
    function getActionsByFilter($start, $stop, $actions = [], $userIds = [], $status = '', $limit = 0)
    {
        $query = "SELECT id  
            FROM `system_actions` WHERE (created_at BETWEEN ? and ?)  ";
        if ($actions) {
            $actions = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_STR);
            }, $actions);
            $query .= " and action in (" . join(',', $actions) . ")";
        }
        if ($userIds) {
            $userIds = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_INT);
            }, $userIds);
            $query .= " and user_id in (" . join(',', $userIds) . ")";
        }
        if ($status) {
            $status = $this->pdo->quote($status);
            $query .= " and `status` = $status";
        }

        $query .= " ORDER BY 1 desc limit ?";
        $psth = $this->pdo->prepare($query);
        if(!$limit) {
            $limit = $this->app->conf('panel.logs_return_result_limit');
        }
        $psth->execute([$start, $stop, $limit]);
        $resp = [];

        foreach ($psth->fetchAll() as $d) {
            $resp[] = $this->fill(new SystemAction($d['id']));
        }
        return $resp;
    }

    /**
     * @param $object
     * @param array $fetchArr
     * @return SystemAction
     */
    function fillByArr($object, $fetchArr = [])
    {
        return parent::fillByArr($object, $fetchArr); // TODO: Change the autogenerated stub
    }
}