<?php


namespace WCAA\Storage;


use DI\Annotation\Inject;
use InvalidArgumentException;
use WCAA\App;
use WCAA\Infrastructure\Compiller;
use WCAA\Infrastructure\ComponentInjector;
use WCAA\Infrastructure\Events\EventObserverStorage;
use WCAA\Models\SystemComponent;
use WCAA\Models\User\User;

class SystemComponentsStorage extends AbstractStorage
{
    protected $tableName = 'system_components';


    protected $_fetched =  null;

    /**
     * @param $id
     * @return SystemComponent
     */
    function getById($id) {
        return $this->getObjectById(SystemComponent::class, $id);
    }

    /**
     * @return SystemComponent[]
     */
    function fetchAll() {
        if($this->_fetched) {
            return  $this->_fetched;
        }
        if($cached = $this->cache->get("SYSTEM_COMPONENTS_FETCHED")) {
            return  $cached;
        }
        $psth = $this->pdo->query("SELECT * FROM system_components order by `key` ");
        $response = [];
        foreach ($psth->fetchAll() as $r) {
            $obj= $this->fillByArr(new SystemComponent(), $r);
            $obj->builtIn = $obj->builtIn === 1;
            $obj->enabled = $obj->enabled === 1;
            $response[] = $obj;
        }
        $this->_fetched = $response;
        $this->cache->set("SYSTEM_COMPONENTS_FETCHED", $response, $this->app->conf('memcache.storage_timeout'));
        return $response;
    }

    /**
     * @param string $key
     * @return SystemComponent|null
     * @throws \Exception
     */
    function getByKey($key) {
        $psth  = $this->pdo->prepare("SELECT id FROM system_components WHERE `key` = ? ");
        $psth->execute([$key]);
        if($psth->rowCount() === 0) {
            throw new \Exception("Component with key='$key' not found!");
        }
        $data = $psth->fetchAll()[0];
        return $this->fill(new SystemComponent($data['id']));
    }

    function add($object)
    {
        $up = parent::add($object); // TODO: Change the autogenerated stub
        $this->cache->delete("SYSTEM_COMPONENTS_FETCHED");
        ComponentInjector::setFetchedComponents(null);
        App::getInstance()->resetRRWorkers();
        return $up;
    }

    function update($object)
    {
        $up = parent::update($object); // TODO: Change the autogenerated stub
        App::getInstance()->getContainer()->get(EventObserverStorage::class)->notify("component:updated", $up);
        $this->cache->delete("SYSTEM_COMPONENTS_FETCHED");
        ComponentInjector::setFetchedComponents(null);
        App::getInstance()->resetRRWorkers();
        return $up;
    }
    function delete($object)
    {
        $up = parent::delete($object); // TODO: Change the autogenerated stub
        $this->cache->delete("SYSTEM_COMPONENTS_FETCHED");
        ComponentInjector::setFetchedComponents(null);
        App::getInstance()->resetRRWorkers();
        return $up;
    }
}
