<?php


namespace WCAA\Storage;


use DI\Annotation\Inject;
use InvalidArgumentException;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Models\User\User;
use WCAA\Models\User\UserRole;
use WCAA\Storage\Devices\DeviceGroupStorage;

class UserStorage extends AbstractStorage
{
    protected $tableName = 'users';

    /**
     * @Inject
     * @var UserRoleStorage
     */
    protected $userRoleStorage;

    /**
     * @Inject
     * @var DeviceGroupStorage
     */
    protected $deviceGroupsStorage;


    /**
     * @param User $object
     * @return User
     */
    public function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object); // TODO: Change the autogenerated stub
        $object->role = $this->userRoleStorage->getById($object->role_id);

        $deviceGroups = [];
        if($object->id < 0 || $object->role->getId() < 0) {
            $deviceGroups = $this->deviceGroupsStorage->fetchAll();
        } else {
            try {
                $psth = $this->pdo->prepare("SELECT group_id FROM user_devices_groups WHERE user_id = ?");
                $psth->execute([$object->getId()]);
                foreach ($psth->fetchAll() as $group) {
                    $deviceGroups[] = $this->deviceGroupsStorage->fill(new DeviceGroup($group['group_id']));
                }
            } catch (\Throwable $e) {
                $this->logger->error("Error fill user with id={$object->getId()} - {$e->getMessage()}");
                throw $e;
            }
        }
        $object->setDeviceGroups($deviceGroups);
        return $object;
    }

    public function add($object)
    {
        $root = clone $object;
        $object->role_id = $object->role->getId();
        $data = parent::add($object);

        try {
            $psth = $this->pdo->prepare("INSERT INTO user_devices_groups (created_at, group_id, user_id) 
                                        VALUES (NOW(),?,?)");
            foreach ($root->deviceGroups as $devGroup) {
                $psth->execute([$devGroup->id, $data->id]);
            }
        } catch (\Throwable $e) {
            $this->logger->error("Error add user to device groups with id={$object->getId()} - {$e->getMessage()}");
        }
        return $data;
    }

    public function update($object)
    {
        $object->role_id = $object->role->getId();
        try {
            $this->pdo->prepare("DELETE FROM user_devices_groups WHERE user_id = ?")->execute([$object->id]);
            $psth = $this->pdo->prepare("INSERT INTO user_devices_groups (created_at, group_id, user_id) 
                                        VALUES (NOW(),?,?)");
            foreach ($object->deviceGroups as $devGroup) {
                $psth->execute([$devGroup->id, $object->id]);
            }
        } catch (\Throwable $e) {
            $this->logger->error("Error add user to device groups with id={$object->getId()} - {$e->getMessage()}");
        }
        return parent::update($object);
    }

    public function delete($object)
    {
        return parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * Write a new password hash without touching any other user field.
     *
     * update() rewrites role and device-group links, which is far more than an
     * upgrade-on-login needs and would fail on a partially hydrated User.
     *
     * @param int $userId
     * @param string $hash
     * @return $this
     */
    public function updatePasswordHash($userId, $hash) {
        $psth = $this->pdo->prepare("UPDATE users SET password = ? WHERE id = ?");
        $psth->execute([$hash, $userId]);
        $this->clearByObject(new User());
        return $this;
    }

    /**
     * @param string $login
     * @return User
     */
    public function getUserByLogin(string $login) {
        if(!$login) {
            throw new InvalidArgumentException("Login cant empty");
        }
        $psth = $this->pdo->prepare("SELECT id FROM users WHERE login = ?");
        $psth->execute([$login]);
        if($psth->rowCount() === 0) {
            return null;
        }
        $user = (new User())->setId($psth->fetchAll()[0]['id']);
        return $this->fill($user);
    }

    /**
     * @return User[]
     */
    public function fetchAll() {
        $psth = $this->pdo->query("SELECT id FROM users");
        $response = [];
        foreach ($psth->fetchAll() as $id) {
            $response[] = $this->fill((new User())->setId($id['id']));
        }
        return $response;
    }

    /**
     * @param number $id
     * @return User
     */
    function getById($id) {
        return $this->getObjectById(User::class, $id);
    }

    /**
     * @param UserRole $group
     * @return User[]
     */
    function getUsersByRole(UserRole $group) {
        $psth = $this->pdo->prepare("SELECT id FROM users WHERE role_id = ?");
        $psth->execute([$group->getId()]);
        $users = [];
        foreach ($psth->fetchAll() as $usrId) {
            $users[] = $this->getById($usrId['id']);
        }
        return $users;
    }

    /**
     * @param DeviceGroup $deviceGroup
     * @return User[]
     */
    function getUsersByDeviceGroup(DeviceGroup $deviceGroup) {
        $psth = $this->pdo->prepare("SELECT user_id 
FROM user_devices_groups WHERE group_id = ?");
        $psth->execute([$deviceGroup->getId()]);
        $users = [];
        foreach ($psth->fetchAll() as $usrId) {
            $users[$usrId['user_id']] = $this->getById($usrId['user_id']);
        }
        //Add system users
        foreach ($this->getUsersByRole(new UserRole(-2)) as $usr) {
            $users[$usr->getId()] = $usr;
        }
        return array_values($users);
    }

    function getCountUsers() {
        if($count = $this->cache->get("STORAGE::Users:count_users")) {
            return $count;
        }
        $count = $this->pdo->query("SELECT count(*) c FROM users WHERE id > 0 AND status = 'ENABLED'")->fetchAll()[0]['c'];
        $this->cache->set("STORAGE::Users:count_users", $count, 60);
        return  $count;
    }

}
