<?php


namespace WCAA\Storage;


use Exception;
use WCAA\Interfaces\CacheInterface;
use WCAA\Models\User\UserRole;

/**
 * Class UserRoleStorage
 * @package WCAA\Storage
 */
class UserRoleStorage extends AbstractStorage
{
    protected $tableName = 'user_roles';

    /**
     * @Inject
     * @var CacheInterface
     */
    protected $cache;

    /**
     * @param UserRole $object
     * @return UserRole|null
     */
    function getByName($name) {
        $id = $this->getOneIdByWhere("name=?", [$name]);
        if(!$id) {
            throw new Exception("Role with name $name not found");
        }
        return $this->fill((new UserRole())->setId($id));
    }

    /**
     * @param UserRole $object
     * @return UserRole|null
     */
    function fill($object, $fillChildObjects = true)
    {
        $object = parent::fill($object);
        if(!$object) return null;
        if($object->getId() <= 0) {
            $permissions = [];
            foreach ($this->app->conf('api.auth.rules') as $perm) {
                $permissions[] = $perm['key'];
            }
            $object->setPermissions($permissions);
        }
        $object->display = $object->display == 1;
        return $object;
    }

    /**
     * @param UserRole $object
     * @return UserRole|null
     */
    function update($object)
    {
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param UserRole $object
     * @return UserRole|null
     */
    function add($object)
    {
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    function delete($object)
    {
        return parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return UserRole[]
     */
    public function fetchAll() {
        $psth = $this->pdo->query("SELECT id FROM user_roles");
        $response = [];
        foreach ($psth->fetchAll() as $id) {
            $response[] = $this->fill((new UserRole())->setId($id['id']));
        }
        return $response;
    }

    /**
     * @param $id
     * @return UserRole
     */
    public function getById($id) {
        return $this->getObjectById(UserRole::class, $id);
    }

    /**
     * @param $permissionName
     * @return UserRole[]
     */
    public function getRolesByPermissionName($permissionName) {
        $groups = array_filter($this->fetchAll(), function ($group) use ($permissionName) {
            if($group->getId() <= 0) {
                return true;
            }
            return in_array($permissionName, $group->getPermissions());
        });
        return array_values($groups);
    }
}