[inet_http_server]
port=0.0.0.0:9001
username=user
password=user

[supervisord]
logfile=/dev/stdout    ; supervisord log file
loglevel=error                                  ; info, debug, warn, trace
pidfile=/var/run/supervisord.pid                ; pidfile location
nodaemon=true                                   ; run supervisord as a daemon
minfds=1024                                     ; number of startup file descriptors
minprocs=300                                    ; number of process descriptors
user=root

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)
username=user
password=user

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface


[program:telegram-bot]
command=/processes/telegram-bot.sh
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
startretries=999
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:notifications]
command=/processes/notification-service.sh
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
startretries=999
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:poller]
command=/processes/poller.sh
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
startretries=999
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:trap-processor]
command=/processes/trap-processor.sh
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
startretries=999
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:scheduler]
command=cron -f
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:internal-event-listener]
command=/processes/internal-event-listener.sh
user=root
stderr_logfile = /dev/stderr
stdout_logfile = /dev/stdout
autostart=true
autorestart=true
startsecs=10
startretries=999
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0