<?php

namespace WCC\Attachments\Storage;

use WCAA\Storage\AbstractStorage;
use WCAA\Storage\UserStorage;
use WCC\Attachments\Models\Attachment;

class AttachmentStorage extends AbstractStorage
{
    protected $tableName = 'c_attachments';

    /**
     * @Inject
     * @var UserStorage
     */
    protected $userStorage;

    /**
     * @param Attachment $object
     * @return Attachment
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object);
        if ($obj->user_id) $obj->user = $this->userStorage->getById($obj->user_id);
        return $obj;
    }

    /**
     * @param Attachment $object
     * @param $fillArr
     * @return Attachment
     */
    public function fillByArr($object, $fillArr = [], $fillChildren = true)
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        if ($obj->user_id) $obj->user = $this->userStorage->getById($obj->user_id);

        return $obj;
    }

    /**
     * @param Attachment $object
     * @return Attachment
     */
    public function add($object)
    {
        $object->user_id = $object->getUser()->getId();
        exec("mkdir -p /www/var/attachments/{$object->getObjectType()}/{$object->getObjectId()}");
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param $objectType
     * @param $objectId
     * @return Attachment[]
     * @throws \Exception
     */
    function fetchByObject($objectType, $objectId)
    {
        $objects = [];
        $psth = $this->pdo->prepare("SELECT id FROM {$this->tableName} WHERE object_type = :object_type AND object_id = :object_id order by id desc");
        $psth->execute(['object_type' => $objectType, 'object_id' => $objectId]);
        foreach ($psth->fetchAll(\PDO::FETCH_ASSOC) as $row) {
            $objects[] = $this->fill(new Attachment($row['id']));
        }
        return $objects;
    }

    function getObjectMetaByUUID($uuid)
    {
        $psth = $this->pdo->prepare("SELECT id FROM {$this->tableName} WHERE uuid = :uuid");
        $psth->execute(['uuid' => $uuid]);
        if($psth->rowCount() === 0) {
            throw new \Exception('Object not found with UUID ' . $uuid);
        }
        $meta = $psth->fetchAll(\PDO::FETCH_ASSOC);
        return $this->fill(new Attachment($meta[0]['id']));
    }

    /**
     * @param Attachment $object
     * @return Attachment
     */
    public function update($object)
    {
        $object->user_id = $object->getUser()->getId();
        exec("mkdir -p /www/var/attachments/{$object->getObjectType()}/{$object->getObjectId()}");
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    public function delete($object)
    {
        $obj = $this->fill($object, false);
        exec("rm -f /www/var/attachments/{$obj->getObjectType()}/{$obj->getObjectId()}/{$obj->getUuid()}*");
        return parent::delete($object);
    }
}
