<?php

namespace WCC\AutoDiscovery\Storage;

use DI\Annotation\Inject;
use DI\Container;
use WCAA\Models\Devices\DeviceGroup;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceAccessStorage;
use WCAA\Storage\Devices\DeviceGroupStorage;
use WCC\AutoDiscovery\Models\AutoDiscoveryNetwork; 
use WCC\Events\Models\Event;
use WCC\Events\Storage\EventsStorage;

class AutoDiscoveryNetworksStorage extends AbstractStorage
{
    protected $tableName = 'c_autodiscovery_networks';
    
    /**
     * @Inject
     * @var DeviceGroupStorage
     */
    protected $deviceGroupStorage;

    /**
     * @Inject
     * @var DeviceAccessStorage
     */
    protected $deviceAccessStorage;

    /**
     * @param AutoDiscoveryNetwork $object
     * @return AutoDiscoveryNetwork
     * @throws \Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $obj = parent::fill($object); // TODO: Change the autogenerated stub
        $obj->device_group = $this->deviceGroupStorage->getById($obj->device_group_id);
        $obj->device_access = $this->deviceAccessStorage->getById($obj->access_id);
        return $obj;
    }

    /**
     * @param $id
     * @return AutoDiscoveryNetwork
     */
    public function getById($id)
    {
        return $this->getObjectById(new AutoDiscoveryNetwork(), $id);
    }

    /**
     * @param AutoDiscoveryNetwork $object
     * @param $fillArr
     * @return AutoDiscoveryNetwork
     */
    public function fillByArr($object, $fillArr = [])
    {
        $obj = parent::fillByArr($object, $fillArr); // TODO: Change the autogenerated stub
        $obj->device_group = $this->deviceGroupStorage->getById($obj->device_group_id);
        $obj->device_access = $this->deviceAccessStorage->getById($obj->access_id);
        return $obj;
    }

    /**
     * @param AutoDiscoveryNetwork $object
     * @return AutoDiscoveryNetwork
     */
    public function add($object)
    {
        $object->setCidr(trim($object->getCidr()));
        if(!$this->validateCIDR($object->getCidr())) {
            throw new \InvalidArgumentException("CIDR {$object->getCidr()} isn't correct");
        }
        $object->access_id = $object->getDeviceAccess()->getId();
        $object->device_group_id = $object->getDeviceGroup()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param AutoDiscoveryNetwork $object
     * @return AutoDiscoveryNetwork
     */
    public function update($object)
    {
        $object->setCidr(trim($object->getCidr()));
        if(!$this->validateCIDR($object->getCidr())) {
            throw new \InvalidArgumentException("CIDR {$object->getCidr()} isn't correct");
        }
        $object->access_id = $object->getDeviceAccess()->getId();
        $object->device_group_id = $object->getDeviceGroup()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param AutoDiscoveryNetwork[] $objects
     * @return AutoDiscoveryNetwork[]
     */
    public function updateAll(array $objects) {
        $this->pdo->beginTransaction();
        $this->pdo->exec("DELETE FROM c_autodiscovery_networks");
        $updated = [];
        foreach ($objects as $object) {
            $updated[] = $this->add($object);
        }
        $this->pdo->commit();
        $this->cache->deleteByRegex('/AutoDiscovery/');
        return $updated;
    }

    public function fetchAll() {
        $idsPsth = $this->pdo->prepare("SELECT id FROM c_autodiscovery_networks");
        $idsPsth->execute();
        $ret = [];
        foreach ($idsPsth->fetchAll() as $ids) {
            $ret[] = $this->fill(new AutoDiscoveryNetwork($ids['id']));
        }
        return $ret;
    }
    public function validateCIDR($cidr)
    {
        if(preg_match('/^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\/([0-9]{1,2})$/', $cidr, $m)) {
            if($m[1] > 255) return false;
            if($m[2] > 255) return false;
            if($m[3] > 255) return false;
            if($m[4] > 255) return false;
            if($m[5] > 32) return false;
            return true;
        } else {
            return  false;
        }
    }

}
