#!/usr/bin/env python3
"""Regenerate backend/app/registry/trap_profile_data.py from the legacy switcher-core trap configs.

Reads the real, checked-in trap definitions (name, object OID, is_interface, modules, description) straight out of
the legacy YAML the current PHP trap listener reads. Nothing here is invented: an entry not present in one of the
four source files is not emitted. OIDs are stored without the leading dot the legacy files use, matching the
convention every other OID in this registry already follows (app/registry/standard_oids.py) - Plan 8 found that a
leading-dot mismatch there silently breaks matching against this system's own stored values.

Run from the repository root:  python3 tools/gen_trap_profile_catalogue.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
TRAPS_DIR = ROOT / "vendor/meklis/switcher-core/configs/traps"
OUT = ROOT / "backend/app/registry/trap_profile_data.py"

# (source file, vendor slug). "global" traps (IETF-standard linkUp/linkDown) apply to any vendor.
SOURCES: list[tuple[str, str]] = [
    ("global.yml", "global"),
    ("bdcom.yml", "bdcom"),
    ("cdata.yml", "cdata"),
    ("huawei.yml", "huawei"),
]


class SourceError(ValueError):
    pass


def _oid(raw: str) -> str:
    oid = raw.strip().lstrip(".")
    if not oid or not all(part.isdigit() for part in oid.split(".")):
        raise SourceError(f"not a numeric OID: {raw!r}")
    return oid


def _entries(vendor: str, path: Path) -> list[tuple[str, str, str, bool, tuple[str, ...], str]]:
    rows = yaml.safe_load(path.read_text())
    if not isinstance(rows, list):
        raise SourceError(f"{path}: expected a list at the top level")
    out = []
    for row in rows:
        name = str(row["name"]).strip()
        oid = _oid(row["object"])
        # The legacy bdcom.yml misspells the key as "descriptions" (plural) on its first few entries; both are read.
        description = str(row.get("description") or row.get("descriptions") or "").strip()
        if not description:
            raise SourceError(f"{path}: {name} has no description")
        is_interface = bool(row.get("is_interface", False))
        modules = tuple(str(m) for m in (row.get("modules") or []))
        out.append((vendor, name, oid, is_interface, modules, description))
    return out


def main() -> None:
    all_entries: list[tuple[str, str, str, bool, tuple[str, ...], str]] = []
    for filename, vendor in SOURCES:
        path = TRAPS_DIR / filename
        if not path.is_file():
            raise SourceError(f"missing source file: {path}")
        all_entries.extend(_entries(vendor, path))

    seen: dict[tuple[str, str], str] = {}
    for vendor, name, oid, _is_interface, _modules, _description in all_entries:
        key = (vendor, name)
        if key in seen and seen[key] != oid:
            raise SourceError(f"{vendor}/{name} declared twice with different OIDs: {seen[key]} and {oid}")
        seen[key] = oid

    lines = [
        '"""Real trap definitions from the legacy switcher-core configs (vendor/meklis/switcher-core/configs/traps/),',
        'generated by tools/gen_trap_profile_catalogue.py. Do not hand-edit; re-run the generator instead."""',
        "from __future__ import annotations",
        "",
        "# (vendor, name, oid, is_interface, modules, description)",
        "TRAP_PROFILES: list[tuple[str, str, str, bool, tuple[str, ...], str]] = [",
    ]
    for vendor, name, oid, is_interface, modules, description in all_entries:
        lines.append(f"    ({vendor!r}, {name!r}, {oid!r}, {is_interface!r}, {modules!r}, {description!r}),")
    lines.append("]")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(all_entries)} trap profiles to {OUT}")


if __name__ == "__main__":
    try:
        main()
    except SourceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
