#!/usr/bin/env python3
"""Regenerate backend/app/registry/switch_capability_data.py from the legacy switcher-core model files (Plan 18).

A legacy switch model lists the modules it supports; a module that is not listed is a feature that model does not
have. This turns that into the per-model capability table Plan 18 asks for, plus the action modules each model
exposes (kept separate: Plan 38 decides which, if any, become buttons). Nothing is invented: a capability is present
only when the model's own `modules:` block names the legacy module for it.

The legacy tree is not merged into this branch, so the model files are read from a directory given on the command
line, for example one exported read-only from origin/main:

    git archive origin/main vendor/meklis/switcher-core/configs/models | tar -x -C /tmp/legacy
    python3 tools/gen_switch_capabilities.py /tmp/legacy/vendor/meklis/switcher-core/configs/models
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parents[1] / "backend/app/registry/switch_capability_data.py"

# legacy module key -> Plan 18 read capability
CAPABILITY_BY_MODULE = {
    "system": "system",
    "link_info": "link_status",
    "interface_counters": "counters",
    "errors": "errors",
    "lldp_info": "lldp",
    "vlans": "vlan_summary",
    "sfp_optical": "sfp_optical",
    "rmon": "rmon",
    "sys_resources": "resources",
    "sys_temp": "temperature",
    "fdb": "fdb",
}
# legacy module keys that change device state or open a console
ACTION_MODULES = {
    "ctrl_port_descr", "ctrl_port_state", "ctrl_port_speed", "ctrl_vlan_port", "ctrl_vlan_state", "save_config",
    "reboot", "clear_counters", "clear_iface_counters", "cable_diag", "console_command", "multi_console_command",
}


def models_in(path: Path) -> list[dict]:
    data = yaml.safe_load(path.read_text()) or {}
    return data.get("models") or []


def rows(models_dir: Path) -> list[tuple[str, str, str, tuple[str, ...], tuple[str, ...]]]:
    out = []
    for path in sorted(models_dir.glob("*.yml")):
        for model in models_in(path):
            if str(model.get("device_type", "")).upper() != "SWITCH":
                continue
            modules = model.get("modules") or {}
            capabilities = tuple(sorted({CAPABILITY_BY_MODULE[m] for m in modules if m in CAPABILITY_BY_MODULE}))
            actions = tuple(sorted(m for m in modules if m in ACTION_MODULES))
            out.append((model["key"], model["name"], path.name, capabilities, actions))
            # A rewrite that names its own modules replaces the parent's list; one that does not inherits it.
            for mapping in (model.get("rewrites") or {}).get("mapping") or []:
                rewrite = mapping.get("rewrite") or {}
                if "key" not in rewrite or rewrite["key"] == model["key"]:
                    continue
                child = rewrite.get("modules")
                child_caps = capabilities if child is None else tuple(sorted({CAPABILITY_BY_MODULE[m] for m in child if m in CAPABILITY_BY_MODULE}))
                child_actions = actions if child is None else tuple(sorted(m for m in child if m in ACTION_MODULES))
                out.append((rewrite["key"], rewrite.get("name", model["name"]), path.name, child_caps, child_actions))
    keys = [r[0] for r in out]
    duplicates = sorted({k for k in keys if keys.count(k) > 1})
    if duplicates:
        raise SystemExit(f"duplicate model keys: {duplicates}")
    return out


def render(data: list[tuple]) -> str:
    lines = [
        '"""Per-model switch capabilities (Plan 18).',
        "",
        "Generated by tools/gen_switch_capabilities.py from the legacy switcher-core model files (configs/models/*.yml, read",
        "from origin/main without merging). A capability is present only when the model's own legacy `modules:` block names",
        'the module for it. Do not edit by hand; regenerate."""',
        "from __future__ import annotations",
        "",
        "# (model key, name, legacy source file, read capabilities, legacy action modules)",
        "SWITCH_MODELS: list[tuple[str, str, str, tuple[str, ...], tuple[str, ...]]] = [",
    ]
    lines += [f"    {row!r}," for row in data]
    lines.append("]")
    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    OUT.write_text(render(rows(Path(sys.argv[1]))))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
