#!/usr/bin/env python3
"""Regenerate backend/app/access/catalogue_data.py.

Inputs (all read-only, offline):
  docs/cybersathy-nms-migration/permission-mapping.md   legacy key -> new code table
  migrations/063_isp_reseller_roles/up.sql              legacy ISP support and Reseller role definitions
  migrations/066_isp_full_control_and_focus/up.sql      legacy full-control ISP role definition

Run from the repository root:  python3 tools/gen_permission_catalogue.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPPING = ROOT / "docs/cybersathy-nms-migration/permission-mapping.md"
M063 = ROOT / "migrations/063_isp_reseller_roles/up.sql"
M066 = ROOT / "migrations/066_isp_full_control_and_focus/up.sql"
OUT = ROOT / "backend/app/access/catalogue_data.py"

ROW = re.compile(r"^\| (\S+) \| `([a-z_0-9]+)` \| (\S+) \| \d+ \| (`[^`]+`|\(dropped\)) \| (yes)? ?\|")


def humanize(code: str) -> str:
    return code.replace(".", " ").replace("_", " ").capitalize()


def keys_in(block: str) -> list[str]:
    return re.findall(r"'([a-z_0-9]+)'", re.sub(r"--[^\n]*", "", block))


def main() -> int:
    legacy: dict[str, str | None] = {}
    dangerous: dict[str, bool] = {}
    for line in MAPPING.read_text().splitlines():
        m = ROW.match(line)
        if not m:
            continue
        key, code = m.group(2), m.group(4).strip("`")
        if code.startswith("("):
            legacy[key] = None
            continue
        legacy[key] = code
        dangerous[code] = dangerous.get(code, False) or bool(m.group(5))
    if not legacy:
        print("no rows parsed from the mapping table", file=sys.stderr)
        return 1

    b063 = re.findall(r"JSON_ARRAY\((.*?)\n\), '", M063.read_text(), re.S)
    b066 = re.search(r"JSON_ARRAY\((.*?)\n\),\ndescription", M066.read_text(), re.S)
    if len(b063) < 2 or not b066:
        print("could not parse legacy role definitions", file=sys.stderr)
        return 1
    roles = {
        "LEGACY_ISP_SUPPORT_063": keys_in(b063[0]),
        "LEGACY_RESELLER_063": keys_in(b063[1]),
        "LEGACY_ISP_FULL_066": keys_in(b066.group(1)),
    }
    unmapped = sorted({k for v in roles.values() for k in v if k not in legacy})
    if unmapped:
        print("legacy role keys missing from the mapping:", unmapped, file=sys.stderr)
        return 1

    out = [
        '"""Permission catalogue and role defaults.',
        "",
        "Generated by tools/gen_permission_catalogue.py from",
        "docs/cybersathy-nms-migration/permission-mapping.md and the legacy role definitions in",
        'migrations 063 and 066. Do not edit by hand; regenerate."""',
        "from __future__ import annotations",
        "",
        "# (code, group, is_dangerous, description)",
        "PERMISSIONS: list[tuple[str, str, bool, str]] = [",
    ]
    for code in sorted(dangerous):
        out.append(f"    ({code!r}, {code.split('.')[0]!r}, {dangerous[code]}, {humanize(code)!r}),")
    out += ["]", "", "# legacy route-permission key -> new permission code (None = dropped)", "LEGACY_TO_NEW: dict[str, str | None] = {"]
    for key in sorted(legacy):
        out.append(f"    {key!r}: {legacy[key]!r},")
    out += ["}", ""]
    for name, lst in roles.items():
        out.append(f"{name}: list[str] = {lst!r}")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(dangerous)} codes, {len(legacy)} legacy keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
