<?php


namespace WCAA\Console;


use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class EventsSubscriber extends AbstractCommand
{

    /**
     * @Inject
     * @var \Superbalist\PubSub\Redis\RedisPubSubAdapter
     */
    protected $psa;

    function configure()
    {
        $this->setName('events:subscribe')
            ->setDescription("Event listener")
            ->addArgument("event-name",  InputArgument::REQUIRED, "Name of listener");
        parent::configure(); // TODO: Change the autogenerated stub
    }

    function execute(InputInterface $input, OutputInterface $output)
    {
        $this->psa->subscribe($input->getArgument('event-name'), function ($message) use ($output) {
            $output->writeln(json_encode($message, JSON_UNESCAPED_UNICODE));
        });

    }
}