<?php


namespace WCAA\Infrastructure\Components;


use Monolog\Logger;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use WCAA\Console\AbstractCommand;
use WCAA\Infrastructure\ComponentInjector;

/**
 * Класс для интеграции контроллера модуля в систему
 * Class AbstractComponentCommand
 * @package WCAA\Modules
 */
abstract class AbstractComponentCommand extends AbstractCommand
{
    /**
     * @var ComponentInjector
     */
    protected $componentInjector;

    /**
     * @var Logger
     */
    protected $logger;

    /**
     * @var array
     */
    protected $componentConfig;

    abstract function config();
    abstract function exec(InputInterface $input, OutputInterface $output);

    function configure()
    {
        $this->componentConfig = $this->componentInjector->getEnabledComponentConfig($this->getComponentName());
        $this->logger= $this->logger->withName("component-console." . $this->componentConfig['name']);
        return $this->config();
    }

    function execute(InputInterface $input, OutputInterface $output)
    {
        return $this->exec($input, $output);
    }

    function __construct(ComponentInjector $componentInjector, Logger $logger)
    {
        $this->componentInjector = $componentInjector;
        $this->logger = $logger;
        parent::__construct();
    }
    function setName( $name)
    {
        return parent::setName($this->componentConfig['name'] . ":" . $name); // TODO: Change the autogenerated stub
    }

    private function getComponentName() {
        $rc = new \ReflectionClass(get_class($this));
        return (require  dirname($rc->getFileName()) . "/../config.php")['name'];
    }
}