<?php


namespace WCAA\Storage\PollerData;


use DI\Annotation\Inject;
use Exception;
use WCAA\Models\Pollers\ArpHistory;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceAccess;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Models\Devices\DeviceModel;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;
use WCAA\Storage\Exceptions\RecordNotFoundException;

/**
 * @method ArpHistory fillByArr(ArpHistory $object, $fetchArr = [])
 * Class DeviceInterfaceStorage
 * @package WCAA\Storage\Devices
 */
class ArpHistoryStorage extends AbstractStorage
{
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    protected $tableName = 'poll_arp_history';

    /**
     * @param ArpHistory $object
     * @return ArpHistory
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        $fill->device = $this->deviceStorage->getById($fill->device_id);
        return $fill;
    }

    /**
     * @param ArpHistory $object
     * @return ArpHistory
     */
    public function add($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param ArpHistory $object
     * @return ArpHistory
     */
    public function update($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return ArpHistory[]
     */
    function fetchAll() {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` order by id desc");
        $psth->execute();
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new ArpHistory($e['id']));
            $interface->setDevice($this->deviceStorage->getById($interface->device_id));
            $resp[] = $interface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return ArpHistory
     */
    function getById($id) {
        return $this->getObjectById(ArpHistory::class, $id);
    }

    /**
     * @param Device $device
     * @param false $onlyActive
     * @return ArpHistory[]
     */
    function getByDevice(Device $device, $onlyActive = false) {
        if($onlyActive) {
            $query = "SELECT id FROM `{$this->tableName}` WHERE device_id = ? and stop_at is null order by id desc ";
        } else {
            $query = "SELECT id FROM `{$this->tableName}` WHERE device_id = ? order by id desc ";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$device->getId()]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $obj = $this->fill(new ArpHistory($e['id']));
            $obj->setDevice($device);
            $resp[] = $obj;
        }
        return $resp;
    }
}
