<?php


namespace WCAA\Storage\PollerData;


use DI\Annotation\Inject;
use Exception;
use WCAA\Models\Pollers\BgpSession;
use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;

/**
 * @method BgpSession fillByArr(BgpSession $object, $fetchArr = [])
 * Class DeviceInterfaceStorage
 * @package WCAA\Storage\Devices
 */
class BgpSessionStorage extends AbstractStorage
{
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    protected $tableName = 'poll_bgp_sessions';

    /**
     * @param BgpSession $object
     * @return BgpSession
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        $fill->device = $this->deviceStorage->getById($fill->device_id);
        return $fill;
    }

    /**
     * @param BgpSession $object
     * @return BgpSession
     */
    public function add($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param BgpSession $object
     * @return BgpSession
     */
    public function update($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return BgpSession[]
     */
    function fetchAll() {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` order by id desc");
        $psth->execute();
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new BgpSession($e['id']));
            $interface->setDevice($this->deviceStorage->getById($interface->device_id));
            $resp[] = $interface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return BgpSession
     */
    function getById($id) {
        return $this->getObjectById(BgpSession::class, $id);
    }

    /**
     * @param Device $device
     * @param false $onlyActive
     * @return BgpSession[]
     */
    function getByDevice(Device $device) {
        $query = "SELECT id FROM `{$this->tableName}` WHERE device_id = ? order by id desc ";
        $psth = $this->pdo->prepare($query);
        $psth->execute([$device->getId()]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $obj = $this->fill(new BgpSession($e['id']));
            $obj->setDevice($device);
            $resp[] = $obj;
        }
        return $resp;
    }
}
