<?php


namespace WCAA\Storage\PollerData;


use DI\Annotation\Inject;
use Exception;
use WCAA\Models\Pollers\FdbHistory;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;
use WCAA\Storage\Devices\DeviceStorage;

/**
 * @method FdbHistory fillByArr(FdbHistory $object, $fetchArr = [])
 * Class DeviceInterfaceStorage
 * @package WCAA\Storage\Devices
 */
class FdbHistoryStorage extends AbstractStorage
{


    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    protected $tableName = 'poll_fdb_history';

    /**
     * @param FdbHistory $object
     * @return FdbHistory
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        if ($fillChildObjects) {
            $fill->device = $this->deviceStorage->getById($fill->device_id);
            $fill->interface = $this->deviceInterfaceStorage->getById($fill->interface_id);
        }
        return $fill;
    }

    /**
     * @param FdbHistory $object
     * @return FdbHistory
     */
    public function add($object)
    {
        $object->device_id = $object->getDevice()->getId();
        $object->interface_id = $object->getInterface()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param FdbHistory $object
     * @return FdbHistory
     */
    public function addOrUpdate($object)
    {
        $psth = $this->pdo->prepare("
            INSERT INTO poll_fdb_history (device_id, interface_id, mac_address, vlan_id, start_at, stop_at) 
            VALUES (?, ?, ?, ?, ?, null)
            ON DUPLICATE KEY UPDATE stop_at = null 
        ");
        $psth->execute([
            $object->getDevice()->getId(),
            $object->getInterface()->getId(),
            $object->getMacAddress(),
            $object->getVlanId(),
            $object->getStartAt(),
        ]);
        $object->id = $this->pdo->lastInsertId();
        $this->clearCache($object);
        $this->flushIds();
        return $this->fill($object, false);
    }

    /**
     * @param FdbHistory $object
     * @return FdbHistory
     */
    public function update($object)
    {
        $object->device_id = $object->getDevice()->getId();
        $object->interface_id = $object->getInterface()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return FdbHistory[]
     */
    function fetchAll()
    {
        $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` order by id desc");
        $psth->execute();
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new FdbHistory($e['id']));
            $interface->setDevice($this->deviceStorage->getById($interface->device_id));
            $interface->setInterface($this->deviceInterfaceStorage->getById($interface->interface_id));
            $resp[] = $interface;
        }
        return $resp;
    }
    /**
     * @return FdbHistory[]
     */
    function fetchAllActive($fillChildObjects = true)
    {
        $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE stop_at is null order by id desc");
        $psth->execute();
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new FdbHistory($e['id']), $fillChildObjects);
            $resp[] = $interface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return FdbHistory
     */
    function getById($id)
    {
        return $this->getObjectById(FdbHistory::class, $id);
    }

    /**
     * @param Device $device
     * @param false $onlyActive
     * @return FdbHistory[]
     */
    function getByDevice(Device $device, $onlyActive = false)
    {
        if ($onlyActive) {
            $query = "SELECT f.id fdb_id,
       f.device_id fdb_device_id,
       f.interface_id fdb_interface_id,
       f.mac_address fdb_mac_address,
       f.vlan_id fdb_vlan_id,
       f.start_at fdb_start_at,
       f.stop_at fdb_stop_at,
       di.id iface_id,
       di.name iface_name,
       di.bind_key  iface_bind_key,
       di.type iface_type,
       di.parent_bind_key iface_parent_bind_key,
       di.params iface_params
FROM `poll_fdb_history` f
JOIN device_interfaces di on di.id = f.interface_id
WHERE f.device_id = ? and stop_at is null order by 1 desc";
        } else {
            $query = "SELECT f.id fdb_id,
       f.device_id fdb_device_id,
       f.interface_id fdb_interface_id,
       f.mac_address fdb_mac_address,
       f.vlan_id fdb_vlan_id,
       f.start_at fdb_start_at,
       f.stop_at fdb_stop_at,
       di.id iface_id,
       di.name iface_name,
       di.bind_key  iface_bind_key,
       di.type iface_type,
       di.parent_bind_key iface_parent_bind_key,
       di.params iface_params
FROM `poll_fdb_history` f
JOIN device_interfaces di on di.id = f.interface_id
WHERE f.device_id = ? order by 1 desc";
        }
        $resp = [];
        $psth = $this->pdo->prepare($query);
        $psth->execute([$device->getId()]);
        foreach ($psth->fetchAll() as $e) {
            $obj = (new FdbHistory())
                ->setDevice($device)
                ->setId($e['fdb_id'])
                ->setMacAddress($e['fdb_mac_address'])
                ->setStartAt($e['fdb_start_at'])
                ->setStopAt($e['fdb_stop_at'])
                ->setVlanId($e['fdb_vlan_id'])
                ->setInterface(
                    (new DeviceInterface())
                        ->setDevice($device)
                        ->setId($e['iface_id'])
                        ->setBindKey($e['iface_bind_key'])
                        ->setName($e['iface_name'])
                        ->setType($e['iface_type'])
                        ->setParams(json_decode($e['iface_params'], true))
                );
            $resp[] = $obj;
        }
        return $resp;
    }


    /**
     * @param Device $device
     * @param false $onlyActive
     * @return FdbHistory[]
     */
    function getByInterface(DeviceInterface $interface, $onlyActive = false)
    {
        if ($onlyActive) {
            $query = "SELECT id FROM `{$this->tableName}` WHERE interface_id = ? and stop_at is null order by id desc ";
        } else {
            $query = "SELECT id FROM `{$this->tableName}` WHERE interface_id = ?  order by id desc ";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$interface->getId()]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $d = $this->fill(new FdbHistory($e['id']));
            $d->setInterface($interface);
            $resp[] = $d;
        }
        return $resp;
    }

    /**
     * @param Device $device
     * @param int $interfaceBindKey
     * @param false $onlyActive
     * @return FdbHistory[]
     */
    function getByDeviceAndInterfaceBindKey(Device $device, int $interfaceBindKey, $onlyActive = false)
    {
        if ($onlyActive) {
            $query = "SELECT id FROM `{$this->tableName}` 
                    WHERE device_id = ? 
                    and interface_id = (SELECT id FROM device_interfaces WHERE bind_key = ? and device_id = ? LIMIT 1) 
                    and stop_at is null";
        } else {
            $query = "SELECT id FROM `{$this->tableName}` 
                    WHERE device_id = ? 
                    and interface_id = (SELECT id FROM device_interfaces WHERE bind_key = ? and device_id = ? LIMIT 1)";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$device->getId(), $interfaceBindKey, $device->getId()]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $d = $this->fill(new FdbHistory($e['id']));
            $d->setDevice($device);
            $d->setInterface($this->deviceInterfaceStorage->getByDeviceAndKey($device, $interfaceBindKey));
            $resp[] = $d;
        }
        return $resp;
    }

    /**
     * @param Device $device
     * @param int $interfaceName
     * @param false $onlyActive
     * @return FdbHistory[]
     */
    function getByDeviceAndInterfaceInterfaceName(Device $device, int $interfaceName, $onlyActive = false)
    {
        if ($onlyActive) {
            $query = "SELECT * FROM `{$this->tableName}` 
                    WHERE device_id = ? 
                    and interface_id = (SELECT id FROM device_interfaces WHERE name = ? and device_id = ? LIMIT 1) 
                    and stop_at is null";
        } else {
            $query = "SELECT * FROM `{$this->tableName}` 
                    WHERE device_id = ? 
                    and interface_id = (SELECT id FROM device_interfaces WHERE name = ? and device_id = ? LIMIT 1)";
        }
        $psth = $this->pdo->prepare($query);
        $psth->execute([$device->getId(), $interfaceName, $device->getId()]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $d = $this->fillByArr(new FdbHistory(), $e);
            $d->setDevice($device);
            $d->setInterface($this->deviceInterfaceStorage->getByDeviceAndKey($device, $e['interface_id']));
            $resp[] = $d;
        }
        return $resp;
    }

    /**
     * @param $searchLine
     * @param int $limit
     * @return FdbHistory[]
     */
    function search($searchLine, $limit = 10)
    {
        $macAddress = strtoupper(str_replace([' ', '-', ':', '.', ','], '', $searchLine));
        $data = $this->pdo->prepare("SELECT max(id) id, interface_id, mac_address FROM `{$this->tableName}` WHERE REPLACE(mac_address, ':', '') like ?   GROUP BY interface_id, mac_address order by 1 desc limit ?");
        $data->execute(["%{$macAddress}%", $limit]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->getById($d['id']);
        }
        return $response;
    }

    /**
     * @param $mac
     * @param $onlyActive
     * @return FdbHistory[]
     */
    function getByMac($mac, $onlyActive = true)
    {
        if ($onlyActive) {
            $data = $this->pdo->prepare("SELECT max(id) id, interface_id, mac_address FROM `{$this->tableName}` WHERE mac_address = ? and stop_at is null  GROUP BY interface_id, mac_address order by 1 desc");
        } else {
            $data = $this->pdo->prepare("SELECT max(id) id, interface_id, mac_address FROM `{$this->tableName}` WHERE mac_address = ?  GROUP BY interface_id, mac_address order by 1 desc");
        }
        $data->execute([$mac]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->getById($d['id']);
        }
        return $response;
    }

    function deleteByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("DELETE FROM poll_fdb_history WHERE device_id = ?");
        $psth->execute([$device->getId()]);
        $this->clearByObject(new FdbHistory());
        $this->_ids = null;
        return $this;
    }

    function analyticsGetDuplicates($macAddress = null)
    {
        $WHERE = "WHERE 1=1 ";
        if($macAddress) {
            $WHERE .= " and io.mac_address = ". $this->pdo->quote($macAddress);
        }
        $psth = $this->pdo->prepare("SELECT min(oi.start_at) first_added_time,
               max(oi.start_at) last_added_time,
               GROUP_CONCAT(oi.interface_id) iface_ids,
               oi.vlan_id,
               oi.mac_address,
               count(*) count_duplicates,
               GROUP_CONCAT(DISTINCT d.group_id) allowed_groups
               FROM poll_fdb_history  oi
               JOIN device_interfaces  di on oi.interface_id = di.id
               JOIN devices d on di.device_id = d.id 
               $WHERE 
               GROUP BY mac_address, vlan_id
               HAVING count_duplicates > 1
        ");
        $psth->execute();
        $data = [];
        foreach ($psth->fetchAll() as $arr) {
            $ifaces = [];
            foreach (explode(",", $arr['iface_ids']) as $ifaceID) {
                $ifaces[] = $this->deviceInterfaceStorage->getById($ifaceID)->getAsArray();
            }
            $data[] = [
                'first_added_time' => $arr['first_added_time'],
                'last_added_time' => $arr['last_added_time'],
                'ifaces' => $ifaces,
                'vlan_id' => $arr['vlan_id'],
                'mac_address' => $arr['mac_address'],
                'count_duplicates' => $arr['count_duplicates'],
                'allowed_group_ids' => explode(",", $arr['allowed_groups']),
            ];
        }
        return  $data;
    }
}
