<?php


namespace WCAA\Storage\PollerData;


use Exception;
use WCAA\Models\Pollers\FdbHistory;
use WCAA\Models\Pollers\OntIdent;
use WCAA\Models\Devices\Device;
use WCAA\Models\Devices\DeviceInterface;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceInterfaceStorage;

/**
 * @method OntIdent fillByArr(OntIdent $object, $fetchArr = [])
 * Class OntIdentStorage
 * @package WCAA\Storage\Devices
 */
class OntIdentStorage extends AbstractStorage
{
    /**
     * @Inject
     * @var DeviceInterfaceStorage
     */
    protected $deviceInterfaceStorage;

    protected $tableName = 'poll_ont_ident';

    /**
     * @param OntIdent $object
     * @return OntIdent
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        if ($fillChildObjects) $fill->interface = $this->deviceInterfaceStorage->getById($fill->interface_id);
        return $fill;
    }

    /**
     * @param OntIdent $object
     * @return OntIdent
     */
    public function add($object)
    {
        $object->interface_id = $object->getInterface()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param OntIdent $object
     * @return OntIdent
     */
    public function update($object)
    {
        $object->interface_id = $object->getInterface()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return OntIdent[]
     */
    function fetchAll($fillChildren = true, $limit = null, $statuses = null)
    {
        if ($limit) {
            $limit = " limit {$limit}";
        }
        $where = '';
        if($statuses) {
             $statuses = array_map(function($status) {
                return $this->pdo->quote($status);
             }, $statuses);
             $where = " and `status` in (".join(",", $statuses).") ";
        }
        if ($fillChildren) {
            $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` order by id desc ");
            $psth->execute();
            $resp = [];
            foreach ($psth->fetchAll() as $e) {
                $interface = $this->fill(new OntIdent($e['id']));
                $resp[] = $interface;
            }
            return $resp;
        } else {
            $psth = $this->pdo->prepare("SELECT o.id o_id, o.created_at o_created_at,  o.type o_type, o.ident o_ident, o.vendor_info o_vendor_info,
       di.id i_id,
       di.created_at i_created_at,
       di.device_id i_device_id,
       di.name i_name,
       di.type i_type,
       di.description i_description,
       di.bind_key i_bind_key,
       di.updated_at i_updated_at,
       di.status i_status,
       di.status_changed i_status_changed,
       di.device_id i_device_id,
       di.agreement i_agreement,
       di.params i_params,
       di.billing_link i_billing_link       
FROM `poll_ont_ident` o
JOIN device_interfaces di on o.interface_id = di.id
WHERE 1 = 1 {$where}
order by o.id desc $limit");
            $psth->execute();
            $resp = [];
            foreach ($psth->fetchAll() as $e) {
                $interface = $this->fillByArr(new OntIdent(), [
                    'id' => $e['o_id'],
                    'created_at' => $e['o_created_at'],
                    'type' => $e['o_type'],
                    'ident' => $e['o_ident'],
                    'interface_id' => $e['i_id'],
                    'vendor_info' => $e['o_vendor_info'],
                ]);
                $interface->setInterface(
                    (new DeviceInterface())
                        ->setId($e['i_id'])
                        ->setType($e['i_type'])
                        ->setName($e['i_name'])
                        ->setDevice(new Device($e['i_device_id']))
                        ->setDeviceId($e['i_device_id'])
                        ->setBindKey($e['i_bind_key'])
                        ->setDescription($e['i_description'])
                        ->setStatus($e['i_status'])
                        ->setStatusChanged($e['i_status_changed'])
                        ->setAgreement($e['i_agreement'])
                        ->setParams($e['i_params'])
                        ->setBillingLink($e['i_billing_link'])
                );
                $resp[] = $interface;
            }
            return $resp;
        }
    }

    /**
     * @param Device[] $devices
     * @return OntIdent[]
     * @throws Exception
     */
    function getByDevices(array $devices)
    {
        $responses = [];
        foreach ($devices as $device) {
            $psth = $this->pdo->prepare("SELECT o.id o_id, o.created_at o_created_at,  o.type o_type, o.ident o_ident,o.vendor_info o_vendor_info,
       di.id i_id,
       di.created_at i_created_at,
       di.device_id i_device_id,
       di.name i_name,
       di.type i_type,
       di.description i_description,
       di.bind_key i_bind_key,
       di.updated_at i_updated_at,
       di.status i_status,
       di.device_id i_device_id
FROM `poll_ont_ident` o
JOIN device_interfaces di on o.interface_id = di.id
WHERE di.device_id = ?
order by o.id desc");
            $psth->execute([$device->getId()]);
            foreach ($psth->fetchAll() as $e) {
                $ident = $this->fillByArr(new OntIdent(), [
                    'id' => $e['o_id'],
                    'created_at' => $e['o_created_at'],
                    'type' => $e['o_type'],
                    'ident' => $e['o_ident'],
                    'interface_id' => $e['i_id'],
                    'vendor_info' => $e['o_vendor_info'],
                ]);
                $ident->setInterface(
                    (new DeviceInterface())
                        ->setId($e['i_id'])
                        ->setType($e['i_type'])
                        ->setName($e['i_name'])
                        ->setDevice($device)
                        ->setBindKey($e['i_bind_key'])
                        ->setDescription($e['i_description'])
                        ->setStatus($e['i_status'])
                );
                $responses[] = $ident;
            }
        }
        return  $responses;
    }

    /**
     * @param $id
     * @return OntIdent
     */
    function getById($id)
    {
        return $this->getObjectById(OntIdent::class, $id);
    }


    function getByInterface(DeviceInterface $interface)
    {
        $psth = $this->pdo->prepare("SELECT id FROM {$this->tableName} WHERE interface_id = ? ORDER BY id DESC LIMIT 1");
        $psth->execute([$interface->getId()]);
        if ($psth->rowCount() === 0) {
            return null;
        }
        $obj = $this->fill(new OntIdent($psth->fetch(\PDO::FETCH_ASSOC)['id']));
        $obj->interface = $interface;
        return $obj;
    }


    /**
     * @TODO Optimize ont idents queries
     * @param Device $device
     * @return OntIdent[]
     */
    function getByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("SELECT ont.id ont_id,
       ont.type ont_type,
       ont.ident ont_ident,
       ont.vendor_info,
       di.id iface_id,
       di.name iface_name,
       di.type iface_type,
       di.bind_key iface_bind_key
FROM poll_ont_ident ont
JOIN device_interfaces di on ont.interface_id = di.id
WHERE device_id = ?");
        $psth->execute([$device->getId()]);
        $latests = [];
        foreach ($psth->fetchAll() as $dt) {
            $obj = $this->fillByArr(new OntIdent(), [
                'id' => $dt['ont_id'],
                'type' => $dt['ont_type'],
                'ident' => $dt['ont_ident'],
                'vendor_info' => $dt['vendor_info'],
            ]);
            $obj->setInterface(
                (new DeviceInterface())
                    ->setDevice($device)
                    ->setId($dt['iface_id'])
                    ->setName($dt['iface_name'])
                    ->setType($dt['iface_type'])
                    ->setBindKey($dt['iface_bind_key'])
            );
            $latests[] = $obj;
        }
        return $latests;
    }

    /**
     * @param $searchLine
     * @param int $limit
     * @return OntIdent[]
     */
    function search($searchLine, $limit = 10)
    {
        $searchLine = strtoupper(str_replace([':', '.', ','], '', trim($searchLine)));
        $data = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE REPLACE(REPLACE(ident, ':', ''), '.', '') like ? order by  id desc limit ?");
        $data->execute(["%{$searchLine}%", $limit]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->getById($d['id']);
        }
        return $response;
    }
    /**
     * @param $searchLine
     * @param int $limit
     * @return OntIdent[]
     */
    function getByIdent($searchLine)
    {
        $searchLine = strtoupper(str_replace([':', '.', ','], '', trim($searchLine)));
        $data = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` WHERE  REPLACE(REPLACE(ident, ':', ''), '.', '') = ? order by  id desc");
        $data->execute([$searchLine]);
        $response = [];
        foreach ($data->fetchAll() as $d) {
            $response[] = $this->getById($d['id']);
        }
        return $response;
    }

    function deleteByDevice(Device $device)
    {
        $psth = $this->pdo->prepare("DELETE FROM poll_ont_ident WHERE interface_id in (SELECT id FROM device_interfaces WHERE device_id = ?)");
        $psth->execute([$device->getId()]);
        $this->clearByObject(new FdbHistory());
        $this->_ids = null;
        return $this;
    }

    /**
     * @return array
     */
    function analitycsGetDuplicatesList( $ident = null)
    {
        $WHERE = "WHERE 1=1 ";
        if($ident) {
            $WHERE .= " and io.ident = ". $this->pdo->quote($ident);
        }
        $psth = $this->pdo->prepare("SELECT min(oi.created_at) first_added_time,
       max(oi.created_at) last_added_time, 
       GROUP_CONCAT(oi.interface_id) iface_ids, 
       oi.type,
       ident, 
       count(*) 
           count_duplicates,
            GROUP_CONCAT(DISTINCT d.group_id) allowed_groups
            FROM poll_ont_ident  oi
            JOIN device_interfaces  di on oi.interface_id = di.id
            JOIN devices d on di.device_id = d.id 
            $WHERE 
            GROUP BY ident, type
            HAVING count_duplicates > 1");
        $psth->execute();
        $data = [];
        foreach ($psth->fetchAll() as $arr) {
            $ifaces = [];
            foreach (explode(",", $arr['iface_ids']) as $ifaceID) {
                $ifaces[] = $this->deviceInterfaceStorage->getById($ifaceID)->getAsArray();
            }
            $data[] = [
                'first_added_time' => $arr['first_added_time'],
                'last_added_time' => $arr['last_added_time'],
                'ifaces' => $ifaces,
                'type' => $arr['type'],
                'ident' => $arr['ident'],
                'count_duplicates' => $arr['count_duplicates'],
                'allowed_group_ids' => explode(",", $arr['allowed_groups']),
            ];
        }
        return  $data;
    }
}
