<?php


namespace WCAA\Storage\PollerData;


use Exception;
use WCAA\Models\Pollers\PollerProcessing;
use WCAA\Models\Devices\Device;
use WCAA\Storage\AbstractStorage;
use WCAA\Storage\Devices\DeviceStorage;

/**
 * @method PollerProcessing fillByArr(PollerProcessing $object, $fetchArr = [])
 * Class PollerProcessingStorage
 * @package WCAA\Storage\Devices
 */
class PollerProcessingStorage extends AbstractStorage
{
    /**
     * @Inject
     * @var DeviceStorage
     */
    protected $deviceStorage;

    protected $tableName = 'poller_processing';

    /**
     * @param PollerProcessing $object
     * @return PollerProcessing
     * @throws Exception
     */
    public function fill($object, $fillChildObjects = true)
    {
        $fill = parent::fill($object); // TODO: Change the autogenerated stub
        $fill->device = $this->deviceStorage->getById($fill->device_id);
        if(!$fill->error) {
            $fill->error = null;
        }

        return $fill;
    }

    /**
     * @param PollerProcessing $object
     * @return PollerProcessing
     */
    public function add($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::add($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param PollerProcessing $object
     * @return PollerProcessing
     */
    public function addOrUpdate($object)
    {

        $existed = $this->getByDeviceAndPoller($object->getDevice(), $object->getPoller());
        if(!$existed) {
            return $this->add($object); // TODO: Change the autogenerated stub
        }  else {
            $object->id = $existed->id;
            return $this->update($object);
        }
    }

    /**
     * @param PollerProcessing $object
     * @return PollerProcessing
     */
    public function update($object)
    {
        $object->device_id = $object->getDevice()->getId();
        return parent::update($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return PollerProcessing[]
     */
    function fetchAll() {
        $psth = $this->pdo->prepare("SELECT id FROM `{$this->tableName}` order by  id desc limit ?");
        $psth->execute([$this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new PollerProcessing($e['id']));
            $interface->setDevice($this->deviceStorage->getById($interface->device_id));
            $resp[] = $interface;
        }
        return $resp;
    }

    /**
     * @param $id
     * @return PollerProcessing
     */
    function getById($id) {
        return $this->getObjectById(PollerProcessing::class, $id);
    }

    /**
     * @param Device $device
     * @return PollerProcessing[]
     */
    function getByDevice(Device $device) {
        $psth = $this->pdo->prepare("SELECT * FROM `{$this->tableName}` WHERE device_id = ? order by id desc limit ?");
        $psth->execute([$device->getId(), $this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];
        foreach ($psth->fetchAll() as $e) {
            $interface = $this->fill(new PollerProcessing($e['id']));
            $interface->setDevice($device);
            $resp[] = $interface;
        }
        return $resp;
    }


    /**
     * @param Device $device
     * @return PollerProcessing|null
     */
    function getByDeviceAndPoller(Device $device, $poller) {
        $psth = $this->pdo->prepare("SELECT * FROM poller_processing WHERE device_id = ? and poller = ? order by id desc LIMIT 1");
        $psth->execute([$device->getId(), $poller]);
        if($psth->rowCount() == 0) {
            return null;
        }
        return $this->fillByArr(new PollerProcessing(), $psth->fetch());
    }

    function getExistedPollers() {
        return array_map(function ($e) {
            return $e['poller'];
        }, $this->pdo->query("SELECT distinct poller 
                                        from poller_processing order by 1")
            ->fetchAll(\PDO::FETCH_ASSOC)
        );
    }

    function getCountByFilter($start, $stop, $deviceIds = [], $collects = [], $status = null) {
        $query = "SELECT id
            FROM `{$this->tableName}` WHERE (start_at BETWEEN ? and ?) ";
        if ($collects) {
            $collectsQuotes = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_STR);
            }, $collects);
            $query .= " and poller in (" . join(',', $collectsQuotes) . ")";
        }
        if ($deviceIds) {
            $deviceIds = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_INT);
            }, $deviceIds);
            $query .= " and device_id in (" . join(',', $deviceIds) . ")";
        }
        if ($status) {
            $status = $this->pdo->quote($status);
            $query .= " and `status` = $status";
        }

        $psth = $this->pdo->prepare($query);
        $psth->execute([$start, $stop]);
        return $psth->rowCount();
    }

    function getByFilter($start, $stop, $deviceIds = [], $collects = [], $status = null) {
        $query = "SELECT id, start_at, stop_at, poller, device_id, error, status 
            FROM `{$this->tableName}` WHERE (start_at BETWEEN ? and ?) ";
        if ($collects) {
            $collectsQuotes = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_STR);
            }, $collects);
            $query .= " and poller in (" . join(',', $collectsQuotes) . ")";
        }
        if ($deviceIds) {
            $deviceIds = array_map(function ($e) {
                return  $this->pdo->quote($e, \PDO::PARAM_INT);
            }, $deviceIds);
            $query .= " and device_id in (" . join(',', $deviceIds) . ")";
        }
        if ($status) {
            $status = $this->pdo->quote($status);
            $query .= " and `status` = $status";
        }

        $query .= " ORDER BY 1 desc limit ?";
        $psth = $this->pdo->prepare($query);
        $psth->execute([$start, $stop, $this->app->conf('panel.logs_return_result_limit')]);
        $resp = [];

        foreach ($psth->fetchAll() as $d) {
            $r = $this->fillByArr(new PollerProcessing(), $d);
            $r->setDevice($this->deviceStorage->getById($d['device_id']));
            $resp[] = $r;
        }
        return $resp;
    }

    /**
     * @return PollerProcessing[]
     */
    function getInProcess() {
        $query = "SELECT id, start_at, stop_at, poller, device_id, error, status 
            FROM `{$this->tableName}` WHERE stop_at is null";

        $query .= " ORDER BY 1 desc";
        $psth = $this->pdo->prepare($query);
        $psth->execute();
        $resp = [];
        foreach ($psth->fetchAll() as $d) {
            $r = $this->fillByArr(new PollerProcessing(), $d);
            $r->setDevice($this->deviceStorage->getById($d['device_id']));
            $resp[] = $r;
        }
        return $resp;
    }

    /**
     * @param Device|null $device
     * @param bool $onlySuccess
     * @return PollerProcessing[]
     */
    function getLatests(?Device $device = null, $onlySuccess = false): array
    {
        $where = " c.id != -1";
        $where_in = ' id != -1';
        if($device) {
            $where_in .= " and device_id = {$device->getId()}";
            $where .= " and c.device_id = {$device->getId()}";
        }
        if($onlySuccess) {
            $where_in .= " and status = 'SUCCESS'";
            $where .= " and c.status = 'SUCCESS'";
        }
        $query = "SELECT c.id,
       c.poller,
       c.device_id,
       c.start_at,
       c.stop_at,
       c.status,
       c.error
FROM poller_processing c
         JOIN (
    SELECT max(id) id, device_id, poller
    FROM poller_processing
    WHERE $where_in
    GROUP BY device_id, poller
) cd on cd.id = c.id
WHERE $where order by 1 desc";
        $resp = [];
        foreach ($this->pdo->query($query)->fetchAll() as $d) {
            $r = $this->fillByArr(new PollerProcessing(), $d);
            $r->setDevice($this->deviceStorage->getById($d['device_id']));
            $resp[] = $r;
        }
        return $resp;
    }
}
